namespace EFTest.ModelTestFiles
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class ModelTest : DbContext
    {
        public ModelTest()
            : base("name=ModelTest")
        {
        }

        public virtual DbSet<C_ErrorLogBase> C_ErrorLogBase { get; set; }
        public virtual DbSet<AccumConfig> AccumConfigs { get; set; }
        public virtual DbSet<ACH_History> ACH_History { get; set; }
        public virtual DbSet<ACH_HistoryCashedCheck> ACH_HistoryCashedCheck { get; set; }
        public virtual DbSet<ACH_Recv> ACH_Recv { get; set; }
        public virtual DbSet<ACH_ReturnCode> ACH_ReturnCode { get; set; }
        public virtual DbSet<ACH_Sent> ACH_Sent { get; set; }
        public virtual DbSet<ACHAck> ACHAcks { get; set; }
        public virtual DbSet<ACHBank> ACHBanks { get; set; }
        public virtual DbSet<ACHBankConfig> ACHBankConfigs { get; set; }
        public virtual DbSet<ACHBankConfigException> ACHBankConfigExceptions { get; set; }
        public virtual DbSet<ACHBatchHeader> ACHBatchHeaders { get; set; }
        public virtual DbSet<ACHDetail> ACHDetails { get; set; }
        public virtual DbSet<ACHDetailAddendum> ACHDetailAddendums { get; set; }
        public virtual DbSet<ACHPending> ACHPendings { get; set; }
        public virtual DbSet<ACHPresentment> ACHPresentments { get; set; }
        public virtual DbSet<ACHPresentmentType> ACHPresentmentTypes { get; set; }
        public virtual DbSet<ACHProcessingQueue> ACHProcessingQueues { get; set; }
        public virtual DbSet<ACHProcessingType> ACHProcessingTypes { get; set; }
        public virtual DbSet<ACHQueue> ACHQueues { get; set; }
        public virtual DbSet<ACHReason> ACHReasons { get; set; }
        public virtual DbSet<ACHSentParent> ACHSentParents { get; set; }
        public virtual DbSet<AdAstraWebInventory> AdAstraWebInventories { get; set; }
        public virtual DbSet<AgentAction> AgentActions { get; set; }
        public virtual DbSet<AgentResult> AgentResults { get; set; }
        public virtual DbSet<AlternateLender> AlternateLenders { get; set; }
        public virtual DbSet<AMLAdditionalParty> AMLAdditionalParties { get; set; }
        public virtual DbSet<AMLFileLog> AMLFileLogs { get; set; }
        public virtual DbSet<AMLForeignAddress> AMLForeignAddresses { get; set; }
        public virtual DbSet<AMLOccupation> AMLOccupations { get; set; }
        public virtual DbSet<AMLThresholdRule> AMLThresholdRules { get; set; }
        public virtual DbSet<AMLThresholdRuleTransXref> AMLThresholdRuleTransXrefs { get; set; }
        public virtual DbSet<ApiApplication> ApiApplications { get; set; }
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<AppValue> AppValues { get; set; }
        public virtual DbSet<AreaCode> AreaCodes { get; set; }
        public virtual DbSet<Attorney> Attorneys { get; set; }
        public virtual DbSet<AttorneyLoan> AttorneyLoans { get; set; }
        public virtual DbSet<AttorneyPayment> AttorneyPayments { get; set; }
        public virtual DbSet<AUDDISAdviceReport> AUDDISAdviceReports { get; set; }
        public virtual DbSet<AUDDISReasonCodeMapping> AUDDISReasonCodeMappings { get; set; }
        public virtual DbSet<AutoBankingReport> AutoBankingReports { get; set; }
        public virtual DbSet<AutoReport> AutoReports { get; set; }
        public virtual DbSet<AutoReportEmail> AutoReportEmails { get; set; }
        public virtual DbSet<AutoReportRunSchedule> AutoReportRunSchedules { get; set; }
        public virtual DbSet<AutoReportSchedule> AutoReportSchedules { get; set; }
        public virtual DbSet<AutoReportTab> AutoReportTabs { get; set; }
        public virtual DbSet<BalSheet_TransDetail> BalSheet_TransDetail { get; set; }
        public virtual DbSet<BalSheet2> BalSheet2 { get; set; }
        public virtual DbSet<BalSheetColumns2> BalSheetColumns2 { get; set; }
        public virtual DbSet<Bank_Status> Bank_Status { get; set; }
        public virtual DbSet<BankClassification> BankClassifications { get; set; }
        public virtual DbSet<BankClassificationType> BankClassificationTypes { get; set; }
        public virtual DbSet<BANK> BANKS { get; set; }
        public virtual DbSet<BanksParent> BanksParents { get; set; }
        public virtual DbSet<BillerOCRRegion> BillerOCRRegions { get; set; }
        public virtual DbSet<BillPayBiller> BillPayBillers { get; set; }
        public virtual DbSet<BillPayVendor> BillPayVendors { get; set; }
        public virtual DbSet<BlockedAddress> BlockedAddresses { get; set; }
        public virtual DbSet<BlockMailing> BlockMailings { get; set; }
        public virtual DbSet<BlockReason> BlockReasons { get; set; }
        public virtual DbSet<BusinessLoan> BusinessLoans { get; set; }
        public virtual DbSet<CABLender> CABLenders { get; set; }
        public virtual DbSet<CapsCCTXRef> CapsCCTXRefs { get; set; }
        public virtual DbSet<CapsHold> CapsHolds { get; set; }
        public virtual DbSet<CapsRun> CapsRuns { get; set; }
        public virtual DbSet<CapsRunStatu> CapsRunStatus { get; set; }
        public virtual DbSet<CapsSkipReason> CapsSkipReasons { get; set; }
        public virtual DbSet<CapsUpdate> CapsUpdates { get; set; }
        public virtual DbSet<CardBatchSettle> CardBatchSettles { get; set; }
        public virtual DbSet<CashedCheck> CashedChecks { get; set; }
        public virtual DbSet<CashedCheckImage> CashedCheckImages { get; set; }
        public virtual DbSet<CashedCheckMICR> CashedCheckMICRs { get; set; }
        public virtual DbSet<CashedCheckPayment> CashedCheckPayments { get; set; }
        public virtual DbSet<CashedCheckPaymentRefund> CashedCheckPaymentRefunds { get; set; }
        public virtual DbSet<CashedCheckPaymentRefundXRef> CashedCheckPaymentRefundXRefs { get; set; }
        public virtual DbSet<CashMoneyToCuroXRef> CashMoneyToCuroXRefs { get; set; }
        public virtual DbSet<CC_Status> CC_Status { get; set; }
        public virtual DbSet<CCardResponse> CCardResponses { get; set; }
        public virtual DbSet<CCardRespons> CCardResponses1 { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<CheckAgain> CheckAgains { get; set; }
        public virtual DbSet<CheckAgainHistory> CheckAgainHistories { get; set; }
        public virtual DbSet<CheckPaymentType> CheckPaymentTypes { get; set; }
        public virtual DbSet<CheckReturn> CheckReturns { get; set; }
        public virtual DbSet<CheckType> CheckTypes { get; set; }
        public virtual DbSet<chk_type> chk_type { get; set; }
        public virtual DbSet<CollBonusDetail> CollBonusDetails { get; set; }
        public virtual DbSet<CollBonusPTP> CollBonusPTPs { get; set; }
        public virtual DbSet<CollBonusTask> CollBonusTasks { get; set; }
        public virtual DbSet<CollectionAction> CollectionActions { get; set; }
        public virtual DbSet<CollectionAgency> CollectionAgencies { get; set; }
        public virtual DbSet<CollectionAgencyPct> CollectionAgencyPcts { get; set; }
        public virtual DbSet<CollectionMovement> CollectionMovements { get; set; }
        public virtual DbSet<CollectionNote> CollectionNotes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyACHBank> CompanyACHBanks { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<CompanyDocumentResource> CompanyDocumentResources { get; set; }
        public virtual DbSet<CompanyExpenseType> CompanyExpenseTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CourtesyPayout> CourtesyPayouts { get; set; }
        public virtual DbSet<CpiuDetail> CpiuDetails { get; set; }
        public virtual DbSet<CpiuExceptionReport> CpiuExceptionReports { get; set; }
        public virtual DbSet<CpiuMaster> CpiuMasters { get; set; }
        public virtual DbSet<CreditCardAttempt> CreditCardAttempts { get; set; }
        public virtual DbSet<CreditCardBlock> CreditCardBlocks { get; set; }
        public virtual DbSet<CreditCardBrand> CreditCardBrands { get; set; }
        public virtual DbSet<CreditCardResultCode> CreditCardResultCodes { get; set; }
        public virtual DbSet<CreditCardResultCodeType> CreditCardResultCodeTypes { get; set; }
        public virtual DbSet<CreditCard> CreditCards { get; set; }
        public virtual DbSet<CreditCardsEdit> CreditCardsEdits { get; set; }
        public virtual DbSet<CreditCardTran> CreditCardTrans { get; set; }
        public virtual DbSet<CreditCardVendor> CreditCardVendors { get; set; }
        public virtual DbSet<CreditCardXRef> CreditCardXRefs { get; set; }
        public virtual DbSet<CreditRptPrint> CreditRptPrints { get; set; }
        public virtual DbSet<CreditVendor> CreditVendors { get; set; }
        public virtual DbSet<CreditVendorData> CreditVendorDatas { get; set; }
        public virtual DbSet<CuroHelp> CuroHelps { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyExchangeConfig> CurrencyExchangeConfigs { get; set; }
        public virtual DbSet<CurrencyExchangeTran> CurrencyExchangeTrans { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerActivity> CustomerActivities { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerAddressEdit> CustomerAddressEdits { get; set; }
        public virtual DbSet<CustomerAppDate> CustomerAppDates { get; set; }
        public virtual DbSet<CustomerBusiness> CustomerBusinesses { get; set; }
        public virtual DbSet<CustomerCreditRpt> CustomerCreditRpts { get; set; }
        public virtual DbSet<CustomerCreditRptDetail> CustomerCreditRptDetails { get; set; }
        public virtual DbSet<CustomerDocument> CustomerDocuments { get; set; }
        public virtual DbSet<CustomerEarnedCredit> CustomerEarnedCredits { get; set; }
        public virtual DbSet<CustomerEdit> CustomerEdits { get; set; }
        public virtual DbSet<CustomerEmployer> CustomerEmployers { get; set; }
        public virtual DbSet<CustomerEmployerEdit> CustomerEmployerEdits { get; set; }
        public virtual DbSet<CustomerExpense> CustomerExpenses { get; set; }
        public virtual DbSet<CustomerExpenseDetail> CustomerExpenseDetails { get; set; }
        public virtual DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual DbSet<CustomerFeedbackCategory> CustomerFeedbackCategories { get; set; }
        public virtual DbSet<CustomerFeedbackResolution> CustomerFeedbackResolutions { get; set; }
        public virtual DbSet<CustomerFeedbackType> CustomerFeedbackTypes { get; set; }
        public virtual DbSet<CustomerFeedbackTypeCategoryXRef> CustomerFeedbackTypeCategoryXRefs { get; set; }
        public virtual DbSet<CustomerFlash> CustomerFlashes { get; set; }
        public virtual DbSet<CustomerFlashORRebate> CustomerFlashORRebates { get; set; }
        public virtual DbSet<CustomerFlashQuestion> CustomerFlashQuestions { get; set; }
        public virtual DbSet<CustomerFlashResponse> CustomerFlashResponses { get; set; }
        public virtual DbSet<CustomerIdentification> CustomerIdentifications { get; set; }
        public virtual DbSet<CustomerIdentificationEdit> CustomerIdentificationEdits { get; set; }
        public virtual DbSet<CustomerIncome> CustomerIncomes { get; set; }
        public virtual DbSet<CustomerLastCreditReport> CustomerLastCreditReports { get; set; }
        public virtual DbSet<CustomerLead> CustomerLeads { get; set; }
        public virtual DbSet<CustomerLeadAction> CustomerLeadActions { get; set; }
        public virtual DbSet<CustomerLeadActivity> CustomerLeadActivities { get; set; }
        public virtual DbSet<CustomerLeadLocation> CustomerLeadLocations { get; set; }
        public virtual DbSet<CustomerLeadNote> CustomerLeadNotes { get; set; }
        public virtual DbSet<CustomerLeadReason> CustomerLeadReasons { get; set; }
        public virtual DbSet<CustomerLeadStatu> CustomerLeadStatus { get; set; }
        public virtual DbSet<CustomerLeadStatusReason> CustomerLeadStatusReasons { get; set; }
        public virtual DbSet<CustomerMergeHistory> CustomerMergeHistories { get; set; }
        public virtual DbSet<CustomerNote> CustomerNotes { get; set; }
        public virtual DbSet<CustomerPhoneNumber> CustomerPhoneNumbers { get; set; }
        public virtual DbSet<CustomerPhoneNumberEdit> CustomerPhoneNumberEdits { get; set; }
        public virtual DbSet<CustomerResponse> CustomerResponses { get; set; }
        public virtual DbSet<CustomerSDNCert> CustomerSDNCerts { get; set; }
        public virtual DbSet<CustomerSurvey> CustomerSurveys { get; set; }
        public virtual DbSet<dba_indexDefragLog> dba_indexDefragLog { get; set; }
        public virtual DbSet<DCardChargeBackXRef> DCardChargeBackXRefs { get; set; }
        public virtual DbSet<DDI> DDIs { get; set; }
        public virtual DbSet<DDIACHHistory> DDIACHHistories { get; set; }
        public virtual DbSet<DDIEditHistory> DDIEditHistories { get; set; }
        public virtual DbSet<DDISend> DDISends { get; set; }
        public virtual DbSet<DDISendDetail> DDISendDetails { get; set; }
        public virtual DbSet<DDISendQueue> DDISendQueues { get; set; }
        public virtual DbSet<DDIStatu> DDIStatus { get; set; }
        public virtual DbSet<Denomination> Denominations { get; set; }
        public virtual DbSet<DepositBag> DepositBags { get; set; }
        public virtual DbSet<DepositBagDetail> DepositBagDetails { get; set; }
        public virtual DbSet<DepositChk> DepositChks { get; set; }
        public virtual DbSet<DepositChkDetail> DepositChkDetails { get; set; }
        public virtual DbSet<DepositDebitCard> DepositDebitCards { get; set; }
        public virtual DbSet<DepositDebitCardDetail> DepositDebitCardDetails { get; set; }
        public virtual DbSet<DialerJob> DialerJobs { get; set; }
        public virtual DbSet<DialerKey> DialerKeys { get; set; }
        public virtual DbSet<DialerResultCode> DialerResultCodes { get; set; }
        public virtual DbSet<DirtyDataGroup> DirtyDataGroups { get; set; }
        public virtual DbSet<DirtyDataJob> DirtyDataJobs { get; set; }
        public virtual DbSet<DirtyDataJobRun> DirtyDataJobRuns { get; set; }
        public virtual DbSet<DiscountLocation> DiscountLocations { get; set; }
        public virtual DbSet<DiscountMaster> DiscountMasters { get; set; }
        public virtual DbSet<DiscountMasterLoanProduct> DiscountMasterLoanProducts { get; set; }
        public virtual DbSet<DiscountSecurity> DiscountSecurities { get; set; }
        public virtual DbSet<DiscountType> DiscountTypes { get; set; }
        public virtual DbSet<DiscountUsed> DiscountUseds { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DMA> DMAs { get; set; }
        public virtual DbSet<Doc10000Trans> Doc10000Trans { get; set; }
        public virtual DbSet<Doc10000TransDetail> Doc10000TransDetail { get; set; }
        public virtual DbSet<DocImage> DocImages { get; set; }
        public virtual DbSet<DocPrint> DocPrints { get; set; }
        public virtual DbSet<DocTemplate> DocTemplates { get; set; }
        public virtual DbSet<DocumentPrinting> DocumentPrintings { get; set; }
        public virtual DbSet<DocumentResource> DocumentResources { get; set; }
        public virtual DbSet<DocumentSigningStatu> DocumentSigningStatus { get; set; }
        public virtual DbSet<DocuwareCabinet> DocuwareCabinets { get; set; }
        public virtual DbSet<DocuwareLoanLkup> DocuwareLoanLkups { get; set; }
        public virtual DbSet<DocuwareStatu> DocuwareStatus { get; set; }
        public virtual DbSet<DrawerMaster> DrawerMasters { get; set; }
        public virtual DbSet<DrawerMasterParsedCash> DrawerMasterParsedCashes { get; set; }
        public virtual DbSet<DrawerService> DrawerServices { get; set; }
        public virtual DbSet<DrawerX> DrawerXes { get; set; }
        public virtual DbSet<DrawerXService> DrawerXServices { get; set; }
        public virtual DbSet<DrawerZ> DrawerZs { get; set; }
        public virtual DbSet<DrawerZCash> DrawerZCashes { get; set; }
        public virtual DbSet<DrawerZService> DrawerZServices { get; set; }
        public virtual DbSet<DualApprovalMessage> DualApprovalMessages { get; set; }
        public virtual DbSet<EarnedCreditTran> EarnedCreditTrans { get; set; }
        public virtual DbSet<EarnedCreditType> EarnedCreditTypes { get; set; }
        public virtual DbSet<EmailDisposition> EmailDispositions { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EndOfDayInventoryDetail> EndOfDayInventoryDetails { get; set; }
        public virtual DbSet<EndOfDayRpt> EndOfDayRpts { get; set; }
        public virtual DbSet<EndOfDayRptDetail> EndOfDayRptDetails { get; set; }
        public virtual DbSet<EOscarBatch> EOscarBatches { get; set; }
        public virtual DbSet<EOscarBatchDetail> EOscarBatchDetails { get; set; }
        public virtual DbSet<EOscarDetailDisputeCode> EOscarDetailDisputeCodes { get; set; }
        public virtual DbSet<EOscarDisputeCode> EOscarDisputeCodes { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<ESignLoan> ESignLoans { get; set; }
        public virtual DbSet<ESignLoanStatu> ESignLoanStatus { get; set; }
        public virtual DbSet<ESignOptIn> ESignOptIns { get; set; }
        public virtual DbSet<ESignOptInDoc> ESignOptInDocs { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<ExchangeRateDaily> ExchangeRateDailies { get; set; }
        public virtual DbSet<ExcludeFromCapsHistory> ExcludeFromCapsHistories { get; set; }
        public virtual DbSet<ExpenseType> ExpenseTypes { get; set; }
        public virtual DbSet<ExperianCardValidation> ExperianCardValidations { get; set; }
        public virtual DbSet<ExternalAppConfig> ExternalAppConfigs { get; set; }
        public virtual DbSet<ExternalAppMaster> ExternalAppMasters { get; set; }
        public virtual DbSet<ExternalAppRunDate> ExternalAppRunDates { get; set; }
        public virtual DbSet<ExternalApp> ExternalApps { get; set; }
        public virtual DbSet<FcrmAmlCheckTypeXref> FcrmAmlCheckTypeXrefs { get; set; }
        public virtual DbSet<FcrmAmlServiceXRef> FcrmAmlServiceXRefs { get; set; }
        public virtual DbSet<FcrmAmlTransCode> FcrmAmlTransCodes { get; set; }
        public virtual DbSet<FcrmAmlTransCodeXRef> FcrmAmlTransCodeXRefs { get; set; }
        public virtual DbSet<ForceApprovalQuestion> ForceApprovalQuestions { get; set; }
        public virtual DbSet<ForceApprovalValue> ForceApprovalValues { get; set; }
        public virtual DbSet<FormLetter> FormLetters { get; set; }
        public virtual DbSet<FormLetterBatch> FormLetterBatches { get; set; }
        public virtual DbSet<FormLetterBatchBuildLetterProgress> FormLetterBatchBuildLetterProgresses { get; set; }
        public virtual DbSet<FormLetterBatchStatu> FormLetterBatchStatus { get; set; }
        public virtual DbSet<FormLetterBatchValidation> FormLetterBatchValidations { get; set; }
        public virtual DbSet<FormLetterBatchVendorFile> FormLetterBatchVendorFiles { get; set; }
        public virtual DbSet<FormLetterConfig> FormLetterConfigs { get; set; }
        public virtual DbSet<FormLetterEmail> FormLetterEmails { get; set; }
        public virtual DbSet<FormLetterLoanHistoryFile> FormLetterLoanHistoryFiles { get; set; }
        public virtual DbSet<FormLetterLoanHistoryState> FormLetterLoanHistoryStates { get; set; }
        public virtual DbSet<FormLetterOnDemand> FormLetterOnDemands { get; set; }
        public virtual DbSet<FormLetterPrinted> FormLetterPrinteds { get; set; }
        public virtual DbSet<FormLetterProduct> FormLetterProducts { get; set; }
        public virtual DbSet<FormLetterResult> FormLetterResults { get; set; }
        public virtual DbSet<FurtherFinanceExecutionLog> FurtherFinanceExecutionLogs { get; set; }
        public virtual DbSet<FurtherFinanceExecutionLogDetail> FurtherFinanceExecutionLogDetails { get; set; }
        public virtual DbSet<FurtherFinanceJobType> FurtherFinanceJobTypes { get; set; }
        public virtual DbSet<FurtherFinanceOutcome> FurtherFinanceOutcomes { get; set; }
        public virtual DbSet<FurtherFinanceQuery> FurtherFinanceQueries { get; set; }
        public virtual DbSet<FurtherFinanceResult> FurtherFinanceResults { get; set; }
        public virtual DbSet<FurtherFinanceResultDetail> FurtherFinanceResultDetails { get; set; }
        public virtual DbSet<GalileoResponseCode> GalileoResponseCodes { get; set; }
        public virtual DbSet<GiftCard> GiftCards { get; set; }
        public virtual DbSet<GLAcct> GLAccts { get; set; }
        public virtual DbSet<GLAcctGlobal> GLAcctGlobals { get; set; }
        public virtual DbSet<GLAcctGroup> GLAcctGroups { get; set; }
        public virtual DbSet<Global> Globals { get; set; }
        public virtual DbSet<GlobalState> GlobalStates { get; set; }
        public virtual DbSet<GoldConfig> GoldConfigs { get; set; }
        public virtual DbSet<GoldDailyBag> GoldDailyBags { get; set; }
        public virtual DbSet<GoldDailyBagDetail> GoldDailyBagDetails { get; set; }
        public virtual DbSet<GoldItem> GoldItems { get; set; }
        public virtual DbSet<GoldTran> GoldTrans { get; set; }
        public virtual DbSet<GoldTransCustomer> GoldTransCustomers { get; set; }
        public virtual DbSet<GoldTransDetail> GoldTransDetails { get; set; }
        public virtual DbSet<GoldTransfer> GoldTransfers { get; set; }
        public virtual DbSet<GoldTransferDetail> GoldTransferDetails { get; set; }
        public virtual DbSet<GoldTransStoneDetail> GoldTransStoneDetails { get; set; }
        public virtual DbSet<GoodCustomerStudy> GoodCustomerStudies { get; set; }
        public virtual DbSet<IatDialerResult> IatDialerResults { get; set; }
        public virtual DbSet<IdentificationType> IdentificationTypes { get; set; }
        public virtual DbSet<IdentificationTypeAML> IdentificationTypeAMLs { get; set; }
        public virtual DbSet<IdentificationTypeRule> IdentificationTypeRules { get; set; }
        public virtual DbSet<IdentificationTypeRuleXRef> IdentificationTypeRuleXRefs { get; set; }
        public virtual DbSet<IdentificationTypeState> IdentificationTypeStates { get; set; }
        public virtual DbSet<IdentificationTypeVerify> IdentificationTypeVerifies { get; set; }
        public virtual DbSet<IINRange> IINRanges { get; set; }
        public virtual DbSet<ImageCashLetter> ImageCashLetters { get; set; }
        public virtual DbSet<ImageCashLetterBundle> ImageCashLetterBundles { get; set; }
        public virtual DbSet<ImageCashLetterDetail> ImageCashLetterDetails { get; set; }
        public virtual DbSet<IncomeJobType> IncomeJobTypes { get; set; }
        public virtual DbSet<IncomeSource> IncomeSources { get; set; }
        public virtual DbSet<IncomeType> IncomeTypes { get; set; }
        public virtual DbSet<IncomeTypeLocation> IncomeTypeLocations { get; set; }
        public virtual DbSet<IncomeVerificationMessage> IncomeVerificationMessages { get; set; }
        public virtual DbSet<IncomeVerifyMethod> IncomeVerifyMethods { get; set; }
        public virtual DbSet<IncomeVerifyMethodLocation> IncomeVerifyMethodLocations { get; set; }
        public virtual DbSet<InitGLList> InitGLLists { get; set; }
        public virtual DbSet<InsuranceClaim> InsuranceClaims { get; set; }
        public virtual DbSet<InsuranceClaimEdit> InsuranceClaimEdits { get; set; }
        public virtual DbSet<InsuranceClaimStatu> InsuranceClaimStatus { get; set; }
        public virtual DbSet<InsurancePayment> InsurancePayments { get; set; }
        public virtual DbSet<InsurancePaymentBatch> InsurancePaymentBatches { get; set; }
        public virtual DbSet<InsuranceStatu> InsuranceStatus { get; set; }
        public virtual DbSet<InternalProcessEmail> InternalProcessEmails { get; set; }
        public virtual DbSet<InvalidCustomerAddress> InvalidCustomerAddresses { get; set; }
        public virtual DbSet<IPBlock> IPBlocks { get; set; }
        public virtual DbSet<IpToCountry> IpToCountries { get; set; }
        public virtual DbSet<Issuer> Issuers { get; set; }
        public virtual DbSet<IssuerEdit> IssuerEdits { get; set; }
        public virtual DbSet<LegalVerification> LegalVerifications { get; set; }
        public virtual DbSet<Lender> Lenders { get; set; }
        public virtual DbSet<LienHolder> LienHolders { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<LoanApplication> LoanApplications { get; set; }
        public virtual DbSet<LoanApplicationAddress> LoanApplicationAddresses { get; set; }
        public virtual DbSet<LoanApplicationAffordSurvey_ToBeDeleted> LoanApplicationAffordSurvey_ToBeDeleted { get; set; }
        public virtual DbSet<LoanApplicationEmployer> LoanApplicationEmployers { get; set; }
        public virtual DbSet<LoanApplicationExpense> LoanApplicationExpenses { get; set; }
        public virtual DbSet<LoanApplicationExpenseDetail> LoanApplicationExpenseDetails { get; set; }
        public virtual DbSet<LoanApplicationIncome> LoanApplicationIncomes { get; set; }
        public virtual DbSet<LoanApplicationProduct> LoanApplicationProducts { get; set; }
        public virtual DbSet<LoanApplicationVehicleInformation> LoanApplicationVehicleInformations { get; set; }
        public virtual DbSet<LoanCCallChange> LoanCCallChanges { get; set; }
        public virtual DbSet<LoanCheck> LoanChecks { get; set; }
        public virtual DbSet<LoanChkAcctChange> LoanChkAcctChanges { get; set; }
        public virtual DbSet<LoanConfigApplyPaymentOrder> LoanConfigApplyPaymentOrders { get; set; }
        public virtual DbSet<LoanCoPledger> LoanCoPledgers { get; set; }
        public virtual DbSet<LoanCreditLimit> LoanCreditLimits { get; set; }
        public virtual DbSet<LoanDepositOrderHistory> LoanDepositOrderHistories { get; set; }
        public virtual DbSet<LoanDepositOrderResetReason> LoanDepositOrderResetReasons { get; set; }
        public virtual DbSet<LoanDoc> LoanDocs { get; set; }
        public virtual DbSet<LoanDocPrinted> LoanDocPrinteds { get; set; }
        public virtual DbSet<LoanDocType> LoanDocTypes { get; set; }
        public virtual DbSet<LoanDocUpload> LoanDocUploads { get; set; }
        public virtual DbSet<LoanDocUsed> LoanDocUseds { get; set; }
        public virtual DbSet<LoanDueDateChange> LoanDueDateChanges { get; set; }
        public virtual DbSet<LoanFunding> LoanFundings { get; set; }
        public virtual DbSet<LoanFundingMethodHistory> LoanFundingMethodHistories { get; set; }
        public virtual DbSet<LoanImport> LoanImports { get; set; }
        public virtual DbSet<LoanImportXRef> LoanImportXRefs { get; set; }
        public virtual DbSet<LoanIncome> LoanIncomes { get; set; }
        public virtual DbSet<LoanNote> LoanNotes { get; set; }
        public virtual DbSet<LoanOverride> LoanOverrides { get; set; }
        public virtual DbSet<LoanPayment> LoanPayments { get; set; }
        public virtual DbSet<LoanPaymentAddToQueue> LoanPaymentAddToQueues { get; set; }
        public virtual DbSet<LoanPaymentCheckPaymentTypeXref> LoanPaymentCheckPaymentTypeXrefs { get; set; }
        public virtual DbSet<LoanPaymentDecreaseAmountOwed> LoanPaymentDecreaseAmountOweds { get; set; }
        public virtual DbSet<LoanPaymentDueDate> LoanPaymentDueDates { get; set; }
        public virtual DbSet<LoanPaymentInsuranceClaimXRef> LoanPaymentInsuranceClaimXRefs { get; set; }
        public virtual DbSet<LoanPaymentLoanCheckXref> LoanPaymentLoanCheckXrefs { get; set; }
        public virtual DbSet<LoanPaymentMPay> LoanPaymentMPays { get; set; }
        public virtual DbSet<LoanPaymentMPayRefund> LoanPaymentMPayRefunds { get; set; }
        public virtual DbSet<LoanPaymentOpenEnd> LoanPaymentOpenEnds { get; set; }
        public virtual DbSet<LoanPaymentOpenEndRefund> LoanPaymentOpenEndRefunds { get; set; }
        public virtual DbSet<LoanPaymentRefund> LoanPaymentRefunds { get; set; }
        public virtual DbSet<LoanPaymentRefundXRef> LoanPaymentRefundXRefs { get; set; }
        public virtual DbSet<LoanPaymentRescind> LoanPaymentRescinds { get; set; }
        public virtual DbSet<LoanPaymentSPay> LoanPaymentSPays { get; set; }
        public virtual DbSet<LoanPaymentSPayRefund> LoanPaymentSPayRefunds { get; set; }
        public virtual DbSet<LoanPaymentSuspendInterest> LoanPaymentSuspendInterests { get; set; }
        public virtual DbSet<LoanPaymentWaiveRIFee> LoanPaymentWaiveRIFees { get; set; }
        public virtual DbSet<LoanProduct> LoanProducts { get; set; }
        public virtual DbSet<LoanProductBlocked> LoanProductBlockeds { get; set; }
        public virtual DbSet<LoanProductConfig> LoanProductConfigs { get; set; }
        public virtual DbSet<LoanProductConfigApprovalRate> LoanProductConfigApprovalRates { get; set; }
        public virtual DbSet<LoanProductConfigEdit> LoanProductConfigEdits { get; set; }
        public virtual DbSet<LoanProductConfigInsuranceRate> LoanProductConfigInsuranceRates { get; set; }
        public virtual DbSet<LoanProductConfigInterestRate> LoanProductConfigInterestRates { get; set; }
        public virtual DbSet<LoanProductConfigLoanFeeRate> LoanProductConfigLoanFeeRates { get; set; }
        public virtual DbSet<LoanProductConfigLoanStat> LoanProductConfigLoanStats { get; set; }
        public virtual DbSet<LoanProductConfigMaxLoanAmtRate> LoanProductConfigMaxLoanAmtRates { get; set; }
        public virtual DbSet<LoanProductConfigOpenEnd> LoanProductConfigOpenEnds { get; set; }
        public virtual DbSet<LoanProductConfigRIRate> LoanProductConfigRIRates { get; set; }
        public virtual DbSet<LoanProductConfigTitle> LoanProductConfigTitles { get; set; }
        public virtual DbSet<LoanProductEnableNewLoan> LoanProductEnableNewLoans { get; set; }
        public virtual DbSet<LoanProductFeature> LoanProductFeatures { get; set; }
        public virtual DbSet<LoanProductFeatureType> LoanProductFeatureTypes { get; set; }
        public virtual DbSet<LoanProductRollover> LoanProductRollovers { get; set; }
        public virtual DbSet<LoanProductTila> LoanProductTilas { get; set; }
        public virtual DbSet<LoanService> LoanServices { get; set; }
        public virtual DbSet<LoanStatusChange> LoanStatusChanges { get; set; }
        public virtual DbSet<LoanWebReviewTemplateXref> LoanWebReviewTemplateXrefs { get; set; }
        public virtual DbSet<LocaleSetting> LocaleSettings { get; set; }
        public virtual DbSet<LocaleTranslator> LocaleTranslators { get; set; }
        public virtual DbSet<LocationConverted> LocationConverteds { get; set; }
        public virtual DbSet<LocationUS_ZipcodesXRef> LocationUS_ZipcodesXRef { get; set; }
        public virtual DbSet<MarketingInvitation> MarketingInvitations { get; set; }
        public virtual DbSet<MarketingInvitationHistory> MarketingInvitationHistories { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessageClass> MessageClasses { get; set; }
        public virtual DbSet<MessageClient> MessageClients { get; set; }
        public virtual DbSet<MessageScenario> MessageScenarios { get; set; }
        public virtual DbSet<MetroIIBaseSegment> MetroIIBaseSegments { get; set; }
        public virtual DbSet<MimeType> MimeTypes { get; set; }
        public virtual DbSet<MOStatu> MOStatus { get; set; }
        public virtual DbSet<MOStatusHistory> MOStatusHistories { get; set; }
        public virtual DbSet<MPayAmort> MPayAmorts { get; set; }
        public virtual DbSet<MPayAmortDueDateChange> MPayAmortDueDateChanges { get; set; }
        public virtual DbSet<MPayInterest> MPayInterests { get; set; }
        public virtual DbSet<MPayLoan> MPayLoans { get; set; }
        public virtual DbSet<MPayLoanInSyncAdj> MPayLoanInSyncAdjs { get; set; }
        public virtual DbSet<MPayLoanInSyncAdj_Rows> MPayLoanInSyncAdj_Rows { get; set; }
        public virtual DbSet<MPayPayInFull> MPayPayInFulls { get; set; }
        public virtual DbSet<MPayRecalcInterestAdj> MPayRecalcInterestAdjs { get; set; }
        public virtual DbSet<MPayRecalcLoanPaymentAdj> MPayRecalcLoanPaymentAdjs { get; set; }
        public virtual DbSet<MSA> MSAs { get; set; }
        public virtual DbSet<NetSpendTran> NetSpendTrans { get; set; }
        public virtual DbSet<NobleConfiguration> NobleConfigurations { get; set; }
        public virtual DbSet<NoteType> NoteTypes { get; set; }
        public virtual DbSet<OCRRegion> OCRRegions { get; set; }
        public virtual DbSet<OOWSession> OOWSessions { get; set; }
        public virtual DbSet<OOWSessionAlert> OOWSessionAlerts { get; set; }
        public virtual DbSet<OOWSessionError> OOWSessionErrors { get; set; }
        public virtual DbSet<OOWSessionQuestion> OOWSessionQuestions { get; set; }
        public virtual DbSet<OpenEndInterest> OpenEndInterests { get; set; }
        public virtual DbSet<OpenEndInterestRate> OpenEndInterestRates { get; set; }
        public virtual DbSet<OpenEndLoan> OpenEndLoans { get; set; }
        public virtual DbSet<OpenEndLoanStatement> OpenEndLoanStatements { get; set; }
        public virtual DbSet<OpenEndLoanStatementSnapshot> OpenEndLoanStatementSnapshots { get; set; }
        public virtual DbSet<OpenEndRecalcInterestAdj> OpenEndRecalcInterestAdjs { get; set; }
        public virtual DbSet<OpenEndRecalcLoanPaymentAdj> OpenEndRecalcLoanPaymentAdjs { get; set; }
        public virtual DbSet<OpenEndRecalcStatementAdj> OpenEndRecalcStatementAdjs { get; set; }
        public virtual DbSet<OpenEndRecalcStatementSnapshot> OpenEndRecalcStatementSnapshots { get; set; }
        public virtual DbSet<OptInOut> OptInOuts { get; set; }
        public virtual DbSet<OptInOutEdit> OptInOutEdits { get; set; }
        public virtual DbSet<OptPlusBinProduct> OptPlusBinProducts { get; set; }
        public virtual DbSet<OptPlusBinService> OptPlusBinServices { get; set; }
        public virtual DbSet<OptPlusCardDetail> OptPlusCardDetails { get; set; }
        public virtual DbSet<OptPlusCardRIPayment> OptPlusCardRIPayments { get; set; }
        public virtual DbSet<OptPlusCarrier> OptPlusCarriers { get; set; }
        public virtual DbSet<OptPlusDirectDeposit> OptPlusDirectDeposits { get; set; }
        public virtual DbSet<OptPlusEdit> OptPlusEdits { get; set; }
        public virtual DbSet<OptPlusEmail> OptPlusEmails { get; set; }
        public virtual DbSet<OptPlusEmailLocation> OptPlusEmailLocations { get; set; }
        public virtual DbSet<OptPlusEmployment> OptPlusEmployments { get; set; }
        public virtual DbSet<OptPlusExportInitGL> OptPlusExportInitGLs { get; set; }
        public virtual DbSet<OptPlusGlobal> OptPlusGlobals { get; set; }
        public virtual DbSet<OptPlusMerchant> OptPlusMerchants { get; set; }
        public virtual DbSet<OptPlusProduct> OptPlusProducts { get; set; }
        public virtual DbSet<OptPlusRDFAccountCard> OptPlusRDFAccountCards { get; set; }
        public virtual DbSet<OptPlusRDFAuthorizedTransaction> OptPlusRDFAuthorizedTransactions { get; set; }
        public virtual DbSet<OptPlusRDFCustomerMaster> OptPlusRDFCustomerMasters { get; set; }
        public virtual DbSet<OptPlusRDFLookUp> OptPlusRDFLookUps { get; set; }
        public virtual DbSet<OptPlusRDFODTransition> OptPlusRDFODTransitions { get; set; }
        public virtual DbSet<OptPlusRDFPostedTran> OptPlusRDFPostedTrans { get; set; }
        public virtual DbSet<OverShort> OverShorts { get; set; }
        public virtual DbSet<ParseCash> ParseCashes { get; set; }
        public virtual DbSet<PaydayLoan> PaydayLoans { get; set; }
        public virtual DbSet<PaydayLoanApproval> PaydayLoanApprovals { get; set; }
        public virtual DbSet<PaydayLoanQualification> PaydayLoanQualifications { get; set; }
        public virtual DbSet<PaymentPlan> PaymentPlans { get; set; }
        public virtual DbSet<PAYROLL1> PAYROLL1 { get; set; }
        public virtual DbSet<PayStub> PayStubs { get; set; }
        public virtual DbSet<PersonTitle> PersonTitles { get; set; }
        public virtual DbSet<PhoneSkillsCall> PhoneSkillsCalls { get; set; }
        public virtual DbSet<PhoneSkillsGrade> PhoneSkillsGrades { get; set; }
        public virtual DbSet<PhoneSkillsGrader> PhoneSkillsGraders { get; set; }
        public virtual DbSet<PhoneSkillsReason> PhoneSkillsReasons { get; set; }
        public virtual DbSet<PhoneSkillsSequence> PhoneSkillsSequences { get; set; }
        public virtual DbSet<PrepaidCardBin> PrepaidCardBins { get; set; }
        public virtual DbSet<PrepaidCardBinCompany> PrepaidCardBinCompanies { get; set; }
        public virtual DbSet<PrepaidCardGroup> PrepaidCardGroups { get; set; }
        public virtual DbSet<PrepaidCardStopPayment> PrepaidCardStopPayments { get; set; }
        public virtual DbSet<PrepaidCardStopPaymentEdit> PrepaidCardStopPaymentEdits { get; set; }
        public virtual DbSet<PrepaidCardStopPaymentReason> PrepaidCardStopPaymentReasons { get; set; }
        public virtual DbSet<PrepaidCardTran> PrepaidCardTrans { get; set; }
        public virtual DbSet<PrepaidCardTransAction> PrepaidCardTransActions { get; set; }
        public virtual DbSet<PrepaidFISAccountBalance> PrepaidFISAccountBalances { get; set; }
        public virtual DbSet<PrepaidFISAuthTran> PrepaidFISAuthTrans { get; set; }
        public virtual DbSet<PrepaidFISCustomerMaster> PrepaidFISCustomerMasters { get; set; }
        public virtual DbSet<PrepaidFISPostedTran> PrepaidFISPostedTrans { get; set; }
        public virtual DbSet<PrescreenQuestion> PrescreenQuestions { get; set; }
        public virtual DbSet<PrescreenQuestionState> PrescreenQuestionStates { get; set; }
        public virtual DbSet<PrescreenQuestionType> PrescreenQuestionTypes { get; set; }
        public virtual DbSet<PRICE> PRICES { get; set; }
        public virtual DbSet<ProcessConfig> ProcessConfigs { get; set; }
        public virtual DbSet<ProcessConfigDetail> ProcessConfigDetails { get; set; }
        public virtual DbSet<ProcessConfigDetailHistory> ProcessConfigDetailHistories { get; set; }
        public virtual DbSet<ProcessConfigInstance> ProcessConfigInstances { get; set; }
        public virtual DbSet<ProcessConfigInstanceGroup> ProcessConfigInstanceGroups { get; set; }
        public virtual DbSet<ProcessConfigInstanceTeller> ProcessConfigInstanceTellers { get; set; }
        public virtual DbSet<ProcessSchedule> ProcessSchedules { get; set; }
        public virtual DbSet<ProductOpenLoanMatrix> ProductOpenLoanMatrices { get; set; }
        public virtual DbSet<PromiseToPay> PromiseToPays { get; set; }
        public virtual DbSet<PromiseToPayDetail> PromiseToPayDetails { get; set; }
        public virtual DbSet<PromiseToPayDetailEdit> PromiseToPayDetailEdits { get; set; }
        public virtual DbSet<PromiseToPayDetailTran> PromiseToPayDetailTrans { get; set; }
        public virtual DbSet<PromiseToPayTimeSlotConfig> PromiseToPayTimeSlotConfigs { get; set; }
        public virtual DbSet<PurchaseService> PurchaseServices { get; set; }
        public virtual DbSet<PushNotification> PushNotifications { get; set; }
        public virtual DbSet<RbcEFundBatch> RbcEFundBatches { get; set; }
        public virtual DbSet<RbcEFundBatchDetail> RbcEFundBatchDetails { get; set; }
        public virtual DbSet<RbcEFundBatchSummary> RbcEFundBatchSummaries { get; set; }
        public virtual DbSet<RbcEFundResponseCode> RbcEFundResponseCodes { get; set; }
        public virtual DbSet<RbcEFundSecurity> RbcEFundSecurities { get; set; }
        public virtual DbSet<ReasonForArrear> ReasonForArrears { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<RedactedWord> RedactedWords { get; set; }
        public virtual DbSet<ReferralMethod> ReferralMethods { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<REL> RELS { get; set; }
        public virtual DbSet<RemovedReason> RemovedReasons { get; set; }
        public virtual DbSet<RepoCaseHistory> RepoCaseHistories { get; set; }
        public virtual DbSet<ReturnCheckDetail> ReturnCheckDetails { get; set; }
        public virtual DbSet<ReturnCheckFile> ReturnCheckFiles { get; set; }
        public virtual DbSet<ReturnCheckMatch> ReturnCheckMatches { get; set; }
        public virtual DbSet<RIAgingHistory> RIAgingHistories { get; set; }
        public virtual DbSet<RiBalanceHistory> RiBalanceHistories { get; set; }
        public virtual DbSet<RiccAutoRoll> RiccAutoRolls { get; set; }
        public virtual DbSet<RICCConfig> RICCConfigs { get; set; }
        public virtual DbSet<RiccHold> RiccHolds { get; set; }
        public virtual DbSet<RiccPayment> RiccPayments { get; set; }
        public virtual DbSet<RiccUpdate> RiccUpdates { get; set; }
        public virtual DbSet<RIPTPPaymentPlanConfig> RIPTPPaymentPlanConfigs { get; set; }
        public virtual DbSet<RI> RIS { get; set; }
        public virtual DbSet<RISAUDIT> RISAUDITs { get; set; }
        public virtual DbSet<RISREPT> RISREPTs { get; set; }
        public virtual DbSet<RisTask> RisTasks { get; set; }
        public virtual DbSet<RISTYPE> RISTYPEs { get; set; }
        public virtual DbSet<RiUrgentNote> RiUrgentNotes { get; set; }
        public virtual DbSet<RolloverRequest> RolloverRequests { get; set; }
        public virtual DbSet<RolloverRequestDeclineReason> RolloverRequestDeclineReasons { get; set; }
        public virtual DbSet<RolloverRequestStatu> RolloverRequestStatus { get; set; }
        public virtual DbSet<RuleDef> RuleDefs { get; set; }
        public virtual DbSet<RuleDefEdit> RuleDefEdits { get; set; }
        public virtual DbSet<RuleDefSet> RuleDefSets { get; set; }
        public virtual DbSet<RuleDefSetDetail> RuleDefSetDetails { get; set; }
        public virtual DbSet<RuleDefSetDetailEdit> RuleDefSetDetailEdits { get; set; }
        public virtual DbSet<RuleDefType> RuleDefTypes { get; set; }
        public virtual DbSet<ScannedDocument> ScannedDocuments { get; set; }
        public virtual DbSet<ScannedDocumentOverride> ScannedDocumentOverrides { get; set; }
        public virtual DbSet<SDNAdd> SDNAdds { get; set; }
        public virtual DbSet<SDNAlt> SDNAlts { get; set; }
        public virtual DbSet<SDNList> SDNLists { get; set; }
        public virtual DbSet<SDNMain> SDNMains { get; set; }
        public virtual DbSet<SdnMatch> SdnMatches { get; set; }
        public virtual DbSet<SecurityAnswer> SecurityAnswers { get; set; }
        public virtual DbSet<SecurityGroup> SecurityGroups { get; set; }
        public virtual DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual DbSet<ServiceDetail> ServiceDetails { get; set; }
        public virtual DbSet<ServiceMaster> ServiceMasters { get; set; }
        public virtual DbSet<ServiceSubItem> ServiceSubItems { get; set; }
        public virtual DbSet<ServiceTran> ServiceTrans { get; set; }
        public virtual DbSet<ServiceTransDetail> ServiceTransDetails { get; set; }
        public virtual DbSet<SG_RIGHTS> SG_RIGHTS { get; set; }
        public virtual DbSet<SignatureLoanApproval> SignatureLoanApprovals { get; set; }
        public virtual DbSet<SkipTraceConfig> SkipTraceConfigs { get; set; }
        public virtual DbSet<SkipTraceEvents_NotUsed> SkipTraceEvents_NotUsed { get; set; }
        public virtual DbSet<SkipTraceStep> SkipTraceSteps { get; set; }
        public virtual DbSet<SkipTraceStep_AuditCategory> SkipTraceStep_AuditCategory { get; set; }
        public virtual DbSet<SkipTraceStep_Location> SkipTraceStep_Location { get; set; }
        public virtual DbSet<SkipTraceStep_ProductCode> SkipTraceStep_ProductCode { get; set; }
        public virtual DbSet<SkipTraceThread> SkipTraceThreads { get; set; }
        public virtual DbSet<SkipTraceVendor> SkipTraceVendors { get; set; }
        public virtual DbSet<SMSCommandMapping> SMSCommandMappings { get; set; }
        public virtual DbSet<SMSFailedSend> SMSFailedSends { get; set; }
        public virtual DbSet<SMSInbound> SMSInbounds { get; set; }
        public virtual DbSet<SMSOutbound> SMSOutbounds { get; set; }
        public virtual DbSet<SMSOxygenErrorCode> SMSOxygenErrorCodes { get; set; }
        public virtual DbSet<SMSResponse> SMSResponses { get; set; }
        public virtual DbSet<SMSSender> SMSSenders { get; set; }
        public virtual DbSet<SMSTemplate> SMSTemplates { get; set; }
        public virtual DbSet<SPayInterest> SPayInterests { get; set; }
        public virtual DbSet<SPayLoan> SPayLoans { get; set; }
        public virtual DbSet<SPayLoanInSyncAdj> SPayLoanInSyncAdjs { get; set; }
        public virtual DbSet<SPaySchedRollover> SPaySchedRollovers { get; set; }
        public virtual DbSet<SPaySchedRolloverDetail> SPaySchedRolloverDetails { get; set; }
        public virtual DbSet<SpecialMessage> SpecialMessages { get; set; }
        public virtual DbSet<SpecialMessage_AzCusts> SpecialMessage_AzCusts { get; set; }
        public virtual DbSet<SpecialMessageLoanProduct> SpecialMessageLoanProducts { get; set; }
        public virtual DbSet<SpecialMessageLocation> SpecialMessageLocations { get; set; }
        public virtual DbSet<Store_Windows> Store_Windows { get; set; }
        public virtual DbSet<StoreClosed> StoreCloseds { get; set; }
        public virtual DbSet<StoreClosedDetail> StoreClosedDetails { get; set; }
        public virtual DbSet<TaskActionResult> TaskActionResults { get; set; }
        public virtual DbSet<TaskActionResultXref> TaskActionResultXrefs { get; set; }
        public virtual DbSet<TellerComputer> TellerComputers { get; set; }
        public virtual DbSet<TELLERID> TELLERIDs { get; set; }
        public virtual DbSet<TellerIDEdit> TellerIDEdits { get; set; }
        public virtual DbSet<TellerLogin> TellerLogins { get; set; }
        public virtual DbSet<TellerParsedCashException> TellerParsedCashExceptions { get; set; }
        public virtual DbSet<TellerPwdHistory> TellerPwdHistories { get; set; }
        public virtual DbSet<TellerSecurity> TellerSecurities { get; set; }
        public virtual DbSet<TellerTitle> TellerTitles { get; set; }
        public virtual DbSet<TellerTitleEdit> TellerTitleEdits { get; set; }
        public virtual DbSet<TellerType> TellerTypes { get; set; }
        public virtual DbSet<TempLoanProductSplit> TempLoanProductSplits { get; set; }
        public virtual DbSet<TestCreditCard> TestCreditCards { get; set; }
        public virtual DbSet<TitleLoan> TitleLoans { get; set; }
        public virtual DbSet<TitleLoanApproval> TitleLoanApprovals { get; set; }
        public virtual DbSet<TotalDailyFee> TotalDailyFees { get; set; }
        public virtual DbSet<TransDetail> TransDetails { get; set; }
        public virtual DbSet<TransDetailAcct> TransDetailAccts { get; set; }
        public virtual DbSet<TransDetailCash> TransDetailCashes { get; set; }
        public virtual DbSet<TransDetailCashParsedCash> TransDetailCashParsedCashes { get; set; }
        public virtual DbSet<TransDetailCheck> TransDetailChecks { get; set; }
        public virtual DbSet<TransDetailIntShort> TransDetailIntShorts { get; set; }
        public virtual DbSet<TransDetailLoan> TransDetailLoans { get; set; }
        public virtual DbSet<TransDetailService> TransDetailServices { get; set; }
        public virtual DbSet<TransferFund> TransferFunds { get; set; }
        public virtual DbSet<TransPOS> TransPOS { get; set; }
        public virtual DbSet<TransUnionCode> TransUnionCodes { get; set; }
        public virtual DbSet<UDDReport> UDDReports { get; set; }
        public virtual DbSet<UDDReportDetail> UDDReportDetails { get; set; }
        public virtual DbSet<US_States> US_States { get; set; }
        public virtual DbSet<US_Zipcodes> US_Zipcodes { get; set; }
        public virtual DbSet<UtilRecalcLog> UtilRecalcLogs { get; set; }
        public virtual DbSet<UtilRecalcLogDetail> UtilRecalcLogDetails { get; set; }
        public virtual DbSet<VaultCount> VaultCounts { get; set; }
        public virtual DbSet<VaultCountCalcParsedCash> VaultCountCalcParsedCashes { get; set; }
        public virtual DbSet<VaultCountEnteredParsedCash> VaultCountEnteredParsedCashes { get; set; }
        public virtual DbSet<VaultCountService> VaultCountServices { get; set; }
        public virtual DbSet<VaultMaster> VaultMasters { get; set; }
        public virtual DbSet<VaultMasterParsedCash> VaultMasterParsedCashes { get; set; }
        public virtual DbSet<VaultMgrAssignment> VaultMgrAssignments { get; set; }
        public virtual DbSet<VaultMgrAuthorization> VaultMgrAuthorizations { get; set; }
        public virtual DbSet<VaultMgrAuthorizationDetail> VaultMgrAuthorizationDetails { get; set; }
        public virtual DbSet<VaultMgrAuthorizationNote> VaultMgrAuthorizationNotes { get; set; }
        public virtual DbSet<VaultRecalcAdj> VaultRecalcAdjs { get; set; }
        public virtual DbSet<VaultService> VaultServices { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleHistory> VehicleHistories { get; set; }
        public virtual DbSet<VehicleQuote> VehicleQuotes { get; set; }
        public virtual DbSet<VeritecLoanID> VeritecLoanIDs { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<VisitorApiAuthorization> VisitorApiAuthorizations { get; set; }
        public virtual DbSet<VisitorDevice> VisitorDevices { get; set; }
        public virtual DbSet<VisitorEdit> VisitorEdits { get; set; }
        public virtual DbSet<VisitorEmail> VisitorEmails { get; set; }
        public virtual DbSet<VisitorEmailDisposition> VisitorEmailDispositions { get; set; }
        public virtual DbSet<VisitorEmailExcludedSender> VisitorEmailExcludedSenders { get; set; }
        public virtual DbSet<VisitorHistory> VisitorHistories { get; set; }
        public virtual DbSet<VisitorSecurityQuestion> VisitorSecurityQuestions { get; set; }
        public virtual DbSet<VMATransType> VMATransTypes { get; set; }
        public virtual DbSet<WebArchive> WebArchives { get; set; }
        public virtual DbSet<WebBlob> WebBlobs { get; set; }
        public virtual DbSet<WebBlobLoanApplicationXref> WebBlobLoanApplicationXrefs { get; set; }
        public virtual DbSet<WebBlobLoanXref> WebBlobLoanXrefs { get; set; }
        public virtual DbSet<WebBlobType> WebBlobTypes { get; set; }
        public virtual DbSet<WebBlobVisitorEmailXref> WebBlobVisitorEmailXrefs { get; set; }
        public virtual DbSet<WebCallApplicationModeAudit> WebCallApplicationModeAudits { get; set; }
        public virtual DbSet<WebCallApplicationMode> WebCallApplicationModes { get; set; }
        public virtual DbSet<WebCallApplicationStatusHistory> WebCallApplicationStatusHistories { get; set; }
        public virtual DbSet<WebCallAuthorizedVisitorContact> WebCallAuthorizedVisitorContacts { get; set; }
        public virtual DbSet<WebCallBatchAction> WebCallBatchActions { get; set; }
        public virtual DbSet<WebCallBatchCriteria> WebCallBatchCriterias { get; set; }
        public virtual DbSet<WebCallBatchTask> WebCallBatchTasks { get; set; }
        public virtual DbSet<WebCallBatchTaskExecutionHistory> WebCallBatchTaskExecutionHistories { get; set; }
        public virtual DbSet<WebCallCampaign> WebCallCampaigns { get; set; }
        public virtual DbSet<WebCallCampaignCategory> WebCallCampaignCategories { get; set; }
        public virtual DbSet<WebCallCategory> WebCallCategories { get; set; }
        public virtual DbSet<WebCallCatRarrAlia> WebCallCatRarrAlias { get; set; }
        public virtual DbSet<WebCallCCTimerLog> WebCallCCTimerLogs { get; set; }
        public virtual DbSet<WebCallCenterLogin> WebCallCenterLogins { get; set; }
        public virtual DbSet<WebCallChatCannedRespons> WebCallChatCannedResponses { get; set; }
        public virtual DbSet<WebCallChatMessage> WebCallChatMessages { get; set; }
        public virtual DbSet<WebCallChatSession> WebCallChatSessions { get; set; }
        public virtual DbSet<WebCallChatStatu> WebCallChatStatus { get; set; }
        public virtual DbSet<WebCallChatTopic> WebCallChatTopics { get; set; }
        public virtual DbSet<WebCallChatUser> WebCallChatUsers { get; set; }
        public virtual DbSet<WebCallCSRReportColumn> WebCallCSRReportColumns { get; set; }
        public virtual DbSet<WebCallCSRReportColumnRARR> WebCallCSRReportColumnRARRs { get; set; }
        public virtual DbSet<WebCallDualAuth> WebCallDualAuths { get; set; }
        public virtual DbSet<WebCallEmailTemplate> WebCallEmailTemplates { get; set; }
        public virtual DbSet<WebCallFAQ> WebCallFAQs { get; set; }
        public virtual DbSet<WebCallFAQAttachment> WebCallFAQAttachments { get; set; }
        public virtual DbSet<WebCallFAQCategory> WebCallFAQCategories { get; set; }
        public virtual DbSet<WebCallFeature> WebCallFeatures { get; set; }
        public virtual DbSet<WebCallIntraChatMessage> WebCallIntraChatMessages { get; set; }
        public virtual DbSet<WebCallIntraChatSession> WebCallIntraChatSessions { get; set; }
        public virtual DbSet<WebCallInvalidPhoneNumber> WebCallInvalidPhoneNumbers { get; set; }
        public virtual DbSet<WebCallLoanAppSourceApp> WebCallLoanAppSourceApps { get; set; }
        public virtual DbSet<WebCallLoanProductConfig> WebCallLoanProductConfigs { get; set; }
        public virtual DbSet<WebCallLoggingCategory> WebCallLoggingCategories { get; set; }
        public virtual DbSet<WebCallLoggingCategoryLog> WebCallLoggingCategoryLogs { get; set; }
        public virtual DbSet<WebCallLoggingLog> WebCallLoggingLogs { get; set; }
        public virtual DbSet<WebCallOnlineStatusDisplayLookup> WebCallOnlineStatusDisplayLookups { get; set; }
        public virtual DbSet<WebCallQueue> WebCallQueues { get; set; }
        public virtual DbSet<WebCallQueueAudit> WebCallQueueAudits { get; set; }
        public virtual DbSet<WebCallQueueConfiguration> WebCallQueueConfigurations { get; set; }
        public virtual DbSet<WebCallQueueLoanAppAudit> WebCallQueueLoanAppAudits { get; set; }
        public virtual DbSet<WebCallQueueStatu> WebCallQueueStatus { get; set; }
        public virtual DbSet<WebCallQueueType> WebCallQueueTypes { get; set; }
        public virtual DbSet<WebCallQuickNote> WebCallQuickNotes { get; set; }
        public virtual DbSet<WebCallRARR> WebCallRARRs { get; set; }
        public virtual DbSet<WebCallRARRAction> WebCallRARRActions { get; set; }
        public virtual DbSet<WebCallRARRCategoryReason> WebCallRARRCategoryReasons { get; set; }
        public virtual DbSet<WebCallRARReason> WebCallRARReasons { get; set; }
        public virtual DbSet<WebCallRARResult1> WebCallRARResult1 { get; set; }
        public virtual DbSet<WebCallRARResult2> WebCallRARResult2 { get; set; }
        public virtual DbSet<WebCallRARRFeature> WebCallRARRFeatures { get; set; }
        public virtual DbSet<WebCallRarrGroup> WebCallRarrGroups { get; set; }
        public virtual DbSet<WebCallRARRHistory> WebCallRARRHistories { get; set; }
        public virtual DbSet<WebCallRecordingArchive> WebCallRecordingArchives { get; set; }
        public virtual DbSet<WebCallTeam> WebCallTeams { get; set; }
        public virtual DbSet<WebCallTeamUser> WebCallTeamUsers { get; set; }
        public virtual DbSet<WebCallUserSetting> WebCallUserSettings { get; set; }
        public virtual DbSet<WebCallVisitorAlert> WebCallVisitorAlerts { get; set; }
        public virtual DbSet<WebCallVisitorAlertsAudit> WebCallVisitorAlertsAudits { get; set; }
        public virtual DbSet<WebCallWebEmergencyAlertTemplate> WebCallWebEmergencyAlertTemplates { get; set; }
        public virtual DbSet<WebCallWorkItemCategoryHistory> WebCallWorkItemCategoryHistories { get; set; }
        public virtual DbSet<WebCallWorkQueue> WebCallWorkQueues { get; set; }
        public virtual DbSet<WebDailyReport> WebDailyReports { get; set; }
        public virtual DbSet<WebDailyReportField> WebDailyReportFields { get; set; }
        public virtual DbSet<WebDailyReportState> WebDailyReportStates { get; set; }
        public virtual DbSet<WebDialerCallResult> WebDialerCallResults { get; set; }
        public virtual DbSet<WebDialerPhoneLine> WebDialerPhoneLines { get; set; }
        public virtual DbSet<WebDialerResult> WebDialerResults { get; set; }
        public virtual DbSet<WebDialerResultType> WebDialerResultTypes { get; set; }
        public virtual DbSet<WebDialerStatu> WebDialerStatus { get; set; }
        public virtual DbSet<WebDialerUploadHistory> WebDialerUploadHistories { get; set; }
        public virtual DbSet<WebDialerUser> WebDialerUsers { get; set; }
        public virtual DbSet<WebEmailNote> WebEmailNotes { get; set; }
        public virtual DbSet<WebErrorLog> WebErrorLogs { get; set; }
        public virtual DbSet<WebImage> WebImages { get; set; }
        public virtual DbSet<WebLead> WebLeads { get; set; }
        public virtual DbSet<WebLeadBuyer> WebLeadBuyers { get; set; }
        public virtual DbSet<WebLeadGen> WebLeadGens { get; set; }
        public virtual DbSet<WebLeadGenAddress> WebLeadGenAddresses { get; set; }
        public virtual DbSet<WebLeadGenField> WebLeadGenFields { get; set; }
        public virtual DbSet<WebLeadGenStatistic> WebLeadGenStatistics { get; set; }
        public virtual DbSet<WebLeadGenTier> WebLeadGenTiers { get; set; }
        public virtual DbSet<WebLeadGenTranslation> WebLeadGenTranslations { get; set; }
        public virtual DbSet<WebLeadPostData> WebLeadPostDatas { get; set; }
        public virtual DbSet<WebLeadSale> WebLeadSales { get; set; }
        public virtual DbSet<WebLoanCreditFraud> WebLoanCreditFrauds { get; set; }
        public virtual DbSet<WebPixelVendor> WebPixelVendors { get; set; }
        public virtual DbSet<WebPixelVendorData> WebPixelVendorDatas { get; set; }
        public virtual DbSet<WebPixelVendorDetail> WebPixelVendorDetails { get; set; }
        public virtual DbSet<WebReferralMethod> WebReferralMethods { get; set; }
        public virtual DbSet<WebRemoteControl> WebRemoteControls { get; set; }
        public virtual DbSet<WebReportByApp> WebReportByApps { get; set; }
        public virtual DbSet<WebReportByLoan> WebReportByLoans { get; set; }
        public virtual DbSet<WebReviewTemplate> WebReviewTemplates { get; set; }
        public virtual DbSet<WebSiteEvent> WebSiteEvents { get; set; }
        public virtual DbSet<WebVisit> WebVisits { get; set; }
        public virtual DbSet<WebVisitSource> WebVisitSources { get; set; }
        public virtual DbSet<WebVisitSrcXref> WebVisitSrcXrefs { get; set; }
        public virtual DbSet<WireTransferFileImport> WireTransferFileImports { get; set; }
        public virtual DbSet<WireTransferMatch> WireTransferMatches { get; set; }
        public virtual DbSet<WireTransferMatchEdit> WireTransferMatchEdits { get; set; }
        public virtual DbSet<WSConfig> WSConfigs { get; set; }
        public virtual DbSet<WSOperation> WSOperations { get; set; }
        public virtual DbSet<WSResponse> WSResponses { get; set; }
        public virtual DbSet<ZeroDollarAuth> ZeroDollarAuths { get; set; }
        public virtual DbSet<ZipArea> ZipAreas { get; set; }
        public virtual DbSet<C_ErrorLogTest> C_ErrorLogTest { get; set; }
        public virtual DbSet<AACbExportDataArchive> AACbExportDataArchives { get; set; }
        public virtual DbSet<ACHGroup> ACHGroups { get; set; }
        public virtual DbSet<AUDDISAdviceReportDetail> AUDDISAdviceReportDetails { get; set; }
        public virtual DbSet<CreditCardResultCodeEdit> CreditCardResultCodeEdits { get; set; }
        public virtual DbSet<CustomerFlashMPayRebate> CustomerFlashMPayRebates { get; set; }
        public virtual DbSet<CustomerIncomeBackup> CustomerIncomeBackups { get; set; }
        public virtual DbSet<EmploymentRegion> EmploymentRegions { get; set; }
        public virtual DbSet<EmploymentRequest> EmploymentRequests { get; set; }
        public virtual DbSet<InternalProcessEmailBody> InternalProcessEmailBodies { get; set; }
        public virtual DbSet<InternalProcessEmailType> InternalProcessEmailTypes { get; set; }
        public virtual DbSet<KBB_Log_Config> KBB_Log_Config { get; set; }
        public virtual DbSet<LoanApplicationBU> LoanApplicationBUs { get; set; }
        public virtual DbSet<LoanApplicationDiscount> LoanApplicationDiscounts { get; set; }
        public virtual DbSet<LoanProductEnableNewLoanBackup> LoanProductEnableNewLoanBackups { get; set; }
        public virtual DbSet<MPayIntDupNeg> MPayIntDupNegs { get; set; }
        public virtual DbSet<MPayIntDupPos> MPayIntDupPos { get; set; }
        public virtual DbSet<OEndLoanInSyncAdj> OEndLoanInSyncAdjs { get; set; }
        public virtual DbSet<OEndVaultTroubleshooting> OEndVaultTroubleshootings { get; set; }
        public virtual DbSet<OptPlusExportTransCode> OptPlusExportTransCodes { get; set; }
        public virtual DbSet<RitaPwd> RitaPwds { get; set; }
        public virtual DbSet<SkipTraceConfig_RisAudit> SkipTraceConfig_RisAudit { get; set; }
        public virtual DbSet<SkipTraceThreadBackUp> SkipTraceThreadBackUps { get; set; }
        public virtual DbSet<TransferFundsInterStore> TransferFundsInterStores { get; set; }
        public virtual DbSet<WebAlert> WebAlerts { get; set; }
        public virtual DbSet<WebCallRARRType> WebCallRARRTypes { get; set; }
        public virtual DbSet<Docuware_View> Docuware_View { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Svc_Tran> Svc_Tran { get; set; }
        public virtual DbSet<syscolumns_view> syscolumns_view { get; set; }
        public virtual DbSet<sysobjects_view> sysobjects_view { get; set; }
        public virtual DbSet<systypes_view> systypes_view { get; set; }
        public virtual DbSet<vw_Ach_Trecs> vw_Ach_Trecs { get; set; }
        public virtual DbSet<vw_AppSetting> vw_AppSetting { get; set; }
        public virtual DbSet<vw_CashedCheckRate> vw_CashedCheckRate { get; set; }
        public virtual DbSet<vw_CashedCheckRateTable> vw_CashedCheckRateTable { get; set; }
        public virtual DbSet<vw_CustomerEmployerIncome> vw_CustomerEmployerIncome { get; set; }
        public virtual DbSet<vw_DocuwareInfoByCustomerDocumentKey> vw_DocuwareInfoByCustomerDocumentKey { get; set; }
        public virtual DbSet<vw_DocuwareInfoByTransDetailKey> vw_DocuwareInfoByTransDetailKey { get; set; }
        public virtual DbSet<vw_Eos310> vw_Eos310 { get; set; }
        public virtual DbSet<vw_EosMoneyGrams> vw_EosMoneyGrams { get; set; }
        public virtual DbSet<vw_EosMoneyOrder> vw_EosMoneyOrder { get; set; }
        public virtual DbSet<vw_LoanApplication> vw_LoanApplication { get; set; }
        public virtual DbSet<vw_LoanApplicationEmployerIncome> vw_LoanApplicationEmployerIncome { get; set; }
        public virtual DbSet<vw_LoansByStatus> vw_LoansByStatus { get; set; }
        public virtual DbSet<vw_Notes_AchHistory> vw_Notes_AchHistory { get; set; }
        public virtual DbSet<vw_Notes_CheckAgain> vw_Notes_CheckAgain { get; set; }
        public virtual DbSet<vw_Notes_CheckPayment> vw_Notes_CheckPayment { get; set; }
        public virtual DbSet<vw_Notes_CollectionMovement> vw_Notes_CollectionMovement { get; set; }
        public virtual DbSet<vw_Notes_Contacts> vw_Notes_Contacts { get; set; }
        public virtual DbSet<vw_Notes_CustomerEdit> vw_Notes_CustomerEdit { get; set; }
        public virtual DbSet<vw_Notes_IssuerEdit> vw_Notes_IssuerEdit { get; set; }
        public virtual DbSet<vw_Notes_Letters> vw_Notes_Letters { get; set; }
        public virtual DbSet<vw_Notes_LoanPayment> vw_Notes_LoanPayment { get; set; }
        public virtual DbSet<vw_Notes_ManualCcAttempt> vw_Notes_ManualCcAttempt { get; set; }
        public virtual DbSet<vw_Notes_NoteHistory> vw_Notes_NoteHistory { get; set; }
        public virtual DbSet<vw_Notes_RICC> vw_Notes_RICC { get; set; }
        public virtual DbSet<vw_QuickAndDirtyChkRates> vw_QuickAndDirtyChkRates { get; set; }
        public virtual DbSet<vw_SharePoint_StoresList> vw_SharePoint_StoresList { get; set; }
        public virtual DbSet<vw_TaskActionResult> vw_TaskActionResult { get; set; }
        public virtual DbSet<Xah> Xahs { get; set; }
        public virtual DbSet<Xca> Xcas { get; set; }
        public virtual DbSet<Xccp> Xccps { get; set; }
        public virtual DbSet<Xcct> Xccts { get; set; }
        public virtual DbSet<Xcm> Xcms { get; set; }
        public virtual DbSet<Xfl> Xfls { get; set; }
        public virtual DbSet<Xflb> Xflbs { get; set; }
        public virtual DbSet<Xflp> Xflps { get; set; }
        public virtual DbSet<Xflr> Xflrs { get; set; }
        public virtual DbSet<Xl> Xls { get; set; }
        public virtual DbSet<Xlddc> Xlddcs { get; set; }
        public virtual DbSet<Xlp> Xlps { get; set; }
        public virtual DbSet<Xlpc> Xlpcs { get; set; }
        public virtual DbSet<Xlpenl> Xlpenls { get; set; }
        public virtual DbSet<Xlpmp> Xlpmps { get; set; }
        public virtual DbSet<Xlpoe> Xlpoes { get; set; }
        public virtual DbSet<Xlpsp> Xlpsps { get; set; }
        public virtual DbSet<Xmpi> Xmpis { get; set; }
        public virtual DbSet<Xmpl> Xmpls { get; set; }
        public virtual DbSet<Xmplisa> Xmplisas { get; set; }
        public virtual DbSet<Xoei> Xoeis { get; set; }
        public virtual DbSet<Xoel> Xoels { get; set; }
        public virtual DbSet<Xrr> Xrrs { get; set; }
        public virtual DbSet<Xsd> Xsds { get; set; }
        public virtual DbSet<Xsm> Xsms { get; set; }
        public virtual DbSet<Xsplisa> Xsplisas { get; set; }
        public virtual DbSet<Xssrd> Xssrds { get; set; }
        public virtual DbSet<Xst> Xsts { get; set; }
        public virtual DbSet<Xtd> Xtds { get; set; }
        public virtual DbSet<Xtda> Xtdas { get; set; }
        public virtual DbSet<Xtdcash> Xtdcashes { get; set; }
        public virtual DbSet<Xtdcheck> Xtdchecks { get; set; }
        public virtual DbSet<Xtdloan> Xtdloans { get; set; }
        public virtual DbSet<Xti> Xtis { get; set; }
        public virtual DbSet<Xtp> Xtps { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
        }
    }
}
