using System;
using System.Collections.Generic;

namespace EFCoreData
{
    public partial class Global
    {
        public int GlobalKey { get; set; }
        public double MaxSvc { get; set; }
        public double MaxChk { get; set; }
        public string VaultMgrSgValues { get; set; }
        public DateTime? LastRelease { get; set; }
        public DateTime LastDialerImport { get; set; }
        public short? TmpBsFlag { get; set; }
        public int? LastTdKeyIntShort { get; set; }
        public DateTime? DocTrackStartDate { get; set; }
        public DateTime? DocStatusStartDate { get; set; }
        public string OeStatementEmail { get; set; }
        public decimal MaxDrawerCloseAmt { get; set; }
        public byte DaysChecksNotRereturnable { get; set; }
        public string AppName { get; set; }
        public DateTime? SdnListLastUpdate { get; set; }
        public decimal IncomeGrossUpperLimit { get; set; }
        public decimal IncomeGrossLowerLimit { get; set; }
        public decimal IncomeNetUpperLimit { get; set; }
        public decimal IncomeNetLowerLimit { get; set; }
        public string SprocName1 { get; set; }
        public string SprocName2 { get; set; }
        public string SprocName3 { get; set; }
        public string SprocLiveConn1 { get; set; }
        public string SprocLiveConn2 { get; set; }
        public string SprocLiveConn3 { get; set; }
        public string SprocTestConn1 { get; set; }
        public string SprocTestConn2 { get; set; }
        public string SprocTestConn3 { get; set; }
        public string LoanDocSyncPath1 { get; set; }
        public string LoanDocSyncPath2 { get; set; }
        public string LoanDocSyncPath3 { get; set; }
        public string LoanDocSyncPath4 { get; set; }
        public bool LoanDocSyncIncRev1 { get; set; }
        public bool LoanDocSyncIncRev2 { get; set; }
        public bool LoanDocSyncIncRev3 { get; set; }
        public bool LoanDocSyncIncRev4 { get; set; }
        public bool LoanDocSyncIgnoreExt1 { get; set; }
        public bool LoanDocSyncIgnoreExt2 { get; set; }
        public bool LoanDocSyncIgnoreExt3 { get; set; }
        public bool LoanDocSyncIgnoreExt4 { get; set; }
        public byte? CheckagainDefaultedDays { get; set; }
        public short NetspendPortNum { get; set; }
        public string NetspendServerIp { get; set; }
        public string NetspendUserId { get; set; }
        public string NetspendPassword { get; set; }
        public byte AdAstraCommissionPct { get; set; }
        public string KarpowerPassword { get; set; }
        public string KbbUsername { get; set; }
        public string KbbPassword { get; set; }
        public bool ConversionSqlUpdated { get; set; }
        public string ConversionSqlFilename { get; set; }
        public string AdAstraNpaEppKey { get; set; }
        public int KbbMileageThreshold { get; set; }
        public DateTime? WebEodStart { get; set; }
        public decimal? AppVersion { get; set; }
        public decimal GoldPricePerGram { get; set; }
        public DateTime GoldLastUpdate { get; set; }
        public decimal LessTargetVariance { get; set; }
        public decimal GreaterTargetVariance { get; set; }
        public bool PrintCustomerRegistration { get; set; }
        public short LastUsedTelpaySequenceNbr { get; set; }
        public string FieldSolutionsPassword { get; set; }
        public DateTime NextRiccMastercardDate { get; set; }
        public DateTime? RestoreDate { get; set; }
        public short MinNbrBlockedAddressFieldsToMatch { get; set; }
        public short MaxCcAttemptsPerDay { get; set; }
        public short MaxCcAttemptsPerMonth { get; set; }
        public short MaxCcAttemptsWithinXdays { get; set; }
        public short MaxCcDaysForAttemptsWithinXdays { get; set; }
        public bool RestartMaxCcAttempsAfterPaid { get; set; }
        public int? MaxAvsValidationDeclines { get; set; }
        public int? AvsValidationCoolOffHours { get; set; }
        public bool IncludePreAuthInMaxAttemptsCnt { get; set; }
        public short AccountVerificationValidForXDays { get; set; }
        public bool UseRecurringInMaxAttemptsCnt { get; set; }
        public short CapsCcMaxattemptSpay { get; set; }
        public short CapsCcMaxattemptMpay { get; set; }
        public short CapsCcMaxattemptOend { get; set; }
        public string DataProtectionRegistrationNum { get; set; }
        public string InterimPermissionNum { get; set; }
        public string CompanyNum { get; set; }
        public bool EnableDeclineCoolingOff { get; set; }
        public int DeclineCoolingOffMin { get; set; }
        public string ChiefExecutiveOfficer { get; set; }
        public bool EnableAmlReporting { get; set; }
        public bool BreakingOutOfCollectionsAndFeeAttemptsEnabled { get; set; }
        public int MaxDaysForAchRepresentment { get; set; }
        public int MinAchPaymentAmountPct { get; set; }
        public int MaxAchPaymentAmountPct { get; set; }
        public bool CustomerFeedbackEnabled { get; set; }
    }
}
