using System;
using System.Collections.Generic;

namespace EFCoreData
{
    public partial class MpayLoanInSyncAdj
    {
        public int MpayLoanInSyncAdjKey { get; set; }
        public DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public int LoanKey { get; set; }
        public string LoanStatus { get; set; }
        public decimal LoanBalance { get; set; }
        public decimal RiBalance { get; set; }
        public decimal PrincAmt { get; set; }
        public decimal CashAmt { get; set; }
        public decimal TransFeeAmt { get; set; }
        public bool ChargeTransFee { get; set; }
        public decimal LienFeeAmt { get; set; }
        public bool ChargeLienFee { get; set; }
        public DateTime? OrigDueDate { get; set; }
        public DateTime? AdjustedDueDate { get; set; }
        public bool Defaulted { get; set; }
        public DateTime? DefaultDate { get; set; }
        public decimal LastPaymentAmt { get; set; }
        public DateTime? LastPaymentDate { get; set; }
        public DateTime? NextDueDate { get; set; }
        public decimal NextDueAmt { get; set; }
        public DateTime? PendingSchedAchSent { get; set; }
        public decimal PendingSchedAchAmt { get; set; }
        public string CLoanStatus { get; set; }
        public decimal CLoanBalance { get; set; }
        public decimal CRiBalance { get; set; }
        public decimal CPrincAmt { get; set; }
        public decimal CCashAmt { get; set; }
        public decimal CTransFeeAmt { get; set; }
        public bool CChargeTransFee { get; set; }
        public decimal CLienFeeAmt { get; set; }
        public bool CChargeLienFee { get; set; }
        public DateTime? COrigDueDate { get; set; }
        public DateTime? CAdjustedDueDate { get; set; }
        public bool CDefaulted { get; set; }
        public DateTime? CDefaultDate { get; set; }
        public decimal CLastPaymentAmt { get; set; }
        public DateTime? CLastPaymentDate { get; set; }
        public DateTime? CNextDueDate { get; set; }
        public decimal CNextDueAmt { get; set; }
        public DateTime? CPendingSchedAchSent { get; set; }
        public decimal CPendingSchedAchAmt { get; set; }
        public int CAdjCntInt { get; set; }
        public int CAdjCntPendingAchInt { get; set; }
        public int CAdjCntLpMpayRecord { get; set; }
        public decimal? TransFeeColoradoPostponeAmt { get; set; }
        public decimal? CTransFeeColoradoPostponeAmt { get; set; }
        public decimal CollFeePastDueBal { get; set; }
        public decimal LegalFeePastDueBal { get; set; }
        public decimal LoanFeeDueBal { get; set; }
        public decimal TransFeeDueBal { get; set; }
        public decimal InterestDueBal { get; set; }
        public decimal PrincDueBal { get; set; }
        public decimal CCollFeePastDueBal { get; set; }
        public decimal CLegalFeePastDueBal { get; set; }
        public decimal CLoanFeeDueBal { get; set; }
        public decimal CTransFeeDueBal { get; set; }
        public decimal CInterestDueBal { get; set; }
        public decimal CPrincDueBal { get; set; }
        public decimal PaymentDueBal { get; set; }
        public decimal PaymentPastDueBal { get; set; }
        public decimal CPaymentDueBal { get; set; }
        public decimal CPaymentPastDueBal { get; set; }
        public decimal? InventoryAmt { get; set; }
        public decimal? CInventoryAmt { get; set; }
        public decimal CabInterestDueBal { get; set; }
        public decimal CabCollFeePastDueBal { get; set; }
        public decimal CCabInterestDueBal { get; set; }
        public decimal CCabCollFeePastDueBal { get; set; }
        public decimal LoanAmt { get; set; }
        public decimal CLoanAmt { get; set; }
        public decimal NsfFeePastDueBal { get; set; }
        public decimal CNsfFeePastDueBal { get; set; }
        public decimal? RebateAmt { get; set; }
        public decimal? CRebateAmt { get; set; }
        public decimal? DiscAmt { get; set; }
        public decimal? CDiscAmt { get; set; }
        public bool? IsInLegalStatus { get; set; }
        public int CyclesPastDue { get; set; }
        public int CCyclesPastDue { get; set; }
        public decimal PendingPmtAmt { get; set; }
        public decimal CPendingPmtAmt { get; set; }
        public DateTime? PendingPmtDate { get; set; }
        public DateTime? CPendingPmtDate { get; set; }
        public decimal PendingPmtPrinc { get; set; }
        public decimal CPendingPmtPrinc { get; set; }
        public decimal PendingPmtInterestCap { get; set; }
        public decimal CPendingPmtInterestCap { get; set; }
        public decimal PendingPmtCabInterestCap { get; set; }
        public decimal CPendingPmtCabInterestCap { get; set; }
        public decimal InsuranceDueBal { get; set; }
        public decimal CInsuranceDueBal { get; set; }
        public decimal DueDatePaymentQueueBal { get; set; }
        public decimal CDueDatePaymentQueueBal { get; set; }
        public decimal InventoryBal { get; set; }
        public decimal CInventoryBal { get; set; }
    }
}
