using System;
using System.Collections.Generic;

namespace EFCoreData
{
    public partial class Prices
    {
        public decimal Pfee1 { get; set; }
        public decimal Ptfee1 { get; set; }
        public bool? Ptable1 { get; set; }
        public decimal Pfee2 { get; set; }
        public decimal Ptfee2 { get; set; }
        public bool? Ptable2 { get; set; }
        public decimal Pfee3 { get; set; }
        public decimal Ptfee3 { get; set; }
        public bool? Ptable3 { get; set; }
        public decimal Pfee4 { get; set; }
        public decimal Ptfee4 { get; set; }
        public bool? Ptable4 { get; set; }
        public decimal Pfee5 { get; set; }
        public decimal Ptfee5 { get; set; }
        public bool? Ptable5 { get; set; }
        public decimal Pfee6 { get; set; }
        public decimal Ptfee6 { get; set; }
        public bool? Ptable6 { get; set; }
        public decimal Pfee7 { get; set; }
        public decimal Ptfee7 { get; set; }
        public bool? Ptable7 { get; set; }
        public decimal Pfee8 { get; set; }
        public decimal Ptfee8 { get; set; }
        public bool? Ptable8 { get; set; }
        public decimal Pfee9 { get; set; }
        public decimal Ptfee9 { get; set; }
        public bool? Ptable9 { get; set; }
        public decimal Pfeea { get; set; }
        public decimal Ptfeea { get; set; }
        public bool? Ptablea { get; set; }
        public decimal Pfeeb { get; set; }
        public decimal Ptfeeb { get; set; }
        public bool? Ptableb { get; set; }
        public decimal Pfeec { get; set; }
        public decimal Ptfeec { get; set; }
        public bool? Ptablec { get; set; }
        public decimal Pfeed { get; set; }
        public decimal Ptfeed { get; set; }
        public bool? Ptabled { get; set; }
        public decimal Pfeee { get; set; }
        public decimal Ptfeee { get; set; }
        public bool? Ptablee { get; set; }
        public decimal Pfeef { get; set; }
        public decimal Ptfeef { get; set; }
        public bool? Ptablef { get; set; }
        public decimal Pfeeg { get; set; }
        public decimal Ptfeeg { get; set; }
        public bool? Ptableg { get; set; }
        public decimal Pfeeh { get; set; }
        public decimal Ptfeeh { get; set; }
        public bool? Ptableh { get; set; }
        public decimal Pfeei { get; set; }
        public decimal Ptfeei { get; set; }
        public bool? Ptablei { get; set; }
        public decimal Pfeek { get; set; }
        public decimal Ptfeek { get; set; }
        public bool? Ptablek { get; set; }
        public decimal Pfeel { get; set; }
        public decimal Ptfeel { get; set; }
        public bool? Ptablel { get; set; }
        public decimal Pfeej { get; set; }
        public decimal Ptfeej { get; set; }
        public bool? Ptablej { get; set; }
        public decimal Pfeem { get; set; }
        public decimal Ptfeem { get; set; }
        public bool? Ptablem { get; set; }
        public decimal Pfeen { get; set; }
        public decimal Ptfeen { get; set; }
        public bool? Ptablen { get; set; }
        public decimal Pfeeo { get; set; }
        public decimal Ptfeeo { get; set; }
        public bool? Ptableo { get; set; }
        public decimal Pfeep { get; set; }
        public decimal Ptfeep { get; set; }
        public bool? Ptablep { get; set; }
        public decimal Pfeeq { get; set; }
        public decimal Ptfeeq { get; set; }
        public bool? Ptableq { get; set; }
        public decimal Pfeer { get; set; }
        public decimal Ptfeer { get; set; }
        public bool? Ptabler { get; set; }
        public decimal Pfees { get; set; }
        public decimal Ptfees { get; set; }
        public bool? Ptables { get; set; }
        public decimal Pfeet { get; set; }
        public decimal Ptfeet { get; set; }
        public bool? Ptablet { get; set; }
        public decimal Pfeeu { get; set; }
        public decimal Ptfeeu { get; set; }
        public bool? Ptableu { get; set; }
        public decimal Pfeev { get; set; }
        public decimal Ptfeev { get; set; }
        public bool? Ptablev { get; set; }
        public decimal Pfeew { get; set; }
        public decimal Ptfeew { get; set; }
        public bool? Ptablew { get; set; }
        public decimal Pfeex { get; set; }
        public decimal Ptfeex { get; set; }
        public bool? Ptablex { get; set; }
        public double? Pfeey { get; set; }
        public double? Ptfeey { get; set; }
        public bool? Ptabley { get; set; }
        public double? Pfeez { get; set; }
        public double? Ptfeez { get; set; }
        public bool? Ptablez { get; set; }
        public bool? Askkk { get; set; }
        public decimal Location { get; set; }
    }
}
