//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccumConfig
    {
        public int ACCUM_CONFIG_KEY { get; set; }
        public string SHORT_DESCR { get; set; }
        public string LONG_DESCR { get; set; }
        public string TASK_ACTION_RESULT_KEYS { get; set; }
        public string AGENT_ACTION_KEYS { get; set; }
        public string RESULT1_KEYS { get; set; }
        public string RESULT2_KEYS { get; set; }
        public decimal ACCUM_COST { get; set; }
        public bool SHOW_IN_RI { get; set; }
        public string EXCLUDE_RESULTS { get; set; }
    }
}
