//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACH_Recv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACH_Recv()
        {
            this.ACH_History = new HashSet<ACH_History>();
            this.ACH_HistoryCashedCheck = new HashSet<ACH_HistoryCashedCheck>();
            this.ACH_Sent = new HashSet<ACH_Sent>();
            this.UDDReports = new HashSet<UDDReport>();
        }
    
        public int ACH_RECV_KEY { get; set; }
        public string FILE_NAME_RECV { get; set; }
        public System.DateTime DATE_RECV { get; set; }
        public int PAID_COUNT { get; set; }
        public decimal PAID_TOTAL { get; set; }
        public int UNPAID_COUNT { get; set; }
        public decimal UNPAID_TOTAL { get; set; }
        public Nullable<System.DateTime> BTIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACH_History> ACH_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACH_HistoryCashedCheck> ACH_HistoryCashedCheck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACH_Sent> ACH_Sent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UDDReport> UDDReports { get; set; }
    }
}
