//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACH_HistoryCashedCheck
    {
        public int ACH_HISTORY_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public short LOCATION { get; set; }
        public int CASHED_CHECK_KEY { get; set; }
        public decimal ACH_AMOUNT { get; set; }
        public byte ACH_ATTEMPT { get; set; }
        public bool ACH_ATTEMPT2_HIST { get; set; }
        public System.DateTime PROJ_SEND_DATE { get; set; }
        public Nullable<System.DateTime> MANUAL_SEND_DATE { get; set; }
        public string MANUAL_TELLER { get; set; }
        public int ACH_SENT_KEY { get; set; }
        public Nullable<int> ACH_RECV_KEY { get; set; }
        public string ACH_RESULT_CODE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ABA_NO { get; set; }
        public string BANK_NO { get; set; }
        public int JOBID { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
    
        public virtual ACH_Recv ACH_Recv { get; set; }
        public virtual ACH_Sent ACH_Sent { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
