//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBankConfigException
    {
        public int ACH_BANK_CONFIG_EXCEPTION_KEY { get; set; }
        public int ACH_BANK_CONFIG_KEY { get; set; }
        public short LOC { get; set; }
        public string VALUE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    
        public virtual ACHBankConfig ACHBankConfig { get; set; }
        public virtual Company Company { get; set; }
    }
}
