//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHBatchHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACHBatchHeader()
        {
            this.ACHDetails = new HashSet<ACHDetail>();
        }
    
        public int ACH_BATCH_HEADER_KEY { get; set; }
        public string RECORD_TYPE { get; set; }
        public string SERVICE_CLASS_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_DISCRETIONARY_DATA { get; set; }
        public string COMPANY_ID { get; set; }
        public string SEC_CODE { get; set; }
        public string COMPANY_ENTRY_DESCRIPTION { get; set; }
        public string COMPANY_DESCRIPTIVE_DATA { get; set; }
        public string EFFECTIVE_ENTRY_DATE { get; set; }
        public string JULIAN_SETTLEMENT_DATE { get; set; }
        public string STATUS_CODE { get; set; }
        public string ORIGINATING_DFI_ROUTING_NUMBER { get; set; }
        public string BATCH_NUMBER { get; set; }
        public bool PROCESSED_RETURNS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHDetail> ACHDetails { get; set; }
    }
}
