//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHDetailAddendum
    {
        public int ACH_DETAIL_ADDENDUM_KEY { get; set; }
        public int ACH_DETAIL_KEY { get; set; }
        public string RECORD_TYPE { get; set; }
        public string ADDENDA_TYPE_CODE { get; set; }
        public string RETURN_NOC_CODE { get; set; }
        public string ORIGINAL_TRACE_NUMBER { get; set; }
        public string DATE_OF_DEATH { get; set; }
        public string ORIGINAL_RFDI_RT_NUMBER { get; set; }
        public string ADDENDA_INFORMATION { get; set; }
        public string TRACE_NUMBER { get; set; }
    
        public virtual ACHDetail ACHDetail { get; set; }
    }
}
