//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHQueue
    {
        public int ACH_QUEUE_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public System.DateTime DATE_TO_SEND { get; set; }
        public string TELLER { get; set; }
        public int LOAN_KEY { get; set; }
        public decimal AMOUNT { get; set; }
        public string ABA { get; set; }
        public string ACCOUNT { get; set; }
        public short ACH_REASON_CODE { get; set; }
        public bool IS_CREDIT { get; set; }
        public decimal LOAN_BALANCE { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual ACHReason ACHReason { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
