//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHSentParent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACHSentParent()
        {
            this.ACH_Sent = new HashSet<ACH_Sent>();
        }
    
        public int ACH_SENT_PARENT_KEY { get; set; }
        public string ACH_FILE_NAME_SENT { get; set; }
        public string ACH_FILE_NAME_ACK { get; set; }
        public int ACH_FILE_REC_CNT { get; set; }
        public decimal ACH_FILE_TOTAL_AMT { get; set; }
        public System.DateTime ACH_SENT_DATE { get; set; }
        public string FILE_TYPE { get; set; }
        public bool SCHEDULED_PAYMENTS { get; set; }
        public Nullable<bool> IS_AD_ASTRA { get; set; }
        public Nullable<bool> IS_DAY_AFTER_DUE_SENT { get; set; }
        public Nullable<System.DateTime> EXPECTED_RESULTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACH_Sent> ACH_Sent { get; set; }
    }
}
