//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdAstraWebInventory
    {
        public int RISREPT_KEY { get; set; }
        public string REFERENCE { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public decimal RI_BALANCE { get; set; }
        public bool IS_ELIGIBLE { get; set; }
        public Nullable<int> RIS_AUDIT_ID { get; set; }
    }
}
