//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMLAdditionalParty
    {
        public int AML_ADDITIONAL_PARTY_KEY { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public string ENTITY_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MID_INITIAL { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> AML_OCCUPATION_KEY { get; set; }
        public string ADDRESS_FORMAT { get; set; }
        public string ADDR_NUM { get; set; }
        public string ADDR_PRE_DIR { get; set; }
        public string ADDR_STREET { get; set; }
        public string ADDR_SUFFIX { get; set; }
        public string ADDR_POST_DIR { get; set; }
        public string ADDR_SUITE { get; set; }
        public string ADDR_SUITE_NUM { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public string FLAT_NUM { get; set; }
        public string BUILDING_NUM { get; set; }
        public string BUILDING_NAME { get; set; }
        public string ID_TYPE { get; set; }
        public string ID_NUMBER { get; set; }
        public string ID_STATE { get; set; }
        public Nullable<int> COUNTRY_KEY { get; set; }
        public string TAX_ID { get; set; }
        public string PURPOSE { get; set; }
        public string RELATIONSHIP { get; set; }
        public bool IS_ENTITY { get; set; }
        public bool IS_REGISTERED_CHARITY { get; set; }
        public string INCORPORATION_NUMBER { get; set; }
        public string INCORPORATION_PLACE { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string ADDRESS_CSZ { get; set; }
        public string ADDRESS_LINE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
    
        public virtual AMLOccupation AMLOccupation { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual TransDetail TransDetail { get; set; }
    }
}
