//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMLForeignAddress
    {
        public int AML_FOREIGN_ADDRESS_KEY { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public int COUNTRY_KEY { get; set; }
        public string PHONE_NUMBER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
