//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppValue
    {
        public short APP_VALUE_KEY { get; set; }
        public short APP_CONFIG_KEY { get; set; }
        public short APP_SETTING_KEY { get; set; }
        public string APP_VALUE { get; set; }
        public System.DateTime LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual AppConfig AppConfig { get; set; }
        public virtual AppSetting AppSetting { get; set; }
    }
}
