//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDDISReasonCodeMapping
    {
        public string AUDDIS_REASON_CODE { get; set; }
        public int DDI_STATUS_CODE { get; set; }
    }
}
