//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoReportTab
    {
        public int AUTO_REPORT_TAB_KEY { get; set; }
        public int AUTO_REPORT_KEY { get; set; }
        public byte RESULT_NUM { get; set; }
        public string TAB_NAME { get; set; }
    
        public virtual AutoReport AutoReport { get; set; }
    }
}
