//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoReport()
        {
            this.AutoReportEmails = new HashSet<AutoReportEmail>();
            this.AutoReportSchedules = new HashSet<AutoReportSchedule>();
            this.AutoReportTabs = new HashSet<AutoReportTab>();
        }
    
        public int AUTO_REPORT_KEY { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public string REPORT_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string OUTFILE { get; set; }
        public string REPORT_SQL { get; set; }
        public bool RUN_MON { get; set; }
        public bool RUN_TUE { get; set; }
        public bool RUN_WED { get; set; }
        public bool RUN_THU { get; set; }
        public bool RUN_FRI { get; set; }
        public bool RUN_SAT { get; set; }
        public bool RUN_SUN { get; set; }
        public bool RUN_EOM { get; set; }
        public bool RUN_EOQ { get; set; }
        public bool RUN_EOY { get; set; }
        public byte RUN_DOM { get; set; }
        public bool OUTPUT_XLS { get; set; }
        public bool OUTPUT_PDF { get; set; }
        public string SQL_FILE_LOCATION { get; set; }
        public bool ATTACH_FILE_TO_EMAIL { get; set; }
        public bool OUTPUT_CSV { get; set; }
        public string EMAIL_SUBJECT { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoReportEmail> AutoReportEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoReportSchedule> AutoReportSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoReportTab> AutoReportTabs { get; set; }
    }
}
