//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalSheet2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BalSheet2()
        {
            this.BalSheet_TransDetail = new HashSet<BalSheet_TransDetail>();
            this.BalSheetColumns2 = new HashSet<BalSheetColumns2>();
            this.EndOfDayRpts = new HashSet<EndOfDayRpt>();
        }
    
        public int BALSHEET_KEY { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public System.DateTime BUSINESS_DATE { get; set; }
        public bool EXPORTED { get; set; }
        public Nullable<bool> TRECS_EXPORT { get; set; }
        public Nullable<bool> ADASTRA_EXPORTED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalSheet_TransDetail> BalSheet_TransDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalSheetColumns2> BalSheetColumns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndOfDayRpt> EndOfDayRpts { get; set; }
    }
}
