//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapsCCTXRef
    {
        public int CREDIT_CARD_TRANS_KEY { get; set; }
        public int CAPS_HOLD_KEY { get; set; }
        public bool APPROVED { get; set; }
        public bool POSTED { get; set; }
        public decimal AMT { get; set; }
    
        public virtual CapsHold CapsHold { get; set; }
    }
}
