//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapsHold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CapsHold()
        {
            this.CapsCCTXRefs = new HashSet<CapsCCTXRef>();
        }
    
        public int CAPS_HOLD_KEY { get; set; }
        public int CAPS_RUN_KEY { get; set; }
        public int RISREPT_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int CASHED_CHECK_KEY { get; set; }
        public int OPTPLUS_CARD_DETAIL_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int ISSUER_KEY { get; set; }
        public int PTP_HEADER_KEY { get; set; }
        public int PTP_DETAIL_KEY { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public decimal AMT_TO_COLLECT { get; set; }
        public string DEPOSIT_METHOD { get; set; }
        public int DEPOSIT_ORDER { get; set; }
        public string BILLING_ADDRESS { get; set; }
        public string BILLING_CITY { get; set; }
        public string BILLING_STATE { get; set; }
        public string BILLING_ZIPCODE { get; set; }
        public short LOCATION { get; set; }
        public Nullable<int> RIS_AUDIT_ID { get; set; }
        public int CREDITCARD_KEY { get; set; }
        public string CARDNUM { get; set; }
        public string NAMEONCARD { get; set; }
        public byte EXPMONTH { get; set; }
        public int EXPYEAR { get; set; }
        public string TOKEN { get; set; }
        public byte CARD_BRAND { get; set; }
        public byte CARD_TYPE { get; set; }
        public string TELLER { get; set; }
        public string LOAN_TYPE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public bool SELECTED { get; set; }
        public bool PROCESSED { get; set; }
        public bool APPROVED { get; set; }
        public bool POSTED { get; set; }
        public string APP_ERR_CODE { get; set; }
        public byte CAPS_SKIP_REASON_KEY { get; set; }
        public int RI_AGE { get; set; }
        public Nullable<System.DateTime> LAST_DCARD_ATTEMPT_DATE { get; set; }
        public Nullable<int> DCARD_CONSECUTIVE_DAYS { get; set; }
        public Nullable<int> LAST_CCTRANS_KEY { get; set; }
        public Nullable<decimal> AMT_COLLECTED { get; set; }
        public bool EXCLUDE_FROM_CAP { get; set; }
        public decimal TOT_FEE_AMT { get; set; }
        public string CAPS_ATTEMPT_ID { get; set; }
        public Nullable<System.DateTime> CALC_PAY_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapsCCTXRef> CapsCCTXRefs { get; set; }
        public virtual CapsSkipReason CapsSkipReason { get; set; }
    }
}
