//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckAgain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckAgain()
        {
            this.CheckAgainHistories = new HashSet<CheckAgainHistory>();
        }
    
        public int CHECKAGAIN_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public bool SENT { get; set; }
    
        public virtual Loan Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckAgainHistory> CheckAgainHistories { get; set; }
    }
}
