//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionAction
    {
        public int COLLECTION_ACTION_KEY { get; set; }
        public int RISREPT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public string NOTE { get; set; }
        public int AGENT_ACTION_KEY { get; set; }
        public int AGENT_RESULT_KEY1 { get; set; }
        public Nullable<int> AGENT_RESULT_KEY2 { get; set; }
        public Nullable<int> COLLECTION_MOVEMENT_KEY { get; set; }
        public Nullable<int> TASK_ACTION_RESULT_KEY { get; set; }
        public Nullable<int> CUSTOMER_PHONE_NUMBER_KEY { get; set; }
        public bool IS_AD_ASTRA { get; set; }
    
        public virtual AgentAction AgentAction { get; set; }
        public virtual Company Company { get; set; }
        public virtual RISREPT RISREPT { get; set; }
    }
}
