//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionMovement
    {
        public int COLLECTION_MOVEMENT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public int RISREPT_KEY { get; set; }
        public int AUDIT_KEY { get; set; }
        public Nullable<System.DateTime> FOLLOWUP_DATE { get; set; }
        public Nullable<int> COLLECTION_AGENCY_KEY { get; set; }
        public Nullable<byte> ASSIGNMENT_NUMBER { get; set; }
        public string CR_TELLER { get; set; }
        public Nullable<int> REASON_FOR_ARREARS_KEY { get; set; }
    
        public virtual RISREPT RISREPT { get; set; }
    }
}
