//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollBonusPTP
    {
        public Nullable<int> PTP_DETAIL_KEY { get; set; }
        public Nullable<int> RISREPT_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string LOAN_TYPE { get; set; }
        public string TELLER { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<byte> PTP_TYPE { get; set; }
        public Nullable<short> LOCATION { get; set; }
        public int COLL_BONUS_PTP_KEY { get; set; }
    }
}
