//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtesyPayout
    {
        public int COURTESY_PAYOUT_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public decimal COURTESY_PAYOUT_AMT { get; set; }
        public string COURTESY_PAYOUT_TYPE { get; set; }
        public Nullable<int> SERVICE_TRANS_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public short LOCATION { get; set; }
        public string NOTE { get; set; }
        public string RTF_NOTE { get; set; }
        public Nullable<int> CASHED_CHECK_KEY { get; set; }
    
        public virtual CashedCheck CashedCheck { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ServiceTran ServiceTran { get; set; }
        public virtual TransDetail TransDetail { get; set; }
    }
}
