//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditCardTran()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
        }
    
        public int CREDIT_CARD_TRANS_KEY { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public string REQ_FILE_TYPE { get; set; }
        public string CCARD_NAME { get; set; }
        public decimal CHARGE_AMT { get; set; }
        public Nullable<int> REFUND_TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
        public Nullable<bool> SUCCESS_FLAG { get; set; }
        public string ERROR_MSG { get; set; }
        public Nullable<int> TRANS_POS_KEY { get; set; }
        public Nullable<int> RISREPT_KEY { get; set; }
        public string AUTH_CODE { get; set; }
        public Nullable<int> RITA_TROUTD { get; set; }
        public Nullable<int> RITA_SEQUENCE_NUM { get; set; }
        public string RESULT_CODE { get; set; }
        public string DECLINE_CODE { get; set; }
        public string AVS_CODE { get; set; }
        public string CVV_CODE { get; set; }
        public string TOKEN { get; set; }
        public Nullable<decimal> FEE_CHARGED_AMT { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public string VENDOR_RESPONSE { get; set; }
        public string EPDQ_TRANS_ID { get; set; }
        public string VENDOR_POST { get; set; }
        public Nullable<short> CREDIT_CARD_RESULT_CODE_KEY { get; set; }
        public Nullable<byte> CREDIT_CARD_VENDOR_KEY { get; set; }
        public string DECLINE_CODE_TWO_CHAR { get; set; }
        public string AVS_CODE_TWO_CHAR { get; set; }
        public string CCARD_NUM { get; set; }
        public Nullable<byte> EXP_MONTH { get; set; }
        public Nullable<byte> EXP_YEAR { get; set; }
        public string MAG_STRIP { get; set; }
    
        public virtual CreditCardVendor CreditCardVendor { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TransDetail TransDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
        public virtual ZeroDollarAuth ZeroDollarAuth { get; set; }
    }
}
