//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardResultCodeType
    {
        public byte RESULT_CODE_TYPE_ID { get; set; }
        public string RESULT_CODE_TYPE_DESCRIPTION { get; set; }
    }
}
