//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditVendorData
    {
        public int CREDIT_VENDOR_DATA_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public byte VERITEC_STATUS { get; set; }
        public string DEF_STATE { get; set; }
        public int LOAN_KEY { get; set; }
        public decimal TRANS_AMOUNT { get; set; }
        public string CLVERIFY_PAYMENT_CODE { get; set; }
        public Nullable<int> CLVERIFY_PAYMENT_NUMBER { get; set; }
        public byte CLVERIFY_STATUS { get; set; }
        public byte DATAX_STATUS { get; set; }
        public int ORIGINAL_LOAN_KEY { get; set; }
        public bool IS_SENT_VERITEC { get; set; }
        public bool IS_SENT_DATAX { get; set; }
        public bool IS_SENT_CLVERIFY { get; set; }
        public string SENT_MSG { get; set; }
        public Nullable<bool> IS_SENT_GENTRY { get; set; }
        public Nullable<short> DAYS_LATE { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public Nullable<byte> CLARITY_STATUS { get; set; }
        public Nullable<bool> IS_SENT_CLARITY { get; set; }
    }
}
