//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardXRef
    {
        public int CREDITCARDXREF_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public string ORIGINAL_PRN { get; set; }
        public string ID_NO { get; set; }
        public byte CARD_BRAND { get; set; }
        public Nullable<int> CREDIT_CARD_KEY { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
