//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardBrand
    {
        public int CREDIT_CARD_BRAND_KEY { get; set; }
        public string BRAND_NAME { get; set; }
        public string BRAND_DESCRIPTION { get; set; }
    }
}
