//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuroHelp
    {
        public int CUROHELP_KEY { get; set; }
        public string FORM_NAME { get; set; }
        public string CONTROL_NAME { get; set; }
        public string HELP_TITLE { get; set; }
        public string HELP_TEXT { get; set; }
        public string TOOLTIP_TEXT { get; set; }
    }
}
