//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchangeConfig
    {
        public int CURRENCY_EXCHANGE_CONFIG_KEY { get; set; }
        public int CURRENCY_KEY { get; set; }
        public short LOCATION { get; set; }
        public bool MANUAL_FEE_OVERRIDE { get; set; }
        public decimal MIN_EXCHANGE_FEE { get; set; }
        public decimal MAX_EXCHANGE_FEE { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public decimal EXCHANGE_FEE { get; set; }
        public bool EXCHANGE_RATE_OVERRIDE { get; set; }
        public decimal MAX_EXCHANGE_RATE { get; set; }
        public decimal MIN_EXCHANGE_RATE { get; set; }
        public bool DUAL_AUTHORIZATION { get; set; }
        public bool GOVT_ID_REQUIRED { get; set; }
        public decimal BUY_EXCHANGE_RATE_PERCENT { get; set; }
        public decimal SELL_EXCHANGE_RATE_PERCENT { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
