//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMergeHistory
    {
        public int CUSTOMER_MERGE_HISTORY_KEY { get; set; }
        public int DELETED_CUST_PKEY { get; set; }
        public int MERGED_INTO_CUST_PKEY { get; set; }
        public System.DateTime DATE_ENTERED_WITH_SECONDS { get; set; }
        public string TELLER { get; set; }
    }
}
