//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLeadLocation
    {
        public int CUSTOMER_LEAD_LOCATION_KEY { get; set; }
        public short LOCATION { get; set; }
        public bool IS_SUPERSTORE { get; set; }
        public short OF_SUPERSTORE { get; set; }
        public Nullable<short> SUPERSTORE_RADIUS { get; set; }
        public Nullable<short> WARNING_AGE { get; set; }
        public Nullable<short> REFRESH_RATE { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
