//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFeedback
    {
        public int CUSTOMER_FEEDBACK_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public short LOCATION { get; set; }
        public int CUSTOMER_FEEDBACK_TYPE_KEY { get; set; }
        public int CUSTOMER_FEEDBACK_CATEGORY_KEY { get; set; }
        public Nullable<int> CUSTOMER_FEEDBACK_RESOLUTION_KEY { get; set; }
        public string FEEDBACK { get; set; }
        public string RESOLUTION_NOTES { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerFeedbackCategory CustomerFeedbackCategory { get; set; }
        public virtual CustomerFeedbackResolution CustomerFeedbackResolution { get; set; }
        public virtual CustomerFeedbackType CustomerFeedbackType { get; set; }
    }
}
