//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEarnedCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerEarnedCredit()
        {
            this.EarnedCreditTrans = new HashSet<EarnedCreditTran>();
        }
    
        public int CUSTOMER_EARNED_CREDIT_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int EARNED_CREDIT_TYPE_KEY { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public decimal TOTAL_EARNED { get; set; }
        public decimal TOTAL_REDEEMED { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EarnedCreditType EarnedCreditType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EarnedCreditTran> EarnedCreditTrans { get; set; }
    }
}
