//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class dba_indexDefragLog
    {
        public int indexDefrag_id { get; set; }
        public int databaseID { get; set; }
        public string databaseName { get; set; }
        public int objectID { get; set; }
        public string objectName { get; set; }
        public int indexID { get; set; }
        public string indexName { get; set; }
        public short partitionNumber { get; set; }
        public double fragmentation { get; set; }
        public int page_count { get; set; }
        public System.DateTime dateTimeStart { get; set; }
        public int durationSeconds { get; set; }
    }
}
