//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCardChargeBackXRef
    {
        public int DCARD_CHARGE_BACK_XREF_KEY { get; set; }
        public int REFUND_TRANS_DETAIL_KEY { get; set; }
        public int REFUNDED_TRANS_DETAIL_KEY { get; set; }
        public decimal CHARGE_BACK_AMOUNT { get; set; }
    
        public virtual TransDetail TransDetail { get; set; }
        public virtual TransDetail TransDetail1 { get; set; }
    }
}
