//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDIStatu
    {
        public int DDI_STATUS_KEY { get; set; }
        public int STATUS_CODE { get; set; }
        public string DISPLAY { get; set; }
        public string CODE_DESCRIPTION { get; set; }
    }
}
