//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDISendDetail
    {
        public int DDI_SEND_DETAIL_KEY { get; set; }
        public int DDI_SEND_KEY { get; set; }
        public int DDI_KEY { get; set; }
        public string SORT_CODE { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string LAST_NAME { get; set; }
        public string REFERENCE { get; set; }
        public string TRANS_CODE { get; set; }
        public System.DateTime SENT_DATE { get; set; }
        public string STATUS { get; set; }
        public string ORIGINATOR { get; set; }
        public string SENT_BY { get; set; }
    
        public virtual DDI DDI { get; set; }
        public virtual DDISend DDISend { get; set; }
    }
}
