//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositChkDetail
    {
        public int DEPOSIT_CHK_DETAIL_KEY { get; set; }
        public int DEPOSIT_CHK_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public Nullable<int> CASHED_CHECK_KEY { get; set; }
    
        public virtual CashedCheck CashedCheck { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DepositChk DepositChk { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
