//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialerKey
    {
        public Nullable<int> rikey { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string jobname { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> balancetest { get; set; }
        public Nullable<bool> Exclude { get; set; }
        public Nullable<bool> Exported { get; set; }
        public Nullable<short> ris_audit_id { get; set; }
        public Nullable<System.DateTime> Followup { get; set; }
        public Nullable<bool> COURTESY_EXPORT { get; set; }
        public int DIALER_KEYS_KEY { get; set; }
        public bool ExportedToNoble { get; set; }
    }
}
