//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc10000Trans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc10000Trans()
        {
            this.Doc10000TransDetail = new HashSet<Doc10000TransDetail>();
        }
    
        public int DOC_10000_TRANS_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public decimal CASH_IN { get; set; }
        public decimal CASH_OUT { get; set; }
        public bool CASHED_CHECK { get; set; }
        public byte FORM_TYPE { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc10000TransDetail> Doc10000TransDetail { get; set; }
    }
}
