//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentResource()
        {
            this.CompanyDocumentResources = new HashSet<CompanyDocumentResource>();
        }
    
        public int DOCUMENT_RESOURCE_KEY { get; set; }
        public string RESOURCE_NAME { get; set; }
        public byte[] DATA { get; set; }
        public short MIME_TYPE_KEY { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime CREATED_DATETIME { get; set; }
        public System.DateTime UPDATED_DATETIME { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyDocumentResource> CompanyDocumentResources { get; set; }
        public virtual TELLERID TELLERID { get; set; }
        public virtual MimeType MimeType { get; set; }
        public virtual TELLERID TELLERID1 { get; set; }
    }
}
