//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPrinting
    {
        public int DOCUMENT_PRINTING_KEY { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string PRINTER_NAME { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    }
}
