//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DualApprovalMessage
    {
        public int DUAL_APPROVAL_MESSAGE_KEY { get; set; }
        public string APPROVAL_MESSAGE { get; set; }
        public int MESSAGE_ID { get; set; }
    }
}
