//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarnedCreditTran
    {
        public int EARNED_CREDIT_TRANS_KEY { get; set; }
        public int CUSTOMER_EARNED_CREDIT_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public decimal EARNED_AMT { get; set; }
        public bool REVERSED { get; set; }
        public Nullable<System.DateTime> REVERSED_DATE { get; set; }
    
        public virtual CustomerEarnedCredit CustomerEarnedCredit { get; set; }
        public virtual TransDetail TransDetail { get; set; }
    }
}
