//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfDayRptDetail
    {
        public int EODR_DET_KEY { get; set; }
        public int EODR_KEY { get; set; }
        public short ORDER_NUM { get; set; }
        public string EODR_DESC { get; set; }
        public string ACCOUNT1 { get; set; }
        public string QTY1 { get; set; }
        public string AMOUNT1 { get; set; }
        public string FEE1 { get; set; }
        public string ACCOUNT2 { get; set; }
        public string QTY2 { get; set; }
        public string AMOUNT2 { get; set; }
        public string FEE2 { get; set; }
        public bool HEADER { get; set; }
        public bool FOOTER { get; set; }
    
        public virtual EndOfDayRpt EndOfDayRpt { get; set; }
    }
}
