//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndOfDayInventoryDetail
    {
        public int EODR_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public decimal ONHAND_AMT { get; set; }
        public bool DEFAULTED { get; set; }
        public decimal RI_BALANCE { get; set; }
        public Nullable<decimal> CAB_FEE_RECEIVABLE_AMT { get; set; }
    }
}
