//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOscarBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EOscarBatch()
        {
            this.EOscarBatchDetails = new HashSet<EOscarBatchDetail>();
            this.EOscarBatchDetails1 = new HashSet<EOscarBatchDetail>();
        }
    
        public int EOSCAR_BATCH_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public int BATCH_ID { get; set; }
        public int QUEUE_ID { get; set; }
        public string TELLER { get; set; }
        public string SEND_RECV { get; set; }
        public string RAW_XML { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EOscarBatchDetail> EOscarBatchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EOscarBatchDetail> EOscarBatchDetails1 { get; set; }
    }
}
