//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOscarBatchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EOscarBatchDetail()
        {
            this.EOscarDetailDisputeCodes = new HashSet<EOscarDetailDisputeCode>();
        }
    
        public int EOSCAR_BATCH_DETAIL_KEY { get; set; }
        public int EOSCAR_BATCH_KEY_RECV { get; set; }
        public Nullable<int> EOSCAR_BATCH_KEY_SENT { get; set; }
        public int ACDV_IDENTIFIER { get; set; }
        public string ACDV_CONTROL_NUMBER { get; set; }
        public int RISREPT_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public bool MANUAL_EXPORT { get; set; }
        public bool MANUAL_REVIEW { get; set; }
        public bool PROCESSED { get; set; }
        public string XML_RECV { get; set; }
        public string XML_SENT { get; set; }
    
        public virtual EOscarBatch EOscarBatch { get; set; }
        public virtual EOscarBatch EOscarBatch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EOscarDetailDisputeCode> EOscarDetailDisputeCodes { get; set; }
    }
}
