//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOscarDisputeCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EOscarDisputeCode()
        {
            this.EOscarDetailDisputeCodes = new HashSet<EOscarDetailDisputeCode>();
        }
    
        public int EOSCAR_DISPUTE_CODE_KEY { get; set; }
        public string DISPUTE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool MANUAL_PROCESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EOscarDetailDisputeCode> EOscarDetailDisputeCodes { get; set; }
    }
}
