//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESignOptInDoc
    {
        public int ESIGN_OPT_IN_DOC_KEY { get; set; }
        public string DOC_XML { get; set; }
        public string LANGUAGE { get; set; }
        public string DOC_NAME { get; set; }
        public System.DateTime DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
