//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESignOptIn
    {
        public int ESIGN_OPT_IN_KEY { get; set; }
        public int ESIGN_OPT_IN_DOC_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public short LOCATION { get; set; }
    }
}
