//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRateDaily
    {
        public int EXCHANGE_RATE_DAILY_KEY { get; set; }
        public System.DateTime EXCHANGE_RATE_DATE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string BASE_CURRENCY_CODE { get; set; }
        public decimal RATE { get; set; }
    }
}
