//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcludeFromCapsHistory
    {
        public int EXCLUDE_FROM_CAPS_HISTORY_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public string TELLER { get; set; }
        public short LOCATION { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public bool EXCLUDE_FROM_CAPS { get; set; }
        public bool EXCLUDE_FROM_CAPS_ACH { get; set; }
        public string OPT_OUT_REASON { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
