//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalAppRunDate
    {
        public int EXTERNAL_APPS_RUN_DATES_KEY { get; set; }
        public int EXTERNAL_APPS_KEY { get; set; }
        public Nullable<System.DateTime> RUN_DATE { get; set; }
        public byte priority { get; set; }
    
        public virtual ExternalApp ExternalApp { get; set; }
    }
}
