//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalAppMaster
    {
        public int EXTERNAL_APP_MASTER_KEY { get; set; }
        public string TASK_NAME { get; set; }
        public string SERVER_NAME { get; set; }
        public string DTS_OR_EXE { get; set; }
        public string RUN_FILE { get; set; }
        public string RUN_START_FOLDER { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS_DESC { get; set; }
        public Nullable<System.DateTime> NEXT_RUN_DATE { get; set; }
        public Nullable<System.DateTime> LAST_RUN_DATE { get; set; }
        public string LAST_RESULT { get; set; }
    }
}
