//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FcrmAmlTransCodeXRef
    {
        public int FCRM_AML_TRANS_CODE_XREF_KEY { get; set; }
        public int FCRM_AML_TRANS_CODE_KEY { get; set; }
        public int TRANS_CODE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
    
        public virtual FcrmAmlTransCode FcrmAmlTransCode { get; set; }
    }
}
