//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormLetterBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormLetterBatch()
        {
            this.FormLetterOnDemands = new HashSet<FormLetterOnDemand>();
            this.FormLetterPrinteds = new HashSet<FormLetterPrinted>();
            this.FormLetterResults = new HashSet<FormLetterResult>();
        }
    
        public int FORM_LETTER_BATCH_KEY { get; set; }
        public System.DateTime BATCH_DATE { get; set; }
        public string TELLER { get; set; }
        public string UPLOAD_OR_DOWNLOAD { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public byte FORM_LETTER_BATCH_STATUS_KEY { get; set; }
        public Nullable<System.DateTime> BATCH_STATUS_DATETIME { get; set; }
        public Nullable<byte> BATCH_STEP { get; set; }
    
        public virtual FormLetterBatchStatu FormLetterBatchStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetterOnDemand> FormLetterOnDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetterPrinted> FormLetterPrinteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetterResult> FormLetterResults { get; set; }
    }
}
