//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormLetterPrinted
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormLetterPrinted()
        {
            this.FormLetterResults = new HashSet<FormLetterResult>();
        }
    
        public int FORM_LETTER_PRINTED_KEY { get; set; }
        public int FORM_LETTER_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int CUSTOMER_ADDRESS_KEY { get; set; }
        public int FORM_LETTER_BATCH_KEY { get; set; }
        public Nullable<int> FORM_LETTER_ON_DEMAND_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public Nullable<int> PROMISE_TO_PAY_DETAIL_KEY { get; set; }
        public byte FORM_LETTER_RESULT_FILE_TYPE { get; set; }
        public Nullable<System.DateTime> VENDOR_DATE_PRINTED { get; set; }
        public string VENDOR_JOB_CODE { get; set; }
        public Nullable<byte> PROCESSING_STATE_KEY { get; set; }
        public Nullable<int> CASHED_CHECK_KEY { get; set; }
        public Nullable<int> OPTPLUS_CARD_DETAIL_KEY { get; set; }
        public Nullable<int> DWDOCID { get; set; }
        public Nullable<int> RISREPT_KEY { get; set; }
    
        public virtual CashedCheck CashedCheck { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual FormLetter FormLetter { get; set; }
        public virtual FormLetterBatch FormLetterBatch { get; set; }
        public virtual FormLetterOnDemand FormLetterOnDemand { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual OptPlusCardDetail OptPlusCardDetail { get; set; }
        public virtual PromiseToPayDetail PromiseToPayDetail { get; set; }
        public virtual RISREPT RISREPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetterResult> FormLetterResults { get; set; }
    }
}
