//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormLetterConfig
    {
        public int FORM_LETTER_CONFIG_KEY { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public string FTP_USERNAME { get; set; }
        public string FTP_PASSWORD { get; set; }
        public bool ENABLE_UPLOAD_BATCH { get; set; }
        public bool ENABLE_DOWNLOAD_BATCH { get; set; }
        public bool ENABLE_BATCH_VALIDATION { get; set; }
    }
}
