//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormLetterBatchBuildLetterProgress
    {
        public int FORM_LETTER_BATCH_BUILD_LETTER_PROGRESS_KEY { get; set; }
        public int FORM_LETTER_BATCH_KEY { get; set; }
        public int FORM_LETTER_KEY { get; set; }
        public bool BUILD_COMPLETE { get; set; }
    }
}
