//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormLetterBatchVendorFile
    {
        public int FORM_LETTER_BATCH_BUILD_VENDOR_FILE_KEY { get; set; }
        public int FORM_LETTER_BATCH_KEY { get; set; }
        public int FORM_LETTER_KEY { get; set; }
        public string FILE_NAME { get; set; }
        public bool UPLOADED { get; set; }
    }
}
