//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurtherFinanceResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FurtherFinanceResult()
        {
            this.FurtherFinanceResultDetails = new HashSet<FurtherFinanceResultDetail>();
        }
    
        public int FURTHER_FINANCE_RESULT_KEY { get; set; }
        public Nullable<int> FURTHER_FINANCE_PARENT_OUTCOME_KEY { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public string PRODUCT_TYPE_SELECTED { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurtherFinanceResultDetail> FurtherFinanceResultDetails { get; set; }
    }
}
