//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurtherFinanceExecutionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FurtherFinanceExecutionLog()
        {
            this.FurtherFinanceExecutionLogDetails = new HashSet<FurtherFinanceExecutionLogDetail>();
        }
    
        public int FURTHER_FINANCE_EXECUTION_LOG_KEY { get; set; }
        public Nullable<int> FURTHER_FINANCE_PARENT_OUTCOME_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string LOAN_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurtherFinanceExecutionLogDetail> FurtherFinanceExecutionLogDetails { get; set; }
    }
}
