//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalileoResponseCode
    {
        public int GALILEO_RESPONSE_CODE_KEY { get; set; }
        public short CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DETAIL { get; set; }
    }
}
