//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCard
    {
        public int GIFT_CARD_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public int SERVICE_DETAIL_KEY { get; set; }
        public short LOCATION { get; set; }
        public decimal CARD_AMOUNT { get; set; }
        public string CARD_NUMBER { get; set; }
        public string CARD_DATA { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ServiceDetail ServiceDetail { get; set; }
    }
}
