//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAcct
    {
        public int GL_ACCT_KEY { get; set; }
        public int GL_ACCT_NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IS_ADASTRA { get; set; }
        public bool IS_TITLE_ACCT { get; set; }
        public bool IS_NONCASH_ACCT { get; set; }
        public bool IS_TRECS_CASH_ACCT { get; set; }
    }
}
