//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalState
    {
        public int GLOBAL_STATES_KEY { get; set; }
        public string STATE_ABBRV { get; set; }
        public decimal TL_LIEN_FEE { get; set; }
        public short TL_APR_DAYS { get; set; }
        public decimal TL_TITLE_FEE { get; set; }
        public decimal TL_QUICK_TITLE_FEE { get; set; }
        public decimal TL_TITLE_PROC_FEE { get; set; }
        public decimal TL_NOTICE_OF_LIEN_FEE { get; set; }
        public bool ENABLE_CUST_MILITARY_STATUS { get; set; }
        public string STATE_FULL { get; set; }
        public bool REQUIRE_CUST_ID_SCAN { get; set; }
        public bool ENABLE_NOTIFY_REPO_COMPANY_MSG { get; set; }
        public short MIN_LOAN_AGE { get; set; }
        public bool ENABLE_SINGLE_OPEN_LOAN_TYPE { get; set; }
        public bool ENABLE_LOAN_MAINT_OTHER_STATES { get; set; }
        public decimal TL_NO_LIEN_FEE_FOR_LOANS_UP_TO { get; set; }
        public short DUE_DATE_PAYMENTS_THREAD_COUNT { get; set; }
        public bool SHOW_ACCESS_KEY { get; set; }
        public bool ENABLE_MARKETING_INVITATIONS { get; set; }
        public string MARKETING_INVITATION_OVERRIDES_TYPE { get; set; }
        public int MARKETING_INVITATION_INCOME_PCT { get; set; }
    }
}
