//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldDailyBagDetail
    {
        public int GOLD_DAILY_BAG_DETAIL_KEY { get; set; }
        public int GOLD_DAILY_BAG_KEY { get; set; }
        public int GOLD_TRANS_KEY { get; set; }
    
        public virtual GoldDailyBag GoldDailyBag { get; set; }
    }
}
