//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldTransCustomer
    {
        public int GOLD_TRANS_CUSTOMER_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public string GENDER { get; set; }
        public byte HEIGHT_FEET { get; set; }
        public byte HEIGHT_INCHES { get; set; }
        public short WEIGHT { get; set; }
        public byte RACE { get; set; }
        public byte EYE_COLOR { get; set; }
        public byte HAIR_COLOR { get; set; }
        public string HOME_PHONE { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public string PLATE_NUMBER { get; set; }
        public string PLATE_STATE { get; set; }
        public int GOLD_TRANS_KEY { get; set; }
        public bool REQUIRE_MID_NAME { get; set; }
        public string CUST_MID_NAME { get; set; }
        public bool REQUIRE_NOTHING { get; set; }
        public bool REQUIRE_GENDER { get; set; }
        public bool REQUIRE_HEIGHT { get; set; }
        public bool REQUIRE_WEIGHT { get; set; }
        public bool REQUIRE_RACE { get; set; }
        public bool REQUIRE_EYE_COLOR { get; set; }
        public bool REQUIRE_HAIR_COLOR { get; set; }
        public bool REQUIRE_MIN_AGE { get; set; }
        public byte REQUIRE_AGE_VALUE { get; set; }
        public bool REQUIRE_HOME_PHONE { get; set; }
        public bool REQUIRE_EMPLOYER_NAME { get; set; }
        public bool REQUIRE_PLATE_NUMBER { get; set; }
        public bool REQUIRE_PLATE_STATE { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual GoldTran GoldTran { get; set; }
    }
}
