//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldTransStoneDetail
    {
        public int GOLD_TRANS_STONE_DETAIL_KEY { get; set; }
        public int GOLD_TRANS_DETAIL_KEY { get; set; }
        public byte STONE_TYPE { get; set; }
        public decimal STONE_SIZE { get; set; }
        public byte STONE_COUNT { get; set; }
    
        public virtual GoldTransDetail GoldTransDetail { get; set; }
    }
}
