//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificationTypeState
    {
        public int IDENTIFICATION_TYPE_STATE_KEY { get; set; }
        public int IDENTIFICATION_TYPE_KEY { get; set; }
        public string ID_STATE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public bool STORE_EXPIRATION_REQUIRED { get; set; }
        public bool STORE_ACCEPTABLE_FOR_NEW_LOAN { get; set; }
        public bool WEB_ACCEPTABLE_FOR_NEW_LOAN { get; set; }
        public bool WEB_EXPIRATION_REQUIRED { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
