//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageCashLetterDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageCashLetterDetail()
        {
            this.ImageCashLetterBundles = new HashSet<ImageCashLetterBundle>();
        }
    
        public int IMAGE_CASH_LETTER_DETAIL_KEY { get; set; }
        public int IMAGE_CASH_LETTER_KEY { get; set; }
        public short LOCATION { get; set; }
        public string CASH_LETTER_STATUS { get; set; }
        public int REJECTED_ITEM_COUNT { get; set; }
        public decimal REJECTED_DOLLARS { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ImageCashLetter ImageCashLetter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageCashLetterBundle> ImageCashLetterBundles { get; set; }
    }
}
