//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeVerificationMessage
    {
        public int INCOME_VERIFICATION_MESSAGE_KEY { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string STATE { get; set; }
        public string MESSAGE_TEXT { get; set; }
    }
}
