//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceStatu()
        {
            this.InsuranceClaims = new HashSet<InsuranceClaim>();
            this.InsuranceClaimStatus = new HashSet<InsuranceClaimStatu>();
        }
    
        public int INSURANCE_STATUS_KEY { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string FULL_DESCRIPTION { get; set; }
        public bool IS_OPEN_CLAIM { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceClaim> InsuranceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceClaimStatu> InsuranceClaimStatus { get; set; }
    }
}
