//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePayment
    {
        public int INSURANCE_PAYMENT_KEY { get; set; }
        public int INSURANCE_PAYMENT_BATCH_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int INSURANCE_CLAIM_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public decimal PAID_AMT { get; set; }
        public bool PAST_DUE_BAL_WAIVED { get; set; }
    
        public virtual InsuranceClaim InsuranceClaim { get; set; }
        public virtual InsurancePaymentBatch InsurancePaymentBatch { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual TransDetail TransDetail { get; set; }
    }
}
