//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalProcessEmailType
    {
        public byte INTERNAL_PROCESS_EMAIL_TYPE_KEY { get; set; }
        public string INTERNAL_PROCESS_EMAIL_TYPE { get; set; }
    }
}
