//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpToCountry
    {
        public long FromIP { get; set; }
        public long ToIP { get; set; }
        public string CountryCode { get; set; }
        public long IPTOCOUNTRY_KEY { get; set; }
    }
}
