//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalVerification
    {
        public int LEGAL_VERIFICATION_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<int> RISREPT_KEY { get; set; }
        public string RI_REFERENCE { get; set; }
        public string DEBTOR_NUMBER { get; set; }
        public string PLAINTIFF1 { get; set; }
        public string PLAINTIFF2 { get; set; }
        public string DEFENDANT_FULLNAME { get; set; }
        public string DEFENDANT_ADDRESS_LINE { get; set; }
        public string DEFENDANT_ADDRESS_CSZ { get; set; }
        public string DEFENDANT_MASKED_SSN { get; set; }
        public decimal CUSTOMER_BALANCE_DUE { get; set; }
        public decimal COURT_COSTS { get; set; }
        public decimal DEFENDANT_TOTAL_DUE { get; set; }
        public decimal ATTORNEY_FEES { get; set; }
        public decimal ATTORNEY_TITLE_LOAN_BAL_DUE { get; set; }
        public decimal ATTORNEY_CURRENT_BAL_DUE { get; set; }
        public decimal ATTORNEY_POST_JUDGE_DUE { get; set; }
        public decimal PRINCIPLE_DUE { get; set; }
        public int EXCEPTION_REPORT_STATUS { get; set; }
        public string VERIFIED_TELLER { get; set; }
        public Nullable<System.DateTime> VERIFIED_DATE { get; set; }
        public string IMPORT_FILENAME { get; set; }
        public System.DateTime EXCEPTION_STATUS_LAST_UPDATED { get; set; }
        public byte REPORT_TYPE { get; set; }
    
        public virtual RISREPT RISREPT { get; set; }
    }
}
