//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanProductConfigInterestRate
    {
        public int LOAN_PRODUCT_CONFIG_INTEREST_RATE_KEY { get; set; }
        public int LOAN_PRODUCT_CONFIG_KEY { get; set; }
        public decimal LOAN_UP_TO_AMT { get; set; }
        public decimal INTEREST_RATE_PCT { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual LoanProductConfig LoanProductConfig { get; set; }
    }
}
