//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanFunding
    {
        public int LOAN_FUNDING_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int APPROVED_LOAN_PAYMENT_KEY { get; set; }
        public Nullable<int> FUNDING_TRANS_DETAIL_KEY { get; set; }
        public string REQUESTED_FUNDING_METHOD { get; set; }
        public string ACTUAL_FUNDING_METHOD { get; set; }
        public decimal FUNDING_AMT { get; set; }
        public string FUNDING_STATUS { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual LoanPayment LoanPayment { get; set; }
        public virtual TransDetail TransDetail { get; set; }
    }
}
