//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicationVehicleInformation
    {
        public int LOAN_APPLICATION_VEHICLE_INFORMATION_KEY { get; set; }
        public int LOAN_APPLICATION_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public decimal VEH_WHOLESALE { get; set; }
        public int VEH_MILEAGE { get; set; }
        public string VEH_CONDITION { get; set; }
        public string VEH_PLATE { get; set; }
        public string VEH_STICKER { get; set; }
        public Nullable<System.DateTime> VEH_REG_DATE { get; set; }
        public Nullable<System.DateTime> VEH_REG_EXPIRE { get; set; }
        public string VEH_REG_STATE { get; set; }
        public string VEH_TITLE_NUM { get; set; }
        public string VEH_ODO_CODE { get; set; }
        public string LEGAL_STATUS { get; set; }
        public string STATE_CUST_NUM { get; set; }
        public string INS_NAME { get; set; }
        public string INS_PHONE { get; set; }
        public bool INS_FULL_COVER { get; set; }
        public string INS_POLICY_NUM { get; set; }
        public bool PAY_VERIFIED { get; set; }
        public string AND_OR_NAME { get; set; }
        public Nullable<decimal> LIEN_BALANCE { get; set; }
        public string LIEN_ACCT_NUM { get; set; }
        public string VEH_VIN { get; set; }
        public string VEH_MAKE { get; set; }
        public string VEH_MODEL { get; set; }
        public string VEH_BODY { get; set; }
        public string VEH_ENGINE { get; set; }
        public string VEH_TRANS { get; set; }
        public string VEH_DRIVE { get; set; }
        public short VEH_YEAR { get; set; }
        public decimal VEH_RETAIL { get; set; }
        public bool IS_CLEAR_TITLE { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
