//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPaymentWaiveRIFee
    {
        public int LOAN_PAYMENT_WAIVE_RI_FEE_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
        public string WAIVE_RI_FEE_REASON_CODE { get; set; }
    
        public virtual LoanPayment LoanPayment { get; set; }
    }
}
