//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanService
    {
        public int LOAN_SERVICE_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int SERVICE_DETAIL_KEY { get; set; }
        public decimal SERVICE_COST { get; set; }
        public decimal PRICE { get; set; }
        public decimal MARK_DOWN { get; set; }
        public decimal SALES_TAX { get; set; }
        public decimal DOWN_PAYMENT { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual ServiceDetail ServiceDetail { get; set; }
    }
}
