//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicationDiscount
    {
        public int LOAN_APPLICATION_KEY { get; set; }
        public int DISCOUNT_MASTER_KEY { get; set; }
        public decimal AMOUNT_APPLIED { get; set; }
    
        public virtual DiscountMaster DiscountMaster { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
