//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanProductRollover
    {
        public int LOAN_PRODUCT_ROLLOVER_KEY { get; set; }
        public int LOAN_PRODUCT_KEY_PAID_LOAN { get; set; }
        public int LOAN_PRODUCT_KEY_NEW_LOAN { get; set; }
        public short LOCATION { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual LoanProduct LoanProduct { get; set; }
        public virtual LoanProductConfig LoanProductConfig { get; set; }
    }
}
