//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDepositOrderHistory
    {
        public int LOAN_DEPOSIT_ORDER_HISTORY_KEY { get; set; }
        public Nullable<int> RULE_DEF_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public string TELLER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public byte OLD_DEPOSIT_ORDER { get; set; }
        public byte NEW_DEPOSIT_ORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> RESET_REASON_KEY { get; set; }
    
        public virtual LoanDepositOrderResetReason LoanDepositOrderResetReason { get; set; }
        public virtual RuleDef RuleDef { get; set; }
    }
}
