//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDepositOrderResetReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanDepositOrderResetReason()
        {
            this.LoanDepositOrderHistories = new HashSet<LoanDepositOrderHistory>();
        }
    
        public int LOAN_DEPOSIT_ORDER_RESET_REASON_KEY { get; set; }
        public short REASON { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDepositOrderHistory> LoanDepositOrderHistories { get; set; }
    }
}
