//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPaymentInsuranceClaimXRef
    {
        public int LOAN_PAYMENT_INSURANCE_CLAIM_XREF_KEY { get; set; }
        public int INSURANCE_CLAIM_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
    
        public virtual InsuranceClaim InsuranceClaim { get; set; }
        public virtual LoanPayment LoanPayment { get; set; }
    }
}
