//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPaymentRescind
    {
        public int LOAN_PAYMENT_RESCIND_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
        public int CASH_ADVANCE_LOAN_PAYMENT_KEY { get; set; }
        public decimal RESCIND_AMOUNT { get; set; }
        public decimal INTEREST_REBATE { get; set; }
        public decimal CAB_LENDER_INTEREST_REBATE { get; set; }
    
        public virtual LoanPayment LoanPayment { get; set; }
        public virtual LoanPayment LoanPayment1 { get; set; }
    }
}
