//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanProductTila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanProductTila()
        {
            this.LoanApplicationProducts = new HashSet<LoanApplicationProduct>();
            this.LoanProductEnableNewLoans = new HashSet<LoanProductEnableNewLoan>();
        }
    
        public int LOAN_PRODUCT_TILA_KEY { get; set; }
        public string TILA_ADDR_STREET { get; set; }
        public string TILA_ADDRESS1 { get; set; }
        public string TILA_BUILDING_NAME { get; set; }
        public string TILA_BUILDING_NUM { get; set; }
        public string TILA_CERT_NUM { get; set; }
        public string TILA_CITY { get; set; }
        public string TILA_COUNTRY { get; set; }
        public string TILA_COUNTY { get; set; }
        public string TILA_FLAT_NUM { get; set; }
        public string TILA_NAME { get; set; }
        public string TILA_PHONE { get; set; }
        public string TILA_STATE { get; set; }
        public string TILA_ZIPCODE { get; set; }
        public string ADDRESS_FORMAT { get; set; }
        public string TILA_ADDRESS_CSZ { get; set; }
        public string TILA_ADDRESS_LINE { get; set; }
        public string TILA_ADDRESS_LINE_1 { get; set; }
        public string TILA_ADDRESS_LINE_2 { get; set; }
        public string TILA_ADDRESS_LINE_3 { get; set; }
        public short LOCATION { get; set; }
        public int LOANS_COUNT { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplicationProduct> LoanApplicationProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanProductEnableNewLoan> LoanProductEnableNewLoans { get; set; }
    }
}
