//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanStatusChange
    {
        public int LOAN_STATUS_CHANGE_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string OLD_LOAN_STATUS { get; set; }
        public string NEW_LOAN_STATUS { get; set; }
        public bool OLD_LOAN_DEFAULTED { get; set; }
        public bool NEW_LOAN_DEFAULTED { get; set; }
        public string REASON_DEFAULTED { get; set; }
        public bool REVERSED { get; set; }
        public Nullable<System.DateTime> REVERSED_DATE { get; set; }
    }
}
