//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicationExpense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplicationExpense()
        {
            this.LoanApplicationExpenseDetails = new HashSet<LoanApplicationExpenseDetail>();
        }
    
        public int LOAN_APPLICATION_EXPENSE_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
        public Nullable<int> ROLLOVER_REQUEST_KEY { get; set; }
        public int VISITOR_KEY { get; set; }
        public Nullable<bool> IS_CUSTOMER_VERIFIED { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual RolloverRequest RolloverRequest { get; set; }
        public virtual Visitor Visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplicationExpenseDetail> LoanApplicationExpenseDetails { get; set; }
    }
}
