//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanIncome
    {
        public int LOAN_INCOME_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int CUSTOMER_INCOME_KEY { get; set; }
    
        public virtual CustomerIncome CustomerIncome { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
