//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.ACHProcessingQueues = new HashSet<ACHProcessingQueue>();
            this.ACHQueues = new HashSet<ACHQueue>();
            this.AttorneyLoans = new HashSet<AttorneyLoan>();
            this.BusinessLoans = new HashSet<BusinessLoan>();
            this.CheckAgains = new HashSet<CheckAgain>();
            this.CourtesyPayouts = new HashSet<CourtesyPayout>();
            this.DDIs = new HashSet<DDI>();
            this.DDISendQueues = new HashSet<DDISendQueue>();
            this.DepositBagDetails = new HashSet<DepositBagDetail>();
            this.DepositChkDetails = new HashSet<DepositChkDetail>();
            this.DocumentSigningStatus = new HashSet<DocumentSigningStatu>();
            this.DocuwareLoanLkups = new HashSet<DocuwareLoanLkup>();
            this.ErrorLogs = new HashSet<ErrorLog>();
            this.ExcludeFromCapsHistories = new HashSet<ExcludeFromCapsHistory>();
            this.FormLetterOnDemands = new HashSet<FormLetterOnDemand>();
            this.FormLetterPrinteds = new HashSet<FormLetterPrinted>();
            this.InsuranceClaims = new HashSet<InsuranceClaim>();
            this.InsurancePayments = new HashSet<InsurancePayment>();
            this.LoanApplications = new HashSet<LoanApplication>();
            this.LoanCCallChanges = new HashSet<LoanCCallChange>();
            this.LoanChecks = new HashSet<LoanCheck>();
            this.LoanDocPrinteds = new HashSet<LoanDocPrinted>();
            this.LoanFundings = new HashSet<LoanFunding>();
            this.LoanFundingMethodHistories = new HashSet<LoanFundingMethodHistory>();
            this.LoanIncomes = new HashSet<LoanIncome>();
            this.LoanNotes = new HashSet<LoanNote>();
            this.LoanOverrides = new HashSet<LoanOverride>();
            this.LoanPayments = new HashSet<LoanPayment>();
            this.LoanServices = new HashSet<LoanService>();
            this.LoanWebReviewTemplateXrefs = new HashSet<LoanWebReviewTemplateXref>();
            this.MPayLoans = new HashSet<MPayLoan>();
            this.MPayAmorts = new HashSet<MPayAmort>();
            this.MPayAmortDueDateChanges = new HashSet<MPayAmortDueDateChange>();
            this.MPayInterests = new HashSet<MPayInterest>();
            this.OpenEndInterestRates = new HashSet<OpenEndInterestRate>();
            this.PaydayLoans = new HashSet<PaydayLoan>();
            this.PaydayLoanApprovals = new HashSet<PaydayLoanApproval>();
            this.RbcEFundBatchDetails = new HashSet<RbcEFundBatchDetail>();
            this.RbcEFundSecurities = new HashSet<RbcEFundSecurity>();
            this.RIAgingHistories = new HashSet<RIAgingHistory>();
            this.RiccAutoRolls = new HashSet<RiccAutoRoll>();
            this.RiccAutoRolls1 = new HashSet<RiccAutoRoll>();
            this.RolloverRequests = new HashSet<RolloverRequest>();
            this.SignatureLoanApprovals = new HashSet<SignatureLoanApproval>();
            this.SMSInbounds = new HashSet<SMSInbound>();
            this.SMSOutbounds = new HashSet<SMSOutbound>();
            this.SPayInterests = new HashSet<SPayInterest>();
            this.SPayLoans = new HashSet<SPayLoan>();
            this.SPaySchedRollovers = new HashSet<SPaySchedRollover>();
            this.VaultMgrAuthorizationDetails = new HashSet<VaultMgrAuthorizationDetail>();
            this.VehicleHistories = new HashSet<VehicleHistory>();
            this.VisitorEmails = new HashSet<VisitorEmail>();
            this.WebBlobLoanXrefs = new HashSet<WebBlobLoanXref>();
            this.WebCallQueues = new HashSet<WebCallQueue>();
            this.WebCallWorkQueues = new HashSet<WebCallWorkQueue>();
            this.WebErrorLogs = new HashSet<WebErrorLog>();
            this.WebLeads = new HashSet<WebLead>();
            this.WebLoanCreditFrauds = new HashSet<WebLoanCreditFraud>();
        }
    
        public int LOAN_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public bool COURTESY_CALL { get; set; }
        public Nullable<int> ISSUER_KEY { get; set; }
        public string CHECK_NO { get; set; }
        public bool DIRECT_DEPOSIT { get; set; }
        public string LOAN_TYPE { get; set; }
        public string ORIG_CODE { get; set; }
        public Nullable<int> ORIG_LOAN_KEY { get; set; }
        public Nullable<int> PAID_LOAN_KEY { get; set; }
        public Nullable<int> PAYMENT_PLAN_KEY { get; set; }
        public short ROLLOVER_NUM { get; set; }
        public string LOAN_STATUS { get; set; }
        public decimal LOAN_BALANCE { get; set; }
        public decimal LOAN_AMT { get; set; }
        public decimal CASH_AMT { get; set; }
        public decimal PRINC_AMT { get; set; }
        public decimal RATE_PCT { get; set; }
        public decimal DISC_AMT { get; set; }
        public decimal REBATE_AMT { get; set; }
        public decimal GRACE_AMT { get; set; }
        public decimal FEE_AMT { get; set; }
        public decimal TRANS_FEE_AMT { get; set; }
        public decimal LIEN_FEE_AMT { get; set; }
        public bool CHARGE_TRANS_FEE { get; set; }
        public bool CHARGE_LIEN_FEE { get; set; }
        public decimal TOT_FEE_AMT { get; set; }
        public System.DateTime ORIG_DUE_DATE { get; set; }
        public System.DateTime ADJUSTED_DUE_DATE { get; set; }
        public bool DEFAULTED { get; set; }
        public Nullable<System.DateTime> DEFAULT_DATE { get; set; }
        public bool REVERSED { get; set; }
        public Nullable<System.DateTime> REVERSED_DATE { get; set; }
        public Nullable<decimal> ORIG_APR { get; set; }
        public Nullable<int> DRAWERZ_KEY { get; set; }
        public System.DateTime LOAN_STATUS_DATE { get; set; }
        public bool JOINT_LOAN { get; set; }
        public string PRINT_LANGUAGE { get; set; }
        public System.DateTime CALC_DUE_DATE { get; set; }
        public Nullable<int> DWDOCID { get; set; }
        public bool DOCLOST { get; set; }
        public string DW_LOAN_NO { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string DISPLAY_CHECK_NO { get; set; }
        public decimal PENDING_SCHED_ACH_AMT { get; set; }
        public Nullable<System.DateTime> PENDING_SCHED_ACH_SENT { get; set; }
        public decimal PENDING_COLL_ACH_AMT { get; set; }
        public Nullable<System.DateTime> PENDING_COLL_ACH_SENT { get; set; }
        public Nullable<byte> DEPOSIT_ORDER { get; set; }
        public Nullable<byte> DEPOSIT_STATUS { get; set; }
        public System.DateTime LOAN_DATE { get; set; }
        public byte FUNDING_METHOD { get; set; }
        public Nullable<int> CREDIT_CARD_KEY { get; set; }
        public Nullable<bool> IS_MULTI_CHECK { get; set; }
        public Nullable<int> LOAN_PRODUCT_KEY { get; set; }
        public Nullable<bool> IS_GAIL_LOAN { get; set; }
        public bool EXCLUDE_FROM_CAP { get; set; }
        public bool IS_ESIGN { get; set; }
        public Nullable<System.DateTime> CAPS_CHANGE_DATE { get; set; }
        public decimal FASTER_PAYMENTS_FEE { get; set; }
        public byte ESIGN_DOC_METHOD { get; set; }
        public decimal STANDARD_RATE_PCT { get; set; }
        public byte LOAN_RATE_SOURCE { get; set; }
        public Nullable<short> CREDITED_LOCATION { get; set; }
        public decimal TILA_APR { get; set; }
        public decimal TILA_FINANCE_CHARGE { get; set; }
        public decimal TILA_AMOUNT_FINANCED { get; set; }
        public decimal TILA_TOTAL_PAYMENTS { get; set; }
        public bool INTEREST_AND_FEES_CAP_REACHED { get; set; }
        public Nullable<System.DateTime> INTEREST_AND_FEES_CAP_REACHED_DATE { get; set; }
        public Nullable<System.DateTime> WITHDRAW_DATE { get; set; }
        public Nullable<System.DateTime> WITHDRAW_ADJUSTED_DUE_DATE { get; set; }
        public int LOAN_PRODUCT_CONFIG_KEY { get; set; }
        public int LOAN_PRODUCT_TILA_KEY { get; set; }
        public decimal PENDING_PMT_AMT { get; set; }
        public Nullable<System.DateTime> PENDING_PMT_DATE { get; set; }
        public decimal PENDING_PMT_PRINC { get; set; }
        public decimal PENDING_PMT_INTEREST_CAP { get; set; }
        public decimal PENDING_PMT_CAB_INTEREST_CAP { get; set; }
        public decimal PENDING_PMT_FEES { get; set; }
        public decimal INSURANCE_FEE_AMT { get; set; }
        public Nullable<int> CANCEL_INSURANCE_TRANS_DETAIL_KEY { get; set; }
        public bool EXCLUDE_FROM_CAP_ACH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHProcessingQueue> ACHProcessingQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHQueue> ACHQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttorneyLoan> AttorneyLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessLoan> BusinessLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckAgain> CheckAgains { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourtesyPayout> CourtesyPayouts { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DDI> DDIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DDISendQueue> DDISendQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositBagDetail> DepositBagDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositChkDetail> DepositChkDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSigningStatu> DocumentSigningStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocuwareLoanLkup> DocuwareLoanLkups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcludeFromCapsHistory> ExcludeFromCapsHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetterOnDemand> FormLetterOnDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetterPrinted> FormLetterPrinteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceClaim> InsuranceClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePayment> InsurancePayments { get; set; }
        public virtual TransDetail TransDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanCCallChange> LoanCCallChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanCheck> LoanChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDocPrinted> LoanDocPrinteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanFunding> LoanFundings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanFundingMethodHistory> LoanFundingMethodHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanIncome> LoanIncomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanNote> LoanNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanOverride> LoanOverrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanPayment> LoanPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanService> LoanServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanWebReviewTemplateXref> LoanWebReviewTemplateXrefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPayLoan> MPayLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPayAmort> MPayAmorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPayAmortDueDateChange> MPayAmortDueDateChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPayInterest> MPayInterests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenEndInterestRate> OpenEndInterestRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaydayLoan> PaydayLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaydayLoanApproval> PaydayLoanApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RbcEFundBatchDetail> RbcEFundBatchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RbcEFundSecurity> RbcEFundSecurities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIAgingHistory> RIAgingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiccAutoRoll> RiccAutoRolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiccAutoRoll> RiccAutoRolls1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolloverRequest> RolloverRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignatureLoanApproval> SignatureLoanApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSInbound> SMSInbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSOutbound> SMSOutbounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPayInterest> SPayInterests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPayLoan> SPayLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPaySchedRollover> SPaySchedRollovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaultMgrAuthorizationDetail> VaultMgrAuthorizationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleHistory> VehicleHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorEmail> VisitorEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebBlobLoanXref> WebBlobLoanXrefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebCallQueue> WebCallQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebCallWorkQueue> WebCallWorkQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebErrorLog> WebErrorLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebLead> WebLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebLoanCreditFraud> WebLoanCreditFrauds { get; set; }
    }
}
