//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanPaymentSPay
    {
        public int LOAN_PAYMENT_SPAY_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
        public decimal COLL_FEE_DUE_PAID_AMT { get; set; }
        public decimal LEGAL_FEE_DUE_PAID_AMT { get; set; }
        public decimal LOAN_FEE_DUE_PAID_AMT { get; set; }
        public decimal INTEREST_DUE_PAID_AMT { get; set; }
        public decimal CAB_INTEREST_DUE_PAID_AMT { get; set; }
        public decimal PRINC_DUE_PAID_AMT { get; set; }
        public decimal CAB_LENDER_COLL_FEE_PAST_DUE_PAID_AMT { get; set; }
        public decimal NSF_FEE_DUE_PAID_AMT { get; set; }
        public decimal TRANS_FEE_DUE_PAID_AMT { get; set; }
        public decimal PENDING_SCHED_ACH_AMT { get; set; }
    
        public virtual LoanPayment LoanPayment { get; set; }
    }
}
