//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanOverride
    {
        public int LOAN_OVERRIDE_KEY { get; set; }
        public int LOAN_NOTE_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public string LOAN_OVERRIDE_TYPE { get; set; }
        public byte LOAN_OVERRIDE_REASON { get; set; }
        public decimal ORIG_VALUE { get; set; }
        public decimal OVERRIDE_VALUE { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual LoanNote LoanNote { get; set; }
    }
}
