//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanProductEnableNewLoanBackup
    {
        public int LOAN_PRODUCT_ENABLE_NEW_LOAN_KEY { get; set; }
        public int LOAN_PRODUCT_CONFIG_KEY { get; set; }
        public int LOAN_PRODUCT_TILA_KEY { get; set; }
        public short LOCATION { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public bool ENABLE_AGREEMENT_NUMBER { get; set; }
        public int NEXT_AGREEMENT_NUMBER { get; set; }
        public bool LEGACY_IS_ENABLED { get; set; }
        public bool LEGACY_IS_EASYPAY_ENABLED { get; set; }
        public bool LEGACY_IS_BUSINESS_LOAN_ENABLED { get; set; }
        public bool LEGACY_IS_EXPRESS_ENABLED { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<short> LIEN_ADDRESS_LOCATION { get; set; }
    }
}
