//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationConverted
    {
        public int LOCATION_CONVERTED_KEY { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public int LOCATION { get; set; }
        public bool RUN_OPEN_LOAN_CHECK { get; set; }
    }
}
