//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetroIIBaseSegment
    {
        public int METROII_BASE_SEGMENT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string CORRECTION_INDICATOR { get; set; }
        public string IDENTIFICATION_NUMBER { get; set; }
        public string CYCLE_IDENTIFIER { get; set; }
        public Nullable<int> CONSUMER_ACCOUNT_NUMBER { get; set; }
        public string PORTFOLIO_TYPE { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public System.DateTime DATE_OPENED { get; set; }
        public int CREDIT_LIMIT { get; set; }
        public int ORIGINAL_LOAN_AMOUNT { get; set; }
        public short TERMS_DURATION { get; set; }
        public string TERMS_FREQUENCY { get; set; }
        public int SCHEDULE_PAYMENT_AMOUNT { get; set; }
        public int ACTUAL_PAYMENT_AMOUNT { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string PAYMENT_RATING { get; set; }
        public string PAYMENT_HISTORY_PROFILE { get; set; }
        public string SPECIAL_COMMENT { get; set; }
        public string COMPLIANCE_CONDITION_CODE { get; set; }
        public int CURRENT_BALANCE { get; set; }
        public int AMOUNT_PAST_DUE { get; set; }
        public int ORIGINAL_CHARGE_OFF_AMOUNT { get; set; }
        public Nullable<System.DateTime> DATE_FIRST_DELINQUENCY { get; set; }
        public Nullable<System.DateTime> DATE_CLOSED { get; set; }
        public Nullable<System.DateTime> DATE_LAST_PAYMENT { get; set; }
        public string CONSUMER_TRANSACTION_TYPE { get; set; }
        public string SURNAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string GENERATION_CODE { get; set; }
        public string SOCIAL_INSURANCE_NUMBER { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string TELEPHONE_NUMBER { get; set; }
        public string ASSOCIATION_CODE { get; set; }
        public string CONSUMER_INFORMATION_INDICATOR { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string CITY { get; set; }
        public string PROVINCE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string ADDRESS_INDICATOR { get; set; }
        public string RESIDENCE_CODE { get; set; }
        public int CUSTOMER_KEY { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
