//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPayRecalcLoanPaymentAdj
    {
        public int MPAY_RECALC_LOAN_PAYMENT_ADJ_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public string ENTERED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<byte> TRANSCODE { get; set; }
        public byte C_TRANSCODE { get; set; }
        public bool ADD_TO_COLL { get; set; }
        public bool C_ADD_TO_COLL { get; set; }
        public bool REM_FROM_COLL { get; set; }
        public bool C_REM_FROM_COLL { get; set; }
        public decimal PENDING_SCHED_ACH_AMT { get; set; }
        public decimal C_PENDING_SCHED_ACH_AMT { get; set; }
        public decimal COLL_FEE_PAST_DUE_PAID { get; set; }
        public decimal C_COLL_FEE_PAST_DUE_PAID { get; set; }
        public decimal LEGAL_FEE_PAST_DUE_PAID { get; set; }
        public decimal C_LEGAL_FEE_PAST_DUE_PAID { get; set; }
        public decimal LOAN_FEE_DUE_PAID { get; set; }
        public decimal C_LOAN_FEE_DUE_PAID { get; set; }
        public decimal TRANS_FEE_DUE_PAID { get; set; }
        public decimal C_TRANS_FEE_DUE_PAID { get; set; }
        public decimal INTEREST_DUE_PAID { get; set; }
        public decimal C_INTEREST_DUE_PAID { get; set; }
        public decimal PRINC_DUE_PAID { get; set; }
        public decimal C_PRINC_DUE_PAID { get; set; }
        public decimal PAYMENT_DUE_PAID { get; set; }
        public decimal C_PAYMENT_DUE_PAID { get; set; }
        public decimal PAYMENT_PAST_DUE_PAID { get; set; }
        public decimal C_PAYMENT_PAST_DUE_PAID { get; set; }
        public decimal CAB_COLL_FEE_PAST_DUE_PAID { get; set; }
        public decimal C_CAB_COLL_FEE_PAST_DUE_PAID { get; set; }
        public decimal CAB_INTEREST_DUE_PAID { get; set; }
        public decimal C_CAB_INTEREST_DUE_PAID { get; set; }
        public decimal NSF_FEE_PAST_DUE_PAID { get; set; }
        public decimal C_NSF_FEE_PAST_DUE_PAID { get; set; }
        public Nullable<System.DateTime> LPDD_ORIG_DUE_DATE { get; set; }
        public Nullable<System.DateTime> C_LPDD_ORIG_DUE_DATE { get; set; }
        public Nullable<System.DateTime> LPDD_ADJUSTED_DUE_DATE { get; set; }
        public Nullable<System.DateTime> C_LPDD_ADJUSTED_DUE_DATE { get; set; }
        public decimal LPDD_PAST_DUE_AMT { get; set; }
        public decimal C_LPDD_PAST_DUE_AMT { get; set; }
        public decimal LPDD_COLLECTIONS_AMT { get; set; }
        public decimal C_LPDD_COLLECTIONS_AMT { get; set; }
        public decimal LPDD_PENDING_ACH_AMT { get; set; }
        public decimal C_LPDD_PENDING_ACH_AMT { get; set; }
        public decimal INSURANCE_DUE_PAID { get; set; }
        public decimal C_INSURANCE_DUE_PAID { get; set; }
    }
}
