//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NobleConfiguration
    {
        public int NOBLE_CONFIG_KEY { get; set; }
        public string COLLECTIONS_EXCLUSION_TABLE_NAME { get; set; }
        public string COLLECTIONS_TABLE_NAME { get; set; }
        public string COURTESY_TABLE_NAME { get; set; }
        public string INTERNET_LENDING_TABLE_NAME { get; set; }
        public Nullable<int> INTERNET_LENDING_LIST_ID { get; set; }
        public string TABLE_NAME_PREFIX { get; set; }
        public byte TIME_OFFSET_FROM_NOBLE { get; set; }
        public string TELLER_ID { get; set; }
    }
}
