//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEndVaultTroubleshooting
    {
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
        public short LOCATION { get; set; }
        public decimal INV_AMT { get; set; }
        public decimal VLT_AMT { get; set; }
        public Nullable<decimal> AMT_DIFF { get; set; }
        public Nullable<int> INV_CNT { get; set; }
        public short VLT_CNT { get; set; }
        public Nullable<int> CNT_DIFF { get; set; }
        public string LOAN_TYPE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public Nullable<int> LIEN_TYPE { get; set; }
    }
}
