//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenEndLoanStatementSnapshot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenEndLoanStatementSnapshot()
        {
            this.OpenEndLoanStatements = new HashSet<OpenEndLoanStatement>();
            this.OpenEndRecalcStatementSnapshots = new HashSet<OpenEndRecalcStatementSnapshot>();
        }
    
        public int OPEN_END_LOAN_STATEMENT_SNAPSHOT_KEY { get; set; }
        public decimal PAST_DUE_TRANS_FEE_BAL { get; set; }
        public decimal PAST_DUE_LIEN_FEE_BAL { get; set; }
        public decimal PAST_DUE_CAB_FEE_BAL { get; set; }
        public decimal PAST_DUE_COLL_FEE_BAL { get; set; }
        public decimal PAST_DUE_CAB_LENDER_COLL_FEE_BAL { get; set; }
        public decimal PAST_DUE_INTEREST_BAL { get; set; }
        public decimal PAST_DUE_CAB_LENDER_INTEREST_BAL { get; set; }
        public decimal PAST_DUE_PRINC_BAL { get; set; }
        public decimal CURR_DUE_TRANS_FEE_BAL { get; set; }
        public decimal CURR_DUE_LIEN_FEE_BAL { get; set; }
        public decimal CURR_DUE_CAB_FEE_BAL { get; set; }
        public decimal CURR_DUE_INTEREST_BAL { get; set; }
        public decimal CURR_DUE_CAB_LENDER_INTEREST_BAL { get; set; }
        public decimal CURR_DUE_PRINC_BAL { get; set; }
        public decimal NEXT_DUE_TRANS_FEE_BAL { get; set; }
        public decimal NEXT_DUE_LIEN_FEE_BAL { get; set; }
        public decimal NEXT_DUE_CAB_FEE_BAL { get; set; }
        public decimal NEXT_DUE_INTEREST_BAL { get; set; }
        public decimal NEXT_DUE_CAB_LENDER_INTEREST_BAL { get; set; }
        public decimal NEXT_DUE_PRINC_BAL { get; set; }
        public decimal NOT_DUE_TRANS_FEE_BAL { get; set; }
        public decimal NOT_DUE_LIEN_FEE_BAL { get; set; }
        public decimal NOT_DUE_CAB_FEE_BAL { get; set; }
        public decimal NOT_DUE_INTEREST_BAL { get; set; }
        public decimal NOT_DUE_CAB_LENDER_INTEREST_BAL { get; set; }
        public decimal NOT_DUE_PRINC_BAL { get; set; }
        public Nullable<decimal> TRANS_FEE_BAL { get; set; }
        public Nullable<decimal> LIEN_FEE_BAL { get; set; }
        public Nullable<decimal> CAB_FEE_BAL { get; set; }
        public Nullable<decimal> CAB_LENDER_INTEREST_FEE_BAL { get; set; }
        public Nullable<decimal> INTEREST_BAL { get; set; }
        public Nullable<decimal> PRINC_BAL { get; set; }
        public Nullable<decimal> PAST_DUE_BAL { get; set; }
        public Nullable<decimal> CURR_DUE_BAL { get; set; }
        public Nullable<decimal> NEXT_DUE_BAL { get; set; }
        public Nullable<decimal> NOT_DUE_BAL { get; set; }
        public Nullable<System.DateTime> NEXT_STATEMENT_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_DUE_DATE { get; set; }
        public decimal PENDING_SCHED_ACH_AMT { get; set; }
        public Nullable<System.DateTime> PENDING_SCHED_ACH_SENT { get; set; }
        public decimal PENDING_COLL_ACH_AMT { get; set; }
        public Nullable<System.DateTime> PENDING_COLL_ACH_SENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenEndLoanStatement> OpenEndLoanStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenEndRecalcStatementSnapshot> OpenEndRecalcStatementSnapshots { get; set; }
    }
}
