//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptInOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OptInOut()
        {
            this.OptInOutEdits = new HashSet<OptInOutEdit>();
        }
    
        public int OPTINOUT_KEY { get; set; }
        public int VISITOR_KEY { get; set; }
        public bool OPTOUT_TRANSACTION_COMMUNICATION { get; set; }
        public bool OPTOUT_THIRD_PARTY_SHARE { get; set; }
        public bool OPTOUT_EMAIL { get; set; }
        public bool OPTOUT_SMS { get; set; }
        public bool OPTOUT_VOICEBLAST { get; set; }
        public bool OPTOUT_CALL_CAMPAIGN { get; set; }
        public bool OPTOUT_DIRECT_MAIL { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public bool OPTOUT_CR_SMS { get; set; }
        public bool OPTOUT_OPTPLUS_SMS { get; set; }
        public bool OPTOUT_OPTPLUS_VOICEBLAST { get; set; }
        public bool OPTOUT_OPTPLUS_CALL_CAMPAIGN { get; set; }
        public bool OPTOUT_OPTPLUS_EMAIL { get; set; }
        public bool OPTOUT_OPTPLUS_DIRECT_MAIL { get; set; }
        public string SMS_PHONE { get; set; }
        public string VOICEBLAST_PHONE { get; set; }
        public string CALL_CAMPAIGN_PHONE { get; set; }
        public string OPTPLUS_SMS_PHONE { get; set; }
        public string OPTPLUS_VOICEBLAST_PHONE { get; set; }
        public string OPTPLUS_CALL_CAMPAIGN_PHONE { get; set; }
        public bool OPTOUT_PRIVACY_CONSENT { get; set; }
    
        public virtual Visitor Visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptInOutEdit> OptInOutEdits { get; set; }
    }
}
