//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptPlusRDFODTransition
    {
        public string PRN { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public Nullable<short> TRANS_CODE { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public int OD_TRANSITION_KEY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
