//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptPlusExportTransCode
    {
        public string TRANS_CODE { get; set; }
        public string TRECS_CODE { get; set; }
        public string D2JE1D { get; set; }
        public string D2JE1C { get; set; }
        public string D2JE2D { get; set; }
        public string D2JE2C { get; set; }
    }
}
