//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptPlusRDFAuthorizedTransaction
    {
        public string UNIQUE_PROGRAM_ID { get; set; }
        public string GALILEO_ACCOUNT_ID { get; set; }
        public string CARD_ID { get; set; }
        public string TRANSACTION_DATE { get; set; }
        public string TRANSACTION_CURRENCY_CODE { get; set; }
        public string ADDRESS_VERIFICATION_RESPONSE { get; set; }
        public string AUTHORIZATION_RESPONSE { get; set; }
        public string AUTHORIZATION_AMOUNT { get; set; }
        public string AUTHORIZATION_AMOUNT_SIGN { get; set; }
        public string AUTHORIZATION_CODE { get; set; }
        public string NETWORK_CODE { get; set; }
        public string MERCHANT_NUMBER { get; set; }
        public string MERCHANT_NAME { get; set; }
        public string MERCHANT_CATEGORY_CODE { get; set; }
        public string TRANSACTION_CODE { get; set; }
        public string MERCHANT_COUNTRY_CODE { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public int AUTHORIZED_TRANSACTIONS_KEY { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
