//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptPlusBinService
    {
        public int OPT_PLUS_BIN_SERVICE_KEY { get; set; }
        public int SERVICE_DETAIL_KEY { get; set; }
        public int OPT_PLUS_BIN_KEY { get; set; }
    }
}
