//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptPlusEmployment
    {
        public int OPTPLUS_EMPLOYMENT_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public string WEBSITE { get; set; }
        public string HR_CONTACT { get; set; }
        public string HR_PHONE { get; set; }
        public string HR_FAX { get; set; }
        public string ADDR_NUM { get; set; }
        public string ADDR_PRE_DIR { get; set; }
        public string ADDR_STREET { get; set; }
        public string ADDR_SUFFIX { get; set; }
        public string ADDR_POST_DIR { get; set; }
        public string ADDR_SUITE { get; set; }
        public string ADDR_SUITE_NUM { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public string ADDRESS_FORMAT { get; set; }
        public string FLAT_NUM { get; set; }
        public string BUILDING_NUM { get; set; }
        public string BUILDING_NAME { get; set; }
        public string ADDRESS_LINE { get; set; }
        public string ADDRESS_CSZ { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
