//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYROLL1
    {
        public string chk_type { get; set; }
        public decimal PRICE { get; set; }
        public decimal FEE { get; set; }
        public decimal RATE { get; set; }
        public short Location { get; set; }
        public int Payroll1_key { get; set; }
    }
}
