//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneSkillsCall
    {
        public int PHONE_SKILLS_CALL_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public short DISTRICT_KEY { get; set; }
        public short LOCATION { get; set; }
        public string STORE_MANAGER { get; set; }
        public string STORE_TELLER { get; set; }
        public string UNKNOWN_TELLER { get; set; }
        public string COMMENTS { get; set; }
        public bool DELETED { get; set; }
        public string DELETED_DATE { get; set; }
        public string DELETED_BY { get; set; }
        public int PHONE_SKILLS_GRADE_KEY { get; set; }
        public int PHONE_SKILLS_SEQUENCE_KEY { get; set; }
        public int REASON_KEY { get; set; }
        public int SUBREASON1_KEY { get; set; }
        public int SUBREASON2_KEY { get; set; }
        public byte CALL_MONTH { get; set; }
        public short CALL_YEAR { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PhoneSkillsGrade PhoneSkillsGrade { get; set; }
        public virtual PhoneSkillsSequence PhoneSkillsSequence { get; set; }
    }
}
