//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidCardStopPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrepaidCardStopPayment()
        {
            this.PrepaidCardStopPaymentEdits = new HashSet<PrepaidCardStopPaymentEdit>();
        }
    
        public int PREPAID_CARD_STOP_PAYMENT_KEY { get; set; }
        public int CREDIT_CARD_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public string SOURCE_INSTITUTION { get; set; }
        public Nullable<decimal> STOP_PAYMENT_AMOUNT { get; set; }
        public int PREPAID_CARD_STOP_PAYMENT_REASON_KEY { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> CANCELLED_DATE { get; set; }
        public string CANCELLED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string OTHER_REASON_DESCRIBE { get; set; }
        public bool REPORTED_TO_VENDOR { get; set; }
        public Nullable<System.DateTime> REPORTED_TO_VENDOR_DATE { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual PrepaidCardStopPaymentReason PrepaidCardStopPaymentReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrepaidCardStopPaymentEdit> PrepaidCardStopPaymentEdits { get; set; }
    }
}
