//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessConfigInstanceGroup
    {
        public int PROCESS_CONFIG_INSTANCE_GROUP_KEY { get; set; }
        public int PROCESS_CONFIG_INSTANCE_KEY { get; set; }
        public int SECURITYGROUP_KEY { get; set; }
    
        public virtual ProcessConfigInstance ProcessConfigInstance { get; set; }
        public virtual SecurityGroup SecurityGroup { get; set; }
    }
}
