//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromiseToPay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromiseToPay()
        {
            this.PromiseToPayDetails = new HashSet<PromiseToPayDetail>();
        }
    
        public int PROMISE_TO_PAY_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int RISREPT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public byte PTP_PMTS { get; set; }
        public short PTP_LOCATION { get; set; }
        public string PTP_COURTESY_CALL { get; set; }
        public string APPROVED_BY { get; set; }
        public bool CANCELLED { get; set; }
        public bool WAIVE_FEE { get; set; }
        public Nullable<System.DateTime> CANCELLED_DATE { get; set; }
        public string CANCELLED_BY { get; set; }
        public Nullable<int> COLLECTION_ACTION_KEY { get; set; }
        public Nullable<System.DateTime> REVERSED_DATE { get; set; }
        public bool REVERSED { get; set; }
        public int PTP_CONFIG_KEY { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> CUSTOMER_DOCUMENT_KEY { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RIPTPPaymentPlanConfig RIPTPPaymentPlanConfig { get; set; }
        public virtual RISREPT RISREPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromiseToPayDetail> PromiseToPayDetails { get; set; }
    }
}
