//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromiseToPayTimeSlotConfig
    {
        public byte PTP_CC_TIME_SLOT { get; set; }
        public byte PTP_RUN_TIME { get; set; }
        public string PTP_TIMESLOT_DESC { get; set; }
    }
}
