//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RbcEFundBatchDetail
    {
        public int RBC_EFUND_BATCH_DETAIL_KEY { get; set; }
        public int RBC_EFUND_BATCH_KEY { get; set; }
        public int RBC_EFUND_RESPONSE_CODE_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int ISSUER_KEY { get; set; }
        public long BANK_ID { get; set; }
        public string ACCT_NO { get; set; }
        public string EMAIL { get; set; }
        public decimal AMOUNT { get; set; }
        public bool PROCESSED { get; set; }
        public bool FUNDED { get; set; }
        public bool VOIDED { get; set; }
        public Nullable<int> RBC_EFUND_BATCH_SUMMARY_KEY { get; set; }
        public string RESPONSE_TEXT { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Issuer Issuer { get; set; }
        public virtual Loan Loan { get; set; }
        public virtual RbcEFundBatch RbcEFundBatch { get; set; }
        public virtual RbcEFundResponseCode RbcEFundResponseCode { get; set; }
    }
}
