//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonForArrear
    {
        public int REASON_FOR_ARREARS_KEY { get; set; }
        public System.DateTime DATE_UPDATED { get; set; }
        public int UPDATED_TELLER_ID_KEY { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IS_ACTIVE { get; set; }
    
        public virtual TELLERID TELLERID { get; set; }
    }
}
