//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnCheckMatch
    {
        public int RETURN_CHECK_MATCH_KEY { get; set; }
        public int RETURN_CHECK_DETAIL_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public Nullable<int> CASHED_CHECK_KEY { get; set; }
    
        public virtual ReturnCheckDetail ReturnCheckDetail { get; set; }
    }
}
