//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnCheckDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnCheckDetail()
        {
            this.ReturnCheckMatches = new HashSet<ReturnCheckMatch>();
        }
    
        public int RETURN_CHECK_DETAIL_KEY { get; set; }
        public int RETURN_CHECK_FILE_KEY { get; set; }
        public string BANK_ID { get; set; }
        public string ACCT_NO { get; set; }
        public decimal CHARGEBACK_AMT { get; set; }
        public string CUSTOMER_NUMBER { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public int CURRENCY_KEY { get; set; }
        public System.DateTime ORIGINAL_DEPOSIT_DATE { get; set; }
        public string PARSED_LOCATION { get; set; }
        public string SEQUENCE_NUMBER { get; set; }
        public string RETURN_REASON_CODE { get; set; }
    
        public virtual ReturnCheckFile ReturnCheckFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnCheckMatch> ReturnCheckMatches { get; set; }
    }
}
