//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RI
    {
        public System.DateTime DATE { get; set; }
        public string TLR { get; set; }
        public short LOCATION { get; set; }
        public decimal AMOUNT { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> FOLLOWUP { get; set; }
        public Nullable<byte> PTYP { get; set; }
        public Nullable<System.DateTime> xtime { get; set; }
        public Nullable<System.DateTime> ztime { get; set; }
        public Nullable<System.DateTime> btime { get; set; }
        public int RIS_Id { get; set; }
        public Nullable<System.DateTime> BTIME2 { get; set; }
        public bool prepay { get; set; }
        public Nullable<int> dos_refno { get; set; }
        public Nullable<int> reverse_ris_id { get; set; }
        public int Ris_Audit_ID { get; set; }
        public int Ris_Task_ID { get; set; }
        public int risrept_key { get; set; }
        public string DOS_MIGRATED_ID { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
        public Nullable<short> GL_ACCT { get; set; }
    
        public virtual RISAUDIT RISAUDIT { get; set; }
        public virtual RISREPT RISREPT { get; set; }
        public virtual RisTask RisTask { get; set; }
    }
}
