//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RICCConfig
    {
        public int RICC_CONFIG_KEY { get; set; }
        public string AUDIT_CATEGORIES { get; set; }
        public string LOCATIONS { get; set; }
        public short AGE_FROM { get; set; }
        public short AGE_TO { get; set; }
        public bool INCLUDE_NETSPEND { get; set; }
        public bool INCLUDE_DEBIT { get; set; }
        public decimal BALANCE { get; set; }
        public byte NUMBER_THREADS { get; set; }
        public bool PROCESS_SPAY { get; set; }
        public bool PROCESS_MPAY { get; set; }
        public bool PROCESS_OEND { get; set; }
    }
}
