//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiccPayment
    {
        public int ID { get; set; }
        public int LOAN_KEY { get; set; }
        public decimal AMOUNT { get; set; }
        public int RICC_PAYMENTS_KEY { get; set; }
        public Nullable<int> OPTPLUS_CARD_DETAIL_KEY { get; set; }
    }
}
