//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiccHold
    {
        public int RISREPT_KEY { get; set; }
        public string REFERENCE { get; set; }
        public int CASHED_CHECK_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public short LOCATION { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<int> RIS_AUDIT_ID { get; set; }
        public int CREDITCARD_KEY { get; set; }
        public string CARDNUM { get; set; }
        public string NAMEONCARD { get; set; }
        public byte EXPMONTH { get; set; }
        public int EXPYEAR { get; set; }
        public bool PINLESS_ELIGIBLE { get; set; }
        public string TELLER { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public string LOAN_TYPE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public decimal RI_BALANCE { get; set; }
        public int riage { get; set; }
        public int DUPE { get; set; }
        public int VOID { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public string DEPOSIT_METHOD { get; set; }
        public string CVV { get; set; }
        public string BILLING_ADDRESS { get; set; }
        public string BILLING_CITY { get; set; }
        public string BILLING_STATE { get; set; }
        public string BILLING_ZIPCODE { get; set; }
        public bool EXPIRED { get; set; }
        public bool CVVINVALID { get; set; }
        public int ISSUER_KEY { get; set; }
        public int LIEN_HOLDER_KEY { get; set; }
        public string TOKEN { get; set; }
        public byte CARD_BRAND { get; set; }
        public byte CARD_TYPE { get; set; }
        public short ROLLOVER_NUM { get; set; }
        public decimal FEE_AMT { get; set; }
        public decimal SURCHG { get; set; }
        public int AUTO_ROLL { get; set; }
        public bool SELECTED { get; set; }
        public bool PROCESSED { get; set; }
        public bool APPROVED { get; set; }
        public string APP_ERR_CODE { get; set; }
        public int PTP_HEADER_KEY { get; set; }
        public int PTP_DETAIL_KEY { get; set; }
        public int CCARD_TRANS_KEY { get; set; }
        public bool POSTED { get; set; }
        public int id { get; set; }
        public Nullable<int> OPTPLUS_CARD_DETAIL_KEY { get; set; }
    }
}
