//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISAUDIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISAUDIT()
        {
            this.FormLetters = new HashSet<FormLetter>();
            this.RIS = new HashSet<RI>();
            this.RISREPTs = new HashSet<RISREPT>();
            this.SkipTraceConfig_RisAudit = new HashSet<SkipTraceConfig_RisAudit>();
            this.SkipTraceStep_AuditCategory = new HashSet<SkipTraceStep_AuditCategory>();
            this.FormLetters1 = new HashSet<FormLetter>();
        }
    
        public string AUDIT { get; set; }
        public string DESC { get; set; }
        public string SHORT { get; set; }
        public int RIS_Audit_Id { get; set; }
        public Nullable<bool> Displayed { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public bool IS_IN_LEGAL_STATUS { get; set; }
        public int RIS_AUDIT_KEY { get; set; }
        public bool DIALER_EXCLUDE { get; set; }
        public bool SUSPEND_INTEREST { get; set; }
        public bool REPOSSESSION { get; set; }
        public bool BLOCK_EMAILS { get; set; }
        public bool IS_ELIGIBLE_FOR_REPO { get; set; }
        public bool BLOCK_STATEMENTS { get; set; }
        public Nullable<bool> IS_PTP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetter> FormLetters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RI> RIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISREPT> RISREPTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipTraceConfig_RisAudit> SkipTraceConfig_RisAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipTraceStep_AuditCategory> SkipTraceStep_AuditCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormLetter> FormLetters1 { get; set; }
    }
}
