//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RitaPwd
    {
        public string CLIENT_ID { get; set; }
        public string USER_ID { get; set; }
        public int USER_PW_SEQ { get; set; }
        public string USER_STAT { get; set; }
        public string USER_PW { get; set; }
    }
}
