//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleDef()
        {
            this.LoanDepositOrderHistories = new HashSet<LoanDepositOrderHistory>();
            this.RuleDefEdits = new HashSet<RuleDefEdit>();
            this.RuleDefSetDetails = new HashSet<RuleDefSetDetail>();
        }
    
        public int RULE_DEF_KEY { get; set; }
        public int RULE_DEF_TYPE_KEY { get; set; }
        public string NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTENT { get; set; }
        public bool IS_DELETED { get; set; }
        public Nullable<System.DateTime> DATE_DELETED { get; set; }
        public string DELETED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDepositOrderHistory> LoanDepositOrderHistories { get; set; }
        public virtual RuleDefType RuleDefType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleDefEdit> RuleDefEdits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleDefSetDetail> RuleDefSetDetails { get; set; }
    }
}
