//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannedDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScannedDocument()
        {
            this.ScannedDocumentOverrides = new HashSet<ScannedDocumentOverride>();
        }
    
        public int SCANNED_DOCUMENT_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> LOAN_DOC_KEY { get; set; }
        public Nullable<int> DOCUMENT_SYSTEM_KEY { get; set; }
        public Nullable<System.DateTime> DOCUMENT_SYSTEM_SCAN_DATE { get; set; }
    
        public virtual LoanDoc LoanDoc { get; set; }
        public virtual TransDetail TransDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScannedDocumentOverride> ScannedDocumentOverrides { get; set; }
    }
}
