//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannedDocumentOverride
    {
        public int SCANNED_DOCUMENT_OVERRIDE_KEY { get; set; }
        public int SCANNED_DOCUMENT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public string CODE { get; set; }
    
        public virtual ScannedDocument ScannedDocument { get; set; }
    }
}
