//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDNMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SDNMain()
        {
            this.SDNAdds = new HashSet<SDNAdd>();
            this.SDNAlts = new HashSet<SDNAlt>();
        }
    
        public int ENT_NUM { get; set; }
        public string SDN_NAME { get; set; }
        public string SDN_TYPE { get; set; }
        public string PROGRAM { get; set; }
        public string TITLE { get; set; }
        public string REMARKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDNAdd> SDNAdds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDNAlt> SDNAlts { get; set; }
    }
}
