//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityAnswer
    {
        public int SECURITY_ANSWER_KEY { get; set; }
        public string TELLER { get; set; }
        public int SECURITY_QUESTION_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ANSWER { get; set; }
    
        public virtual SecurityQuestion SecurityQuestion { get; set; }
    }
}
