//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTransDetail
    {
        public int SERVICE_TRANS_DETAIL_KEY { get; set; }
        public int SERVICE_TRANS_KEY { get; set; }
        public string PERSON_RECEIVED { get; set; }
        public string COUNTRY_TO { get; set; }
        public string OCCUPATION { get; set; }
        public string PURPOSE { get; set; }
        public string BILLER_NAME { get; set; }
        public string BILLPAY_CODE { get; set; }
        public string BILLPAY_ACCOUNT_NUM { get; set; }
        public bool EXPORTED { get; set; }
        public Nullable<bool> IS_DOMESTIC { get; set; }
        public string THIRD_PARTY_DETAILS { get; set; }
        public Nullable<byte> VENDOR_ID { get; set; }
        public string WIRE_TRANSFER_RECEIPT { get; set; }
    
        public virtual ServiceTran ServiceTran { get; set; }
    }
}
