//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSubItem
    {
        public int SERVICE_SUBITEM_KEY { get; set; }
        public int SERVICE_MASTER_KEY_REQUISITE { get; set; }
        public int SERVICE_MASTER_KEY_SUBITEM { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual ServiceMaster ServiceMaster { get; set; }
        public virtual ServiceMaster ServiceMaster1 { get; set; }
    }
}
