//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkipTraceStep_Location
    {
        public int SKIP_TRACE_STEP_KEY { get; set; }
        public Nullable<short> LOCATION { get; set; }
        public int SKIP_TRACE_STEP_LOCATION_KEY { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SkipTraceStep SkipTraceStep { get; set; }
    }
}
