//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkipTraceConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkipTraceConfig()
        {
            this.SkipTraceSteps = new HashSet<SkipTraceStep>();
            this.SkipTraceThreads = new HashSet<SkipTraceThread>();
            this.SkipTraceVendors = new HashSet<SkipTraceVendor>();
        }
    
        public int SKIP_TRACE_CONFIG_KEY { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public short MAX_CYCLES_PER_CUSTOMER { get; set; }
        public short DAYS_BETWEEN_CYCLES { get; set; }
        public int WATCH_LIST_VENDOR_KEY { get; set; }
        public decimal BALANCE_RANGE_FROM { get; set; }
        public decimal BALANCE_RANGE_TO { get; set; }
    
        public virtual SkipTraceConfig_RisAudit SkipTraceConfig_RisAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipTraceStep> SkipTraceSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipTraceThread> SkipTraceThreads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipTraceVendor> SkipTraceVendors { get; set; }
    }
}
