//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkipTraceConfig_RisAudit
    {
        public int SKIP_TRACE_CONFIG_KEY { get; set; }
        public Nullable<int> RIS_AUDIT_KEY { get; set; }
    
        public virtual RISAUDIT RISAUDIT { get; set; }
        public virtual SkipTraceConfig SkipTraceConfig { get; set; }
    }
}
