//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSInbound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMSInbound()
        {
            this.RolloverRequests = new HashSet<RolloverRequest>();
        }
    
        public int SMS_INBOUND_KEY { get; set; }
        public string SMS_SOURCE { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string CALLING_FROM_NUMBER { get; set; }
        public string CALLING_TO_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<int> SMS_OUTBOUND_KEY { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public Nullable<int> VISITOR_KEY { get; set; }
        public Nullable<int> WEB_CALL_QUEUE_KEY { get; set; }
        public Nullable<System.DateTime> LOCKED_DATE { get; set; }
        public Nullable<System.Guid> LOCKED_GUID { get; set; }
        public Nullable<bool> CLOSED { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolloverRequest> RolloverRequests { get; set; }
        public virtual SMSOutbound SMSOutbound { get; set; }
        public virtual Visitor Visitor { get; set; }
        public virtual WebCallQueue WebCallQueue { get; set; }
    }
}
