//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSOutbound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMSOutbound()
        {
            this.SMSFailedSends = new HashSet<SMSFailedSend>();
            this.SMSInbounds = new HashSet<SMSInbound>();
            this.SMSResponses = new HashSet<SMSResponse>();
        }
    
        public int SMS_OUTBOUND_KEY { get; set; }
        public Nullable<System.DateTime> INITIATED_DATE { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public Nullable<System.DateTime> LOCKED_DATE { get; set; }
        public Nullable<System.Guid> LOCKED_GUID { get; set; }
        public string MESSAGE { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public Nullable<int> SMS_SENDER_KEY { get; set; }
        public Nullable<int> VISITOR_KEY { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSFailedSend> SMSFailedSends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSInbound> SMSInbounds { get; set; }
        public virtual SMSSender SMSSender { get; set; }
        public virtual Visitor Visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSResponse> SMSResponses { get; set; }
    }
}
