//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPaySchedRollover
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPaySchedRollover()
        {
            this.SPaySchedRolloverDetails = new HashSet<SPaySchedRolloverDetail>();
        }
    
        public int SPAY_SCHED_ROLLOVER_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public int ZERO_REC_LOAN_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
        public byte NUM_ROLLOVERS { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Loan Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPaySchedRolloverDetail> SPaySchedRolloverDetails { get; set; }
    }
}
