//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPaySchedRolloverDetail
    {
        public int SPAY_SCHED_ROLLOVER_DETAIL_KEY { get; set; }
        public int SPAY_SCHED_ROLLOVER_KEY { get; set; }
        public System.DateTime ROLLOVER_DATE { get; set; }
        public decimal OPT_BUYDOWN_AMT { get; set; }
        public byte ROLLOVER_NUM { get; set; }
        public decimal LOAN_AMT { get; set; }
        public decimal PRINC_AMT { get; set; }
        public decimal LOAN_ATR { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public Nullable<int> ACH_HISTORY_KEY { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> CANCEL_LOAN_PAYMENT_KEY { get; set; }
        public Nullable<int> VOID_LOAN_PAYMENT_KEY { get; set; }
        public Nullable<int> SCHED_LOAN_PAYMENT_KEY { get; set; }
    
        public virtual SPaySchedRollover SPaySchedRollover { get; set; }
    }
}
