//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialMessageLoanProduct
    {
        public int SPECIAL_MESSAGE_LOAN_PRODUCT_KEY { get; set; }
        public int SPECIAL_MESSAGE_KEY { get; set; }
        public int LOAN_PRODUCT_KEY { get; set; }
    
        public virtual LoanProduct LoanProduct { get; set; }
        public virtual SpecialMessage SpecialMessage { get; set; }
    }
}
