//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Windows
    {
        public int Store_Windows_Key { get; set; }
        public short Location { get; set; }
        public string Computer_Name { get; set; }
        public string Citrix_Name { get; set; }
        public string REPORT { get; set; }
        public string RECEIPT { get; set; }
        public string AGREEMENT { get; set; }
        public string DOTMATRIX { get; set; }
        public Nullable<short> MONEY_ORDERS { get; set; }
        public bool SHARED_PRINTERS { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE_SET { get; set; }
        public short MO_FORMS_REMAINING { get; set; }
        public string WINDOWS_VERSION { get; set; }
        public string TELLER_KEYBOARD { get; set; }
        public string CUSTOMER_KEYBOARD { get; set; }
        public string MONEY_ORDER_COM_PORT { get; set; }
    }
}
