//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysobjects_view
    {
        public string name { get; set; }
        public int id { get; set; }
        public string xtype { get; set; }
        public Nullable<short> uid { get; set; }
        public Nullable<short> info { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> base_schema_ver { get; set; }
        public Nullable<int> replinfo { get; set; }
        public int parent_obj { get; set; }
        public System.DateTime crdate { get; set; }
        public Nullable<short> ftcatid { get; set; }
        public Nullable<int> schema_ver { get; set; }
        public Nullable<int> stats_schema_ver { get; set; }
        public string type { get; set; }
        public Nullable<short> userstat { get; set; }
        public Nullable<short> sysstat { get; set; }
        public Nullable<short> indexdel { get; set; }
        public System.DateTime refdate { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> deltrig { get; set; }
        public Nullable<int> instrig { get; set; }
        public Nullable<int> updtrig { get; set; }
        public Nullable<int> seltrig { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<short> cache { get; set; }
    }
}
