//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class systypes_view
    {
        public string name { get; set; }
        public byte xtype { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<short> xusertype { get; set; }
        public short length { get; set; }
        public byte xprec { get; set; }
        public byte xscale { get; set; }
        public int tdefault { get; set; }
        public int domain { get; set; }
        public Nullable<short> uid { get; set; }
        public Nullable<short> reserved { get; set; }
        public Nullable<int> collationid { get; set; }
        public Nullable<short> usertype { get; set; }
        public bool variable { get; set; }
        public Nullable<bool> allownulls { get; set; }
        public byte type { get; set; }
        public string printfmt { get; set; }
        public Nullable<short> prec { get; set; }
        public Nullable<byte> scale { get; set; }
        public string collation { get; set; }
    }
}
