//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TellerLogin
    {
        public int TELLER_LOGIN_KEY { get; set; }
        public string TELLER { get; set; }
        public short LOCATION { get; set; }
        public string HOSTNAME { get; set; }
        public System.DateTime LOGIN_DATE { get; set; }
        public Nullable<System.DateTime> LOGOUT_DATE { get; set; }
        public bool LOGGED_IN { get; set; }
        public string SERVER_NAME { get; set; }
    }
}
