//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCreditCard
    {
        public int TEST_CREDIT_CARD_KEY { get; set; }
        public string CARD_NUMBER { get; set; }
        public bool VISA { get; set; }
        public bool MC { get; set; }
        public bool IN_USE { get; set; }
        public Nullable<decimal> GUARANTEE_AMT { get; set; }
        public string TOKEN { get; set; }
        public int TestScenario { get; set; }
    }
}
