//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitleLoanApproval
    {
        public int TITLELOAN_APPROVAL_KEY { get; set; }
        public int TITLELOAN_KEY { get; set; }
        public decimal TLA_WHOLESALE_PCT { get; set; }
        public decimal TLA_CHK_ACCT_PCT { get; set; }
        public decimal TLA_CCARD_PCT { get; set; }
        public decimal TLA_EMP_SINCE_PCT { get; set; }
        public int TLA_EMP_SINCE_MON { get; set; }
        public decimal TLA_BASE_PCT { get; set; }
        public decimal TLA_BASE_AMT { get; set; }
        public decimal TLA_NET_INC_AMT { get; set; }
        public bool TLA_NET_INC_USED { get; set; }
        public decimal TLA_NET_INC_PCT { get; set; }
        public decimal TLA_WHOLE_MIN_PCT { get; set; }
        public decimal TLA_WHOLE_MIN_AMT { get; set; }
        public bool TLA_WHOLE_MIN_USED { get; set; }
        public decimal TLA_MAX_LOAN_AMT { get; set; }
        public bool TLA_MAX_LOAN_USED { get; set; }
        public bool TLA_NET_INC_LIMIT { get; set; }
        public bool TLA_FULL_INS_1000 { get; set; }
        public bool TLA_PAY_VER_500 { get; set; }
        public bool TLA_EMP_3_MON_500 { get; set; }
        public bool TLA_MIN_LOAN_150 { get; set; }
        public bool TLA_MAX_NET_INC_25 { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
        public short ENTERED_LOCATION { get; set; }
        public Nullable<bool> TLA_2ND_LIEN_INCR { get; set; }
        public decimal TLA_2ND_LIEN_INCR_AMT { get; set; }
        public Nullable<decimal> APPROVAL_AMT { get; set; }
        public Nullable<decimal> MGR_OVERRIDE_AMT { get; set; }
        public string MGR_OVERRIDE_INITS { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public int SCORE_VALUE { get; set; }
        public decimal SCORE_AMOUNT { get; set; }
    
        public virtual TitleLoan TitleLoan { get; set; }
    }
}
