//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransDetailCheck
    {
        public int TRANS_DETAIL_CHECK_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public short LOCATION { get; set; }
        public string CHECK_FROM { get; set; }
        public string CHECK_TO { get; set; }
        public decimal CHECK_AMT { get; set; }
        public short CHECK_QTY { get; set; }
        public byte CHECK_TYPE { get; set; }
        public Nullable<int> DRAWER_KEY { get; set; }
        public string DEPOSIT_METHOD { get; set; }
    
        public virtual TransDetail TransDetail { get; set; }
    }
}
