//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransDetail()
        {
            this.AMLAdditionalParties = new HashSet<AMLAdditionalParty>();
            this.AMLOccupations = new HashSet<AMLOccupation>();
            this.CashedChecks = new HashSet<CashedCheck>();
            this.CashedCheckPaymentRefunds = new HashSet<CashedCheckPaymentRefund>();
            this.CourtesyPayouts = new HashSet<CourtesyPayout>();
            this.CpiuDetails = new HashSet<CpiuDetail>();
            this.CreditCardTrans = new HashSet<CreditCardTran>();
            this.CurrencyExchangeTrans = new HashSet<CurrencyExchangeTran>();
            this.DCardChargeBackXRefs = new HashSet<DCardChargeBackXRef>();
            this.DCardChargeBackXRefs1 = new HashSet<DCardChargeBackXRef>();
            this.DepositBags = new HashSet<DepositBag>();
            this.Doc10000TransDetail = new HashSet<Doc10000TransDetail>();
            this.EarnedCreditTrans = new HashSet<EarnedCreditTran>();
            this.InsurancePayments = new HashSet<InsurancePayment>();
            this.Loans = new HashSet<Loan>();
            this.LoanFundings = new HashSet<LoanFunding>();
            this.LoanPayments = new HashSet<LoanPayment>();
            this.OpenEndLoanStatements = new HashSet<OpenEndLoanStatement>();
            this.OverShorts = new HashSet<OverShort>();
            this.PayStubs = new HashSet<PayStub>();
            this.PromiseToPayDetailTrans = new HashSet<PromiseToPayDetailTran>();
            this.PurchaseServices = new HashSet<PurchaseService>();
            this.Receipts = new HashSet<Receipt>();
            this.ScannedDocuments = new HashSet<ScannedDocument>();
            this.TransDetail1 = new HashSet<TransDetail>();
            this.TransDetailAccts = new HashSet<TransDetailAcct>();
            this.TransDetailCashes = new HashSet<TransDetailCash>();
            this.TransDetailChecks = new HashSet<TransDetailCheck>();
            this.TransDetailLoans = new HashSet<TransDetailLoan>();
            this.TransDetailServices = new HashSet<TransDetailService>();
            this.TransferFunds = new HashSet<TransferFund>();
            this.VaultCounts = new HashSet<VaultCount>();
            this.WebLoanCreditFrauds = new HashSet<WebLoanCreditFraud>();
        }
    
        public int TRANS_DETAIL_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public short LOCATION { get; set; }
        public Nullable<int> TRANS_POS_KEY { get; set; }
        public Nullable<int> DRAWERZ_KEY { get; set; }
        public Nullable<int> REVERSE_KEY { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public byte TRANS_CODE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string LOAN_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMLAdditionalParty> AMLAdditionalParties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMLOccupation> AMLOccupations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashedCheck> CashedChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashedCheckPaymentRefund> CashedCheckPaymentRefunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourtesyPayout> CourtesyPayouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CpiuDetail> CpiuDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCardTran> CreditCardTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrencyExchangeTran> CurrencyExchangeTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCardChargeBackXRef> DCardChargeBackXRefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCardChargeBackXRef> DCardChargeBackXRefs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositBag> DepositBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc10000TransDetail> Doc10000TransDetail { get; set; }
        public virtual DrawerZ DrawerZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EarnedCreditTran> EarnedCreditTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurancePayment> InsurancePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanFunding> LoanFundings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanPayment> LoanPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenEndLoanStatement> OpenEndLoanStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverShort> OverShorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayStub> PayStubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromiseToPayDetailTran> PromiseToPayDetailTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseService> PurchaseServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScannedDocument> ScannedDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetail> TransDetail1 { get; set; }
        public virtual TransDetail TransDetail2 { get; set; }
        public virtual TransPOS TransPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetailAcct> TransDetailAccts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetailCash> TransDetailCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetailCheck> TransDetailChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetailLoan> TransDetailLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransDetailService> TransDetailServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferFund> TransferFunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaultCount> VaultCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebLoanCreditFraud> WebLoanCreditFrauds { get; set; }
    }
}
