//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_Zipcodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public US_Zipcodes()
        {
            this.LocationUS_ZipcodesXRef = new HashSet<LocationUS_ZipcodesXRef>();
        }
    
        public string ZIPCODE { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTY { get; set; }
        public short TIMEZONE { get; set; }
        public string MSA_CODE { get; set; }
        public string ZIP_TYPE { get; set; }
        public Nullable<int> DMA { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationUS_ZipcodesXRef> LocationUS_ZipcodesXRef { get; set; }
        public virtual MSA MSA { get; set; }
    }
}
