//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaultMaster()
        {
            this.VaultMasterParsedCashes = new HashSet<VaultMasterParsedCash>();
        }
    
        public int VAULT_KEY { get; set; }
        public short LOCATION { get; set; }
        public string VAULT_MGR { get; set; }
        public Nullable<decimal> VAULT_100 { get; set; }
        public Nullable<decimal> VAULT_50 { get; set; }
        public Nullable<decimal> VAULT_20 { get; set; }
        public Nullable<decimal> VAULT_10 { get; set; }
        public Nullable<decimal> VAULT_05 { get; set; }
        public Nullable<decimal> VAULT_01 { get; set; }
        public Nullable<decimal> VAULT_HLF { get; set; }
        public Nullable<decimal> VAULT_QTR { get; set; }
        public Nullable<decimal> VAULT_DIME { get; set; }
        public Nullable<decimal> VAULT_NIC { get; set; }
        public Nullable<decimal> VAULT_PEN { get; set; }
        public Nullable<decimal> VAULT_MISC { get; set; }
        public decimal VAULT_CASHCHK_AMT { get; set; }
        public Nullable<decimal> VAULT_CCARD_AMT { get; set; }
        public short VAULT_CASHCHK_CNT { get; set; }
        public Nullable<short> VAULT_CCARD_CNT { get; set; }
        public bool MGR_AUDIT_COMPLETE { get; set; }
        public bool VMGR_AUDIT_COMPLETE { get; set; }
        public decimal VAULT_MPAY_PAYDAY_AMT { get; set; }
        public decimal VAULT_OEND_PAYDAY_AMT { get; set; }
        public decimal VAULT_SPAY_TITLE_AMT { get; set; }
        public decimal VAULT_MPAY_TITLE_AMT { get; set; }
        public decimal VAULT_OEND_TITLE_AMT { get; set; }
        public decimal VAULT_SPAY_TITLE_2ND_AMT { get; set; }
        public decimal VAULT_MPAY_TITLE_2ND_AMT { get; set; }
        public decimal VAULT_OEND_TITLE_2ND_AMT { get; set; }
        public decimal VAULT_SPAY_SIG_AMT { get; set; }
        public decimal VAULT_MPAY_SIG_AMT { get; set; }
        public decimal VAULT_OEND_SIG_AMT { get; set; }
        public short VAULT_MPAY_PAYDAY_CNT { get; set; }
        public short VAULT_OEND_PAYDAY_CNT { get; set; }
        public short VAULT_SPAY_TITLE_CNT { get; set; }
        public short VAULT_MPAY_TITLE_CNT { get; set; }
        public short VAULT_OEND_TITLE_CNT { get; set; }
        public short VAULT_SPAY_TITLE_2ND_CNT { get; set; }
        public short VAULT_MPAY_TITLE_2ND_CNT { get; set; }
        public short VAULT_OEND_TITLE_2ND_CNT { get; set; }
        public short VAULT_SPAY_SIG_CNT { get; set; }
        public short VAULT_MPAY_SIG_CNT { get; set; }
        public short VAULT_OEND_SIG_CNT { get; set; }
        public short VAULT_BAG_MIDDAY_CNT { get; set; }
        public short VAULT_BAG_MIDDAY_CHK_CNT { get; set; }
        public decimal VAULT_BAG_MIDDAY_AMT { get; set; }
        public short VAULT_BAG_EODAY_CNT { get; set; }
        public short VAULT_BAG_EODAY_CHK_CNT { get; set; }
        public decimal VAULT_BAG_EODAY_AMT { get; set; }
        public decimal VAULT_SPAY_PAYDAY_CHECKS_AMT { get; set; }
        public short VAULT_SPAY_PAYDAY_CHECKS_CNT { get; set; }
        public decimal VAULT_SPAY_PAYDAY_DEBIT_CARDS_AMT { get; set; }
        public int VAULT_SPAY_PAYDAY_DEBIT_CARDS_CNT { get; set; }
        public short VAULT_GOLD_DAILY_BAGS_CNT { get; set; }
        public decimal VAULT_GOLD_DAILY_BAGS_AMT { get; set; }
        public Nullable<decimal> VAULT_2P { get; set; }
        public Nullable<decimal> VAULT_20P { get; set; }
        public Nullable<decimal> VAULT_02 { get; set; }
        public Nullable<decimal> Vault_Tot_Cash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaultMasterParsedCash> VaultMasterParsedCashes { get; set; }
    }
}
