//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultMgrAssignment
    {
        public int VM_ASSIGN_KEY { get; set; }
        public short LOCATION { get; set; }
        public string LOGGED_ON_INITS { get; set; }
        public string CURRENT_VM_INITS { get; set; }
        public string NEW_VM_INITS { get; set; }
        public string OTHER_AUTH_INITS { get; set; }
        public System.DateTime TIME_ASSIGNED { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
