//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.TitleLoans = new HashSet<TitleLoan>();
            this.VehicleHistories = new HashSet<VehicleHistory>();
        }
    
        public int VEHICLE_KEY { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string VEH_VIN { get; set; }
        public string VEH_MAKE { get; set; }
        public string VEH_MODEL { get; set; }
        public string VEH_BODY { get; set; }
        public string VEH_ENGINE { get; set; }
        public string VEH_TRANS { get; set; }
        public string VEH_DRIVE { get; set; }
        public string VEH_MISC_EQUIP1 { get; set; }
        public string VEH_MISC_EQUIP2 { get; set; }
        public string VEH_MISC_EQUIP3 { get; set; }
        public short VEH_YEAR { get; set; }
        public decimal LIST_PRICE { get; set; }
        public string VEH_COLOR { get; set; }
        public string FUEL_TYPE { get; set; }
        public string PLATE { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitleLoan> TitleLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleHistory> VehicleHistories { get; set; }
    }
}
