//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleQuote
    {
        public int VEHICLE_QUOTE_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public short LOCATION { get; set; }
        public string VIN { get; set; }
        public decimal MILEAGE_VALUE { get; set; }
        public decimal RETAIL_PRICE { get; set; }
        public decimal WHOLESALE_PRICE { get; set; }
        public int MILEAGE { get; set; }
        public string PLATE { get; set; }
    }
}
