//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorHistory
    {
        public int VISITOR_HISTORY_KEY { get; set; }
        public int VISITOR_KEY { get; set; }
        public string IP_ADDRESS { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string PAGE_NAME { get; set; }
        public string METHOD_CALL { get; set; }
        public string SESSION_GUID { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED_WITH_SECONDS { get; set; }
        public Nullable<long> WEB_VISIT_KEY { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
