//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorEmailDisposition
    {
        public int VISITOR_EMAIL_DISPOSITION_KEY { get; set; }
        public int VISITOR_EMAIL_KEY { get; set; }
        public int EMAIL_DISPOSITION_KEY { get; set; }
        public System.DateTime DISPOSITION_DATE { get; set; }
        public string TELLER { get; set; }
    
        public virtual EmailDisposition EmailDisposition { get; set; }
        public virtual VisitorEmail VisitorEmail { get; set; }
    }
}
