//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Ach_Trecs
    {
        public string RecordType { get; set; }
        public string ImportAcct { get; set; }
        public string PostDate { get; set; }
        public string EffectiveDate { get; set; }
        public string TransactionType { get; set; }
        public string DebitCredit { get; set; }
        public string Amount { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public string Reference4 { get; set; }
        public string Reference5 { get; set; }
        public string Details { get; set; }
        public string Reference6 { get; set; }
        public string Reference7 { get; set; }
        public string Reference8 { get; set; }
        public System.DateTime BUSINESS_DATE { get; set; }
        public int TRECS_EXPORT { get; set; }
        public short LOCATION { get; set; }
    }
}
