//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerEmployerIncome
    {
        public int PRIMARY_KEY { get; set; }
        public int EMPLOYER_KEY { get; set; }
        public int INCOME_KEY { get; set; }
        public bool IS_PRIMARY_EMPLOYER { get; set; }
        public string INCOME_TYPE_DESC { get; set; }
        public string INCOME_SOURCE_DESC { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public string EMPLOYER_PHONE { get; set; }
        public bool IS_DIRECT_DEPOSIT { get; set; }
        public string PAY_CYCLE_SPELLED { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string EMPLOY_STATUS { get; set; }
        public bool EMPL_ACTIVE { get; set; }
        public bool EMPL_DELETED { get; set; }
        public string PAY_CYCLE { get; set; }
        public byte PAY_CYCLE_1ST { get; set; }
        public byte PAY_CYCLE_2ND { get; set; }
        public string PAY_CYCLE_MONTH_INT { get; set; }
        public byte PAY_CYCLE_DAY { get; set; }
        public Nullable<System.DateTime> BIWEEK_BASE { get; set; }
        public bool PAY_CYCLE_COUNT_DAYS_FROM_END_OF_MONTH { get; set; }
        public string AMOUNT_CYCLE { get; set; }
        public string AMOUNT_TYPE { get; set; }
        public decimal INCOME_AMOUNT { get; set; }
        public string VERIFY_METHOD { get; set; }
        public string VERIFY_TYPE { get; set; }
        public Nullable<System.DateTime> INCOME_DATE_VERIFIED { get; set; }
        public Nullable<System.DateTime> INCOME_DATE_ENTERED { get; set; }
        public string INCOME_TELLER { get; set; }
        public bool INCOME_ACTIVE { get; set; }
        public Nullable<System.DateTime> INCOME_DATE_DELETED { get; set; }
        public string INCOME_DELETED_TELLER { get; set; }
        public Nullable<System.DateTime> INCOME_DATE_INACTIVE { get; set; }
        public string INCOME_INACTIVE_TELLER { get; set; }
    }
}
