//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EosMoneyOrder
    {
        public Nullable<System.DateTime> trans_date { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public short LOCATION { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public string trx_lastname { get; set; }
        public decimal svc_amount { get; set; }
        public System.DateTime trx_date { get; set; }
        public string tellername { get; set; }
    }
}
