//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LoanApplication
    {
        public int LOAN_APPLICATION_KEY { get; set; }
        public byte LENDER_KEY { get; set; }
        public short LOCATION { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public Nullable<int> VISITOR_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public string FIRST_NAME { get; set; }
        public string MID_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string HOME_PHONE { get; set; }
        public string CELL_PHONE { get; set; }
        public string SSN { get; set; }
        public string ABA_NUM { get; set; }
        public string ACCT_NUM { get; set; }
        public decimal REQ_CASH_AMT { get; set; }
        public string CCARD_NUM { get; set; }
        public string CCARD_CVV { get; set; }
        public byte CCARD_EXP_MONTH { get; set; }
        public short CCARD_EXP_YEAR { get; set; }
        public bool CCARD_IS_DEBIT { get; set; }
        public string CCARD_NAME_ON_CARD { get; set; }
        public string LANGUAGE { get; set; }
        public int STATUS { get; set; }
        public string REASON_DENIED { get; set; }
        public Nullable<System.DateTime> NEXT_PAY_DATE { get; set; }
        public string TELLER { get; set; }
        public string ID_NO { get; set; }
        public string SPOUSE_FIRST_NAME { get; set; }
        public string SPOUSE_MID_NAME { get; set; }
        public string SPOUSE_LAST_NAME { get; set; }
        public string SPOUSE_SSN { get; set; }
        public string SPOUSE_HOME_PHONE { get; set; }
        public string SPOUSE_CELL_PHONE { get; set; }
        public string SPOUSE_WORK_NAME { get; set; }
        public string SPOUSE_WORK_PHONE { get; set; }
        public string SPOUSE_WORK_PHONE_EXT { get; set; }
        public string GENDER { get; set; }
        public Nullable<bool> BOUNCED { get; set; }
        public string HOW_REF_OBSOLETE { get; set; }
        public string EMAIL { get; set; }
        public string REF1_FIRST_NAME { get; set; }
        public string REF1_LAST_NAME { get; set; }
        public string REF1_PHONE { get; set; }
        public string REF1_RELATIONSHIP { get; set; }
        public string REF2_FIRST_NAME { get; set; }
        public string REF2_LAST_NAME { get; set; }
        public string REF2_PHONE { get; set; }
        public string REF2_RELATIONSHIP { get; set; }
        public Nullable<decimal> RI_BALANCE { get; set; }
        public Nullable<System.DateTime> RI_FOLLOWUP { get; set; }
        public Nullable<byte> OWN_RENT_OTHER { get; set; }
        public Nullable<System.DateTime> RESIDENCE_SINCE { get; set; }
        public string LEGAL_NUMBER { get; set; }
        public string COURTESY_CALL_NUM { get; set; }
        public Nullable<int> CUST_ID_TYPE_KEY { get; set; }
        public string CUST_ID_NUM { get; set; }
        public string CUST_ID_SOURCE { get; set; }
        public Nullable<int> CUST_ID_VERIFY_KEY { get; set; }
        public string CUST_ID_VERIFY_OTHER { get; set; }
        public Nullable<bool> ACTIVE_MILITARY { get; set; }
        public Nullable<bool> MILITARY_MEMBER { get; set; }
        public Nullable<bool> MILITARY_ACTIVE_DUTY { get; set; }
        public Nullable<bool> MILITARY_COMBAT_DUTY { get; set; }
        public Nullable<bool> MILITARY_RESERVE_NOT_ACTIVE { get; set; }
        public Nullable<bool> MILITARY_RESERVE_ACTIVE { get; set; }
        public Nullable<decimal> MONTHLY_HOUSING { get; set; }
        public Nullable<bool> INET_APPROVED { get; set; }
        public Nullable<bool> CC_BLOCK { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SOURCE_APP { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string SOURCE_DB { get; set; }
        public int WEB_REFERRAL_METHOD_KEY_OBSOLETE { get; set; }
        public byte CC_COUNT { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<byte> MARITAL_STATUS { get; set; }
        public Nullable<bool> JOINT_LOAN { get; set; }
        public short REFERRAL_METHOD_KEY { get; set; }
        public string LOAN_TYPE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public Nullable<int> PENNY_AUTH_KEY { get; set; }
        public string VEH_MAKE { get; set; }
        public string VEH_MODEL { get; set; }
        public Nullable<short> VEH_YEAR { get; set; }
        public string VEH_VIN { get; set; }
        public string VEH_LIEN_HOLDER_NAME { get; set; }
        public Nullable<decimal> VEH_LIEN_BALANCE { get; set; }
        public Nullable<bool> VEH_LEASED { get; set; }
        public Nullable<bool> ARBITRATION_OPT_IN { get; set; }
        public Nullable<decimal> CCARD_GUARANTEE_AMT { get; set; }
        public string CCARD_TOKEN { get; set; }
        public string FUNDING_TYPE { get; set; }
        public Nullable<System.DateTime> CCARD_FROM_DATE { get; set; }
        public Nullable<byte> CCARD_ISSUE_NUM { get; set; }
        public byte CCARD_BRAND { get; set; }
        public byte CCARD_TYPE { get; set; }
        public bool IS_EPDQ_ONLY { get; set; }
        public int TITLE { get; set; }
        public Nullable<int> LOAN_PRODUCT_KEY { get; set; }
        public Nullable<int> LOAN_PRODUCT_CONFIG_KEY { get; set; }
        public Nullable<int> LOAN_PRODUCT_TILA_KEY { get; set; }
        public Nullable<decimal> APPROVED_AMT { get; set; }
        public Nullable<decimal> SELECTED_AMT { get; set; }
        public Nullable<bool> SELECTED { get; set; }
        public Nullable<byte> SELECTED_TERM { get; set; }
        public Nullable<bool> APPROVED { get; set; }
        public string DETAIL { get; set; }
        public Nullable<System.DateTime> PRIMARY_SCORE_DATE { get; set; }
        public Nullable<short> MODEL_USED { get; set; }
        public Nullable<decimal> FINAL_SCORE { get; set; }
        public Nullable<int> SCORE_SUMMARY_KEY { get; set; }
        public Nullable<bool> IS_PIN_VALIDATED { get; set; }
        public Nullable<System.DateTime> VALIDATED_DATE { get; set; }
    }
}
