//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Notes_LoanPayment
    {
        public System.DateTime NOTEDATE { get; set; }
        public string TELLER { get; set; }
        public string DESCR { get; set; }
        public decimal DOLLARAMOUNT { get; set; }
        public string NOTETEXT { get; set; }
        public string TELLERNAME { get; set; }
        public string CUSTOM1 { get; set; }
        public string CUSTOM2 { get; set; }
        public string CUSTOM3 { get; set; }
        public int LOANPAYMENT_KEY { get; set; }
        public int PAID_LOAN_KEY { get; set; }
        public short PAYMENT_METHOD { get; set; }
        public Nullable<int> RISREPT_KEY { get; set; }
        public byte TRANS_CODE { get; set; }
    }
}
