//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TaskActionResult
    {
        public string AGENT_ACTION_DESC { get; set; }
        public string AGENT_RESULT1_DESC { get; set; }
        public string AGENT_RESULT2_DESC { get; set; }
        public string RIS_Audit_DESC { get; set; }
        public int TASK_ACTION_RESULT_KEY { get; set; }
        public int AGENT_ACTION_KEY { get; set; }
        public int AGENT_RESULT_KEY1 { get; set; }
        public int AGENT_RESULT_KEY2 { get; set; }
        public int RIS_AUDIT_ID { get; set; }
        public bool ALLOW_NOTE { get; set; }
        public int FOLLOWUP_MAX { get; set; }
        public bool SHOW_PAYMENT_FORM { get; set; }
        public Nullable<bool> SHOW_PTP_FORM { get; set; }
        public bool COLLECTOR_BONUS_RPT { get; set; }
        public bool OPT_AUDIT_CAT_CODE { get; set; }
        public Nullable<byte> CBR_OUT_OR_IN_CALL { get; set; }
        public int FOLLOWUP_DEFAULT { get; set; }
        public bool REQUIRE_REASON_FOR_ARREARS { get; set; }
        public bool SHOW_FLOD_FORM { get; set; }
        public byte HOT_KEY { get; set; }
        public bool SHOW_REPO_VENDOR_LIST { get; set; }
    }
}
