//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebBlobLoanXref
    {
        public int WEB_BLOB_LOAN_XREF_KEY { get; set; }
        public int WEB_BLOB_KEY { get; set; }
        public int LOAN_KEY { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual WebBlob WebBlob { get; set; }
    }
}
