//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallBatchTaskExecutionHistory
    {
        public int Web_Call_BatchTask_Execution_Key { get; set; }
        public int Web_Call_BatchTask_Key { get; set; }
        public string CriteriaText { get; set; }
        public string ActionText { get; set; }
        public string TargetWorkItemIDs { get; set; }
        public System.DateTime RunDate { get; set; }
        public string RunBy { get; set; }
    }
}
