//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallCenterLogin
    {
        public int CallCenter_Login_Key { get; set; }
        public string Teller { get; set; }
        public string Server { get; set; }
        public System.DateTime Login_Date { get; set; }
        public Nullable<System.DateTime> Logout_Date { get; set; }
        public bool LoggedIn { get; set; }
    }
}
