//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallApplicationStatusHistory
    {
        public int Web_Call_Application_Status_History_KEY { get; set; }
        public int Loan_Application_Key { get; set; }
        public int Web_Call_RARR_History_Key { get; set; }
        public int Loan_Application_Status { get; set; }
        public Nullable<System.DateTime> Application_Status_Change_Date { get; set; }
        public System.DateTime CREATEDATE { get; set; }
    }
}
