//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallWorkItemCategoryHistory
    {
        public int WEB_CALL_WORK_ITEM_CATEGORY_HISTORY_KEY { get; set; }
        public int WEB_CALL_QUEUE_KEY { get; set; }
        public int WEB_CALL_CATEGORY_KEY { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual WebCallCategory WebCallCategory { get; set; }
    }
}
