//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallFeature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebCallFeature()
        {
            this.WebCallRARRFeatures = new HashSet<WebCallRARRFeature>();
        }
    
        public int WEB_CALL_FEATURES_KEY { get; set; }
        public string NAME { get; set; }
        public byte DISPLAY_ORDER { get; set; }
        public bool SupDualAuthEnabled { get; set; }
        public bool CSRDualAuthEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebCallRARRFeature> WebCallRARRFeatures { get; set; }
    }
}
