//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallIntraChatSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebCallIntraChatSession()
        {
            this.WebCallIntraChatMessages = new HashSet<WebCallIntraChatMessage>();
        }
    
        public int Web_Call_IntraChat_Session_Key { get; set; }
        public string From_User_Id { get; set; }
        public string To_User_Id { get; set; }
        public bool From_User_Logged_In { get; set; }
        public bool To_User_Logged_In { get; set; }
        public Nullable<System.DateTime> From_User_LogOut_Date { get; set; }
        public Nullable<System.DateTime> To_User_LogOut_Date { get; set; }
        public System.DateTime Date_Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebCallIntraChatMessage> WebCallIntraChatMessages { get; set; }
    }
}
