//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallRarrGroup
    {
        public int Web_Call_Rarr_Group_KEY { get; set; }
        public string Description { get; set; }
        public bool DELETED { get; set; }
        public Nullable<int> Points { get; set; }
        public int RarrCountOffset { get; set; }
    }
}
