//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallRecordingArchive
    {
        public int WEB_CALL_RECORDING_ARCHIVE_KEY { get; set; }
        public int WEB_ARCHIVE_KEY { get; set; }
        public string SESSION_ID { get; set; }
        public string TELLER { get; set; }
        public System.DateTime CALL_DATE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    
        public virtual WebArchive WebArchive { get; set; }
    }
}
