//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebCallAuthorizedVisitorContact
    {
        public int Web_Call_Authorized_Visitor_Contact_Key { get; set; }
        public int Visitor_Key { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Relationship { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public System.DateTime Date_Entered { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
