//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDialerPhoneLine
    {
        public int WEB_DIALER_PHONE_LINE_KEY { get; set; }
        public string DESCRIPTION { get; set; }
        public int LINE_NO { get; set; }
        public int COLOR_RGB { get; set; }
        public bool ENABLED { get; set; }
        public string PHONE { get; set; }
    }
}
