//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDailyReportField
    {
        public int web_daily_report_fields_key { get; set; }
        public string field_description { get; set; }
        public string group_name { get; set; }
        public int Group_Sort_Priority { get; set; }
        public int Field_Sort_Priority { get; set; }
        public bool Disabled { get; set; }
        public Nullable<bool> allow_range { get; set; }
    }
}
