//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebImage
    {
        public int WEB_IMAGE_KEY { get; set; }
        public int LOAN_APPLICATION_KEY { get; set; }
        public byte[] DATA { get; set; }
        public string SOURCE_URL { get; set; }
        public string SOURCE_HTML { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
