//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLeadGenAddress
    {
        public int WEB_LEAD_GEN_ADDRESS_KEY { get; set; }
        public int WEB_LEAD_GEN_KEY { get; set; }
        public string ADDRESS { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string FAX_NUMBER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string ENTERED_BY { get; set; }
    
        public virtual WebLeadGen WebLeadGen { get; set; }
    }
}
