//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLeadGenTier
    {
        public int Web_Lead_Gen_Key { get; set; }
        public int Score { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int WEB_LEAD_GEN_TIERS_KEY { get; set; }
    
        public virtual WebLeadGen WebLeadGen { get; set; }
    }
}
