//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPixelVendorData
    {
        public int WPVD_KEY { get; set; }
        public int LOAN_APPLICATION_KEY { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string IP_Address { get; set; }
        public int ScoringVendor { get; set; }
        public Nullable<short> MSForResponse { get; set; }
        public string PassWarnFail { get; set; }
        public string RawResponse { get; set; }
        public string DEVICE_ALIAS { get; set; }
        public string VendorResponseMessage { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual WebPixelVendor WebPixelVendor { get; set; }
    }
}
