//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebReportByLoan
    {
        public int web_report_by_loan_key { get; set; }
        public int loan_key { get; set; }
        public Nullable<int> customer_key { get; set; }
        public System.DateTime date_entered { get; set; }
        public Nullable<System.DateTime> adjusted_due_date { get; set; }
        public Nullable<bool> is_customer_new { get; set; }
        public Nullable<bool> is_loan_rollover { get; set; }
        public Nullable<bool> is_loan_open { get; set; }
        public Nullable<bool> is_loan_defaulted { get; set; }
        public Nullable<bool> is_paid_in_full { get; set; }
        public string msa { get; set; }
        public Nullable<int> location { get; set; }
        public string def_state { get; set; }
        public Nullable<decimal> princ_amt { get; set; }
        public Nullable<decimal> fee_amt { get; set; }
        public Nullable<bool> is_first_internet_loan { get; set; }
        public string source { get; set; }
        public Nullable<bool> is_approved_by_scoring { get; set; }
        public Nullable<decimal> cash_amt { get; set; }
        public Nullable<decimal> net_income { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
    }
}
