//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteEvent
    {
        public int WEB_SITE_EVENT_KEY { get; set; }
        public Nullable<int> CUSTOMER_KEY { get; set; }
        public Nullable<int> VISITOR_KEY { get; set; }
        public Nullable<int> LOAN_KEY { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
        public string EVENT_NAME { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
    }
}
