//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebVisit
    {
        public long WEB_VISIT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public System.DateTime DATE_SESSION_END { get; set; }
        public string USER_AGENT { get; set; }
        public string IP_ADDRESS { get; set; }
        public string DESTINATION_URL { get; set; }
        public string DESTINATION_DOMAIN { get; set; }
        public bool IS_SECURE_URL { get; set; }
        public string SOURCE_URL { get; set; }
        public string SOURCE_DOMAIN { get; set; }
        public string SEARCH_QUERY { get; set; }
        public string KEYWORDS { get; set; }
        public string DESCRIPTION { get; set; }
        public string LINK_TYPE { get; set; }
        public string VENDOR { get; set; }
        public string CHANNEL { get; set; }
        public string SUB_CHANNEL { get; set; }
        public string CAMPAIGN { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> VISITOR_KEY { get; set; }
        public Nullable<int> LOAN_APPLICATION_KEY { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
