//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebVisitSrcXref
    {
        public int WebVisitSrcXref_key { get; set; }
        public Nullable<int> Loan_Key { get; set; }
        public Nullable<int> Customer_Key { get; set; }
        public Nullable<int> Loan_Application_Key { get; set; }
        public Nullable<int> Visitor_Key { get; set; }
        public string WebVisit_Session_Guid { get; set; }
        public long WebVisitSource_Key { get; set; }
        public string Source_Credit_Category { get; set; }
    }
}
