//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xca
    {
        public int cakey { get; set; }
        public Nullable<int> ckey { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string X { get; set; }
        public string Spell_ADDRESS_SOURCE_CODE { get; set; }
        public string Spell_ADDRESS_STATUS_CODE { get; set; }
        public string Spell_ADDRESS_TYPE_CODE { get; set; }
        public string Spell_ADDR_SUFFIX { get; set; }
        public string Spell_ADDR_SUITE { get; set; }
        public string Z { get; set; }
        public int CUSTOMER_ADDRESS_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public byte ADDRESS_TYPE_CODE { get; set; }
        public byte ADDRESS_SOURCE_CODE { get; set; }
        public byte ADDRESS_STATUS_CODE { get; set; }
        public short ADDRESS_PRIORITY { get; set; }
        public string ADDRESS_CONTACT_LAST_NAME { get; set; }
        public string ADDRESS_CONTACT_FIRST_NAME { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string TELLER { get; set; }
        public Nullable<System.DateTime> DATE_LAST_USED { get; set; }
        public Nullable<System.DateTime> STATUS_CHANGE_DATE { get; set; }
        public string STATUS_CHANGE_TELLER { get; set; }
        public Nullable<System.DateTime> PRIORITY_CHANGE_DATE { get; set; }
        public string PRIORITY_CHANGE_TELLER { get; set; }
        public string ADDR_NUM { get; set; }
        public string ADDR_PRE_DIR { get; set; }
        public string ADDR_STREET { get; set; }
        public string ADDR_SUFFIX { get; set; }
        public string ADDR_POST_DIR { get; set; }
        public string ADDR_SUITE { get; set; }
        public string ADDR_SUITE_NUM { get; set; }
        public System.DateTime LAST_UPDATED { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string ADDRESS_FORMAT { get; set; }
        public string FLAT_NUM { get; set; }
        public string BUILDING_NUM { get; set; }
        public string BUILDING_NAME { get; set; }
        public string ADDRESS_LINE { get; set; }
        public string ADDRESS_CSZ { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public Nullable<byte> REMOVED_REASON_KEY { get; set; }
        public string REMOVED_REASON_NOTES { get; set; }
    }
}
