//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xccp
    {
        public int ccpkey { get; set; }
        public int cckey { get; set; }
        public int tdkey { get; set; }
        public string Spell_TRANS_CODE { get; set; }
        public int ckey { get; set; }
        public int CASHED_CHECK_PAYMENT_KEY { get; set; }
        public int CASHED_CHECK_KEY { get; set; }
        public int TRANS_DETAIL_KEY { get; set; }
        public short LOCATION { get; set; }
        public string TELLER { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public string NOTE { get; set; }
        public decimal PAID_AMT { get; set; }
        public bool REVERSED { get; set; }
        public Nullable<System.DateTime> REVERSED_DATE { get; set; }
        public short PAYMENT_METHOD { get; set; }
        public byte TRANS_CODE { get; set; }
    }
}
