//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xcm
    {
        public int cmkey { get; set; }
        public int rrkey { get; set; }
        public Nullable<int> rakey { get; set; }
        public int COLLECTION_MOVEMENT_KEY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public int RISREPT_KEY { get; set; }
        public int AUDIT_KEY { get; set; }
        public Nullable<System.DateTime> FOLLOWUP_DATE { get; set; }
        public Nullable<int> COLLECTION_AGENCY_KEY { get; set; }
        public Nullable<byte> ASSIGNMENT_NUMBER { get; set; }
        public string CR_TELLER { get; set; }
        public Nullable<int> REASON_FOR_ARREARS_KEY { get; set; }
        public string ra { get; set; }
        public string AUDIT { get; set; }
        public string DESC { get; set; }
        public string SHORT { get; set; }
        public Nullable<int> RIS_Audit_Id { get; set; }
        public Nullable<bool> Displayed { get; set; }
        public Nullable<bool> IS_AD_ASTRA { get; set; }
        public Nullable<bool> IS_IN_LEGAL_STATUS { get; set; }
        public Nullable<int> RIS_AUDIT_KEY { get; set; }
        public Nullable<bool> DIALER_EXCLUDE { get; set; }
        public Nullable<bool> SUSPEND_INTEREST { get; set; }
        public Nullable<bool> REPOSSESSION { get; set; }
        public Nullable<bool> BLOCK_EMAILS { get; set; }
        public Nullable<bool> IS_ELIGIBLE_FOR_REPO { get; set; }
        public Nullable<bool> BLOCK_STATEMENTS { get; set; }
        public Nullable<bool> IS_PTP { get; set; }
    }
}
