//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xflb
    {
        public int flbkey { get; set; }
        public int FORM_LETTER_BATCH_KEY { get; set; }
        public System.DateTime BATCH_DATE { get; set; }
        public string TELLER { get; set; }
        public string UPLOAD_OR_DOWNLOAD { get; set; }
        public bool IS_AD_ASTRA { get; set; }
        public byte FORM_LETTER_BATCH_STATUS_KEY { get; set; }
        public Nullable<System.DateTime> BATCH_STATUS_DATETIME { get; set; }
        public Nullable<byte> BATCH_STEP { get; set; }
        public string X { get; set; }
        public string FIRSTNAME { get; set; }
        public string LSTNAME { get; set; }
        public Nullable<int> PRINTED_LETTERS { get; set; }
    }
}
