//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6EdmxData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xssrd
    {
        public int ssrdkey { get; set; }
        public int ssrkey { get; set; }
        public Nullable<int> ahkey { get; set; }
        public Nullable<int> tdkey { get; set; }
        public Nullable<int> clpkey { get; set; }
        public Nullable<int> vlpkey { get; set; }
        public int lkey { get; set; }
        public int zrlkey { get; set; }
        public int ckey { get; set; }
        public string ssrd { get; set; }
        public int SPAY_SCHED_ROLLOVER_DETAIL_KEY { get; set; }
        public int SPAY_SCHED_ROLLOVER_KEY { get; set; }
        public System.DateTime ROLLOVER_DATE { get; set; }
        public decimal OPT_BUYDOWN_AMT { get; set; }
        public byte ROLLOVER_NUM { get; set; }
        public decimal LOAN_AMT { get; set; }
        public decimal PRINC_AMT { get; set; }
        public decimal LOAN_ATR { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public Nullable<int> ACH_HISTORY_KEY { get; set; }
        public Nullable<int> TRANS_DETAIL_KEY { get; set; }
        public Nullable<int> CANCEL_LOAN_PAYMENT_KEY { get; set; }
        public Nullable<int> VOID_LOAN_PAYMENT_KEY { get; set; }
        public Nullable<int> SCHED_LOAN_PAYMENT_KEY { get; set; }
        public string ssr { get; set; }
        public int LOAN_KEY { get; set; }
        public int ZERO_REC_LOAN_KEY { get; set; }
        public int CUSTOMER_KEY { get; set; }
        public int LOAN_PAYMENT_KEY { get; set; }
        public byte NUM_ROLLOVERS { get; set; }
    }
}
